# SPDX-License-Identifier: GPL-2.0
# Samsung pin control drivers

obj-$(CONFIG_PINCTRL_SAMSUNG)	+= pinctrl-samsung-core.o
pinctrl-samsung-core-$(CONFIG_PINCTRL_SAMSUNG)	+= pinctrl-samsung.o
pinctrl-samsung-core-$(CONFIG_PINCTRL_EXYNOS)	+= pinctrl-exynos.o
pinctrl-samsung-core-$(CONFIG_PINCTRL_EXYNOS_ARM)	+= pinctrl-exynos-arm.o
pinctrl-samsung-core-$(CONFIG_PINCTRL_EXYNOS_ARM64)	+= pinctrl-exynos-arm64.o
pinctrl-samsung-core-$(CONFIG_PINCTRL_GS)	+= pinctrl-gs.o
pinctrl-samsung-core-$(CONFIG_PINCTRL_S3C24XX)	+= pinctrl-s3c24xx.o
pinctrl-samsung-core-$(CONFIG_PINCTRL_S3C64XX)	+= pinctrl-s3c64xx.o
