# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_ION_EXYNOS) += ion_exynos_mod.o
ion_exynos_mod-y += ion_exynos.o
ion_exynos_mod-$(CONFIG_ION_EXYNOS_CMA_HEAP) += ion_cma_heap.o
ion_exynos_mod-$(CONFIG_ION_EXYNOS_CARVEOUT_HEAP) += ion_carveout_heap.o
ion_exynos_mod-$(CONFIG_EXYNOS_CONTENT_PATH_PROTECTION) += ion_buffer_protect.o
