#!/bin/bash

ln -s ../os_if/sync/inc/osif_driver_sync.h osif_driver_sync.h
ln -s ../os_if/sync/inc/osif_psoc_sync.h osif_psoc_sync.h
ln -s ../os_if/sync/inc/osif_vdev_sync.h osif_vdev_sync.h
ln -s ../os_if/sync/inc/osif_sync.h osif_sync.h
ln -s ../os_if/sync/src/__osif_driver_sync.h __osif_driver_sync.h
ln -s ../os_if/sync/src/__osif_vdev_sync.h __osif_vdev_sync.h
ln -s ../os_if/sync/src/__osif_psoc_sync.h __osif_psoc_sync.h
ln -s ../os_if/son/inc/os_if_son.h os_if_son.h
ln -s ../os_if/p2p/inc/wlan_cfg80211_p2p.h wlan_cfg80211_p2p.h
ln -s ../os_if/tdls/inc/wlan_cfg80211_tdls.h wlan_cfg80211_tdls.h
ln -s ../os_if/pkt_capture/inc/os_if_pkt_capture.h os_if_pkt_capture.h
ln -s ../os_if/interop_issues_ap/inc/wlan_cfg80211_interop_issues_ap.h wlan_cfg80211_interop_issues_ap.h
ln -s ../os_if/twt/inc/osif_twt_ext_req.h osif_twt_ext_req.h
ln -s ../os_if/twt/inc/osif_twt_ext_rsp.h osif_twt_ext_rsp.h
ln -s ../os_if/twt/inc/osif_twt_internal.h osif_twt_internal.h
ln -s ../os_if/coex/inc/wlan_cfg80211_coex.h wlan_cfg80211_coex.h
ln -s ../os_if/nan/inc/os_if_nan.h os_if_nan.h
ln -s ../os_if/fw_offload/inc/os_if_fwol.h os_if_fwol.h
ln -s ../os_if/cp_stats/inc/wlan_cfg80211_mc_cp_stats.h wlan_cfg80211_mc_cp_stats.h
ln -s ../components/disa/dispatcher/inc/wlan_disa_ucfg_api.h wlan_disa_ucfg_api.h
ln -s ../components/disa/dispatcher/inc/wlan_disa_tgt_api.h wlan_disa_tgt_api.h
ln -s ../components/disa/dispatcher/inc/wlan_disa_obj_mgmt_api.h wlan_disa_obj_mgmt_api.h
ln -s ../components/disa/dispatcher/inc/wlan_disa_obj_mgmt_public_struct.h wlan_disa_obj_mgmt_public_struct.h
ln -s ../components/disa/dispatcher/inc/wlan_disa_public_struct.h wlan_disa_public_struct.h
ln -s ../components/disa/core/inc/wlan_disa_main.h wlan_disa_main.h
ln -s ../components/disa/core/inc/wlan_disa_objmgr.h wlan_disa_objmgr.h
ln -s ../components/disa/core/inc/wlan_disa_priv.h wlan_disa_priv.h
ln -s ../components/son/dispatcher/inc/son_api.h son_api.h
ln -s ../components/son/dispatcher/inc/son_ucfg_api.h son_ucfg_api.h
ln -s ../components/cfg/cfg_all.h cfg_all.h
ln -s ../components/ocb/dispatcher/inc/wlan_ocb_public_structs.h wlan_ocb_public_structs.h
ln -s ../components/ocb/dispatcher/inc/wlan_ocb_tgt_api.h wlan_ocb_tgt_api.h
ln -s ../components/ocb/dispatcher/inc/wlan_ocb_ucfg_api.h wlan_ocb_ucfg_api.h
ln -s ../components/ocb/core/inc/wlan_ocb_main.h wlan_ocb_main.h
ln -s ../components/umac/mlme/mlo_mgr/inc/wlan_mlo_mgr_roam.h wlan_mlo_mgr_roam.h
ln -s ../components/umac/mlme/wfa_config/dispatcher/inc/wlan_wfa_ucfg_api.h wlan_wfa_ucfg_api.h
ln -s ../components/umac/mlme/wfa_config/dispatcher/inc/wlan_wfa_tgt_if_tx_api.h wlan_wfa_tgt_if_tx_api.h
ln -s ../components/umac/mlme/wfa_config/dispatcher/inc/wlan_wfa_config_public_struct.h wlan_wfa_config_public_struct.h
ln -s ../components/umac/mlme/connection_mgr/utf/inc/cm_utf.h cm_utf.h
ln -s ../components/umac/mlme/connection_mgr/dispatcher/inc/wlan_cm_roam_public_struct.h wlan_cm_roam_public_struct.h
ln -s ../components/umac/mlme/connection_mgr/dispatcher/inc/wlan_cm_roam_ucfg_api.h wlan_cm_roam_ucfg_api.h
ln -s ../components/umac/mlme/connection_mgr/dispatcher/inc/wlan_cm_roam_api.h wlan_cm_roam_api.h
ln -s ../components/umac/mlme/connection_mgr/dispatcher/inc/wlan_cm_tgt_if_tx_api.h wlan_cm_tgt_if_tx_api.h
ln -s ../components/umac/mlme/connection_mgr/core/src/wlan_cm_vdev_api.h wlan_cm_vdev_api.h
ln -s ../components/umac/mlme/connection_mgr/core/src/wlan_cm_roam_i.h wlan_cm_roam_i.h
ln -s ../components/umac/mlme/connection_mgr/core/src/wlan_cm_roam_offload.h wlan_cm_roam_offload.h
ln -s ../components/umac/twt/dispatcher/inc/wlan_twt_ext_type.h wlan_twt_ext_type.h
ln -s ../components/umac/twt/dispatcher/inc/wlan_twt_ucfg_ext_api.h wlan_twt_ucfg_ext_api.h
ln -s ../components/umac/twt/dispatcher/inc/cfg_twt.h cfg_twt.h
ln -s ../components/umac/twt/dispatcher/inc/wlan_twt_cfg_ext_api.h wlan_twt_cfg_ext_api.h
ln -s ../components/umac/twt/dispatcher/inc/wlan_twt_ext_defs.h wlan_twt_ext_defs.h
ln -s ../components/umac/twt/dispatcher/inc/wlan_twt_tgt_if_ext_tx_api.h wlan_twt_tgt_if_ext_tx_api.h
ln -s ../components/umac/twt/core/src/wlan_twt_main.h wlan_twt_main.h
ln -s ../components/umac/twt/core/src/wlan_twt_cfg.h wlan_twt_cfg.h
ln -s ../components/mlme/dispatcher/inc/wlan_mlme_twt_public_struct.h wlan_mlme_twt_public_struct.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_wep_params.h cfg_mlme_wep_params.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_nss_chains.h cfg_mlme_nss_chains.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_dot11mode.h cfg_mlme_dot11mode.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_lfr.h cfg_mlme_lfr.h
ln -s ../components/mlme/dispatcher/inc/cfg_sap_protection.h cfg_sap_protection.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_btm.h cfg_mlme_btm.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_wifi_pos.h cfg_mlme_wifi_pos.h
ln -s ../components/mlme/dispatcher/inc/wlan_mlme_public_struct.h wlan_mlme_public_struct.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_twt.h cfg_mlme_twt.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_oce.h cfg_mlme_oce.h
ln -s ../components/mlme/dispatcher/inc/wlan_ext_mlme_obj_types.h wlan_ext_mlme_obj_types.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_feature_flag.h cfg_mlme_feature_flag.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_timeout.h cfg_mlme_timeout.h
ln -s ../components/mlme/dispatcher/inc/wlan_mlme_api.h wlan_mlme_api.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_edca_params.h cfg_mlme_edca_params.h
ln -s ../components/mlme/dispatcher/inc/wlan_mlme_ucfg_api.h wlan_mlme_ucfg_api.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_he_caps.h cfg_mlme_he_caps.h
ln -s ../components/mlme/dispatcher/inc/cfg_qos.h cfg_qos.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_reg.h cfg_mlme_reg.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_chainmask.h cfg_mlme_chainmask.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_power.h cfg_mlme_power.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_eht_caps.h cfg_mlme_eht_caps.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_powersave.h cfg_mlme_powersave.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme.h cfg_mlme.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_rates.h cfg_mlme_rates.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_vht_caps.h cfg_mlme_vht_caps.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_sap.h cfg_mlme_sap.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_dfs.h cfg_mlme_dfs.h
ln -s ../components/mlme/dispatcher/inc/wlan_mlme_product_details_cfg.h wlan_mlme_product_details_cfg.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_fe_rrm.h cfg_mlme_fe_rrm.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_roam_scoring.h cfg_mlme_roam_scoring.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_acs.h cfg_mlme_acs.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_fe_wmm.h cfg_mlme_fe_wmm.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_stats.h cfg_mlme_stats.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_generic.h cfg_mlme_generic.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_obss_ht40.h cfg_mlme_obss_ht40.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_mwc.h cfg_mlme_mwc.h
ln -s ../components/mlme/dispatcher/inc/wlan_mlme_twt_ucfg_api.h wlan_mlme_twt_ucfg_api.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_mbo.h cfg_mlme_mbo.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_sta.h cfg_mlme_sta.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_fe_wlm.h cfg_mlme_fe_wlm.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_wps_params.h cfg_mlme_wps_params.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_ht_caps.h cfg_mlme_ht_caps.h
ln -s ../components/mlme/dispatcher/inc/cfg_mlme_threshold.h cfg_mlme_threshold.h
ln -s ../components/mlme/core/inc/wlan_mlme_main.h wlan_mlme_main.h
ln -s ../components/mlme/core/inc/wlan_mlme_twt_api.h wlan_mlme_twt_api.h
ln -s ../components/mlme/core/inc/wlan_mlme_vdev_mgr_interface.h wlan_mlme_vdev_mgr_interface.h
ln -s ../components/p2p/dispatcher/inc/wlan_p2p_tgt_api.h wlan_p2p_tgt_api.h
ln -s ../components/p2p/dispatcher/inc/wlan_p2p_public_struct.h wlan_p2p_public_struct.h
ln -s ../components/p2p/dispatcher/inc/wlan_p2p_cfg_api.h wlan_p2p_cfg_api.h
ln -s ../components/p2p/dispatcher/inc/wlan_p2p_cfg.h wlan_p2p_cfg.h
ln -s ../components/p2p/dispatcher/inc/wlan_p2p_api.h wlan_p2p_api.h
ln -s ../components/p2p/dispatcher/inc/wlan_p2p_ucfg_api.h wlan_p2p_ucfg_api.h
ln -s ../components/p2p/core/src/wlan_p2p_off_chan_tx.h wlan_p2p_off_chan_tx.h
ln -s ../components/p2p/core/src/wlan_p2p_main.h wlan_p2p_main.h
ln -s ../components/p2p/core/src/wlan_p2p_roc.h wlan_p2p_roc.h
ln -s ../components/tdls/dispatcher/inc/wlan_tdls_cfg.h wlan_tdls_cfg.h
ln -s ../components/tdls/dispatcher/inc/wlan_tdls_tgt_api.h wlan_tdls_tgt_api.h
ln -s ../components/tdls/dispatcher/inc/wlan_tdls_ucfg_api.h wlan_tdls_ucfg_api.h
ln -s ../components/tdls/dispatcher/inc/wlan_tdls_api.h wlan_tdls_api.h
ln -s ../components/tdls/dispatcher/inc/wlan_tdls_cfg_api.h wlan_tdls_cfg_api.h
ln -s ../components/tdls/dispatcher/inc/wlan_tdls_public_structs.h wlan_tdls_public_structs.h
ln -s ../components/tdls/core/src/wlan_tdls_main.h wlan_tdls_main.h
ln -s ../components/tdls/core/src/wlan_tdls_txrx.h wlan_tdls_txrx.h
ln -s ../components/tdls/core/src/wlan_tdls_peer.h wlan_tdls_peer.h
ln -s ../components/tdls/core/src/wlan_tdls_mgmt.h wlan_tdls_mgmt.h
ln -s ../components/tdls/core/src/wlan_tdls_cmds_process.h wlan_tdls_cmds_process.h
ln -s ../components/tdls/core/src/wlan_tdls_ct.h wlan_tdls_ct.h
ln -s ../components/target_if/disa/inc/target_if_disa.h target_if_disa.h
ln -s ../components/target_if/ocb/inc/target_if_ocb.h target_if_ocb.h
ln -s ../components/target_if/p2p/inc/target_if_p2p.h target_if_p2p.h
ln -s ../components/target_if/tdls/inc/target_if_tdls.h target_if_tdls.h
ln -s ../components/target_if/blacklist_mgr/inc/target_if_blm.h target_if_blm.h
ln -s ../components/target_if/action_oui/inc/target_if_action_oui.h target_if_action_oui.h
ln -s ../components/target_if/pkt_capture/inc/target_if_pkt_capture.h target_if_pkt_capture.h
ln -s ../components/target_if/interop_issues_ap/inc/target_if_interop_issues_ap.h target_if_interop_issues_ap.h
ln -s ../components/target_if/ipa/inc/target_if_ipa.h target_if_ipa.h
ln -s ../components/target_if/pmo/inc/target_if_pmo.h target_if_pmo.h
ln -s ../components/target_if/wfa_config/inc/target_if_wfa_testcmd.h target_if_wfa_testcmd.h
ln -s ../components/target_if/connection_mgr/inc/target_if_cm_roam_event.h target_if_cm_roam_event.h
ln -s ../components/target_if/connection_mgr/inc/target_if_cm_roam_offload.h target_if_cm_roam_offload.h
ln -s ../components/target_if/ftm_time_sync/inc/target_if_ftm_time_sync.h target_if_ftm_time_sync.h
ln -s ../components/target_if/coex/inc/target_if_coex.h target_if_coex.h
ln -s ../components/target_if/nan/inc/target_if_nan.h target_if_nan.h
ln -s ../components/target_if/fw_offload/inc/target_if_fwol.h target_if_fwol.h
ln -s ../components/dsc/inc/wlan_dsc_psoc.h wlan_dsc_psoc.h
ln -s ../components/dsc/inc/wlan_dsc.h wlan_dsc.h
ln -s ../components/dsc/inc/wlan_dsc_vdev.h wlan_dsc_vdev.h
ln -s ../components/dsc/inc/wlan_dsc_driver.h wlan_dsc_driver.h
ln -s ../components/dsc/test/wlan_dsc_test.h wlan_dsc_test.h
ln -s ../components/dsc/src/__wlan_dsc.h __wlan_dsc.h
ln -s ../components/blacklist_mgr/dispatcher/inc/wlan_blm_public_struct.h wlan_blm_public_struct.h
ln -s ../components/blacklist_mgr/dispatcher/inc/wlan_cfg_blm.h wlan_cfg_blm.h
ln -s ../components/blacklist_mgr/dispatcher/inc/wlan_blm_api.h wlan_blm_api.h
ln -s ../components/blacklist_mgr/dispatcher/inc/wlan_blm_ucfg_api.h wlan_blm_ucfg_api.h
ln -s ../components/blacklist_mgr/dispatcher/inc/wlan_blm_tgt_api.h wlan_blm_tgt_api.h
ln -s ../components/blacklist_mgr/core/inc/wlan_blm_core.h wlan_blm_core.h
ln -s ../components/blacklist_mgr/core/inc/wlan_blm_main.h wlan_blm_main.h
ln -s ../components/action_oui/dispatcher/inc/wlan_action_oui_ucfg_api.h wlan_action_oui_ucfg_api.h
ln -s ../components/action_oui/dispatcher/inc/wlan_action_oui_public_struct.h wlan_action_oui_public_struct.h
ln -s ../components/action_oui/dispatcher/inc/wlan_action_oui_tgt_api.h wlan_action_oui_tgt_api.h
ln -s ../components/action_oui/core/inc/wlan_action_oui_objmgr.h wlan_action_oui_objmgr.h
ln -s ../components/action_oui/core/inc/wlan_action_oui_priv.h wlan_action_oui_priv.h
ln -s ../components/action_oui/core/inc/wlan_action_oui_main.h wlan_action_oui_main.h
ln -s ../components/pkt_capture/dispatcher/inc/wlan_pkt_capture_public_structs.h wlan_pkt_capture_public_structs.h
ln -s ../components/pkt_capture/dispatcher/inc/wlan_pkt_capture_ucfg_api.h wlan_pkt_capture_ucfg_api.h
ln -s ../components/pkt_capture/dispatcher/inc/cfg_pkt_capture.h cfg_pkt_capture.h
ln -s ../components/pkt_capture/dispatcher/inc/wlan_pkt_capture_tgt_api.h wlan_pkt_capture_tgt_api.h
ln -s ../components/pkt_capture/core/inc/wlan_pkt_capture_data_txrx.h wlan_pkt_capture_data_txrx.h
ln -s ../components/pkt_capture/core/inc/wlan_pkt_capture_mgmt_txrx.h wlan_pkt_capture_mgmt_txrx.h
ln -s ../components/pkt_capture/core/inc/wlan_pkt_capture_main.h wlan_pkt_capture_main.h
ln -s ../components/pkt_capture/core/inc/wlan_pkt_capture_objmgr.h wlan_pkt_capture_objmgr.h
ln -s ../components/pkt_capture/core/inc/wlan_pkt_capture_mon_thread.h wlan_pkt_capture_mon_thread.h
ln -s ../components/pkt_capture/core/inc/wlan_pkt_capture_priv.h wlan_pkt_capture_priv.h
ln -s ../components/interop_issues_ap/dispatcher/inc/wlan_interop_issues_ap_public_structs.h wlan_interop_issues_ap_public_structs.h
ln -s ../components/interop_issues_ap/dispatcher/inc/wlan_interop_issues_ap_tgt_api.h wlan_interop_issues_ap_tgt_api.h
ln -s ../components/interop_issues_ap/dispatcher/inc/wlan_interop_issues_ap_ucfg_api.h wlan_interop_issues_ap_ucfg_api.h
ln -s ../components/interop_issues_ap/core/inc/wlan_interop_issues_ap_api.h wlan_interop_issues_ap_api.h
ln -s ../components/ipa/dispatcher/inc/cfg_ipa.h cfg_ipa.h
ln -s ../components/ipa/dispatcher/inc/wlan_ipa_public_struct.h wlan_ipa_public_struct.h
ln -s ../components/ipa/dispatcher/inc/wlan_ipa_obj_mgmt_api.h wlan_ipa_obj_mgmt_api.h
ln -s ../components/ipa/dispatcher/inc/wlan_ipa_ucfg_api.h wlan_ipa_ucfg_api.h
ln -s ../components/ipa/dispatcher/inc/wlan_ipa_tgt_api.h wlan_ipa_tgt_api.h
ln -s ../components/ipa/core/inc/wlan_ipa_main.h wlan_ipa_main.h
ln -s ../components/ipa/core/inc/wlan_ipa_priv.h wlan_ipa_priv.h
ln -s ../components/ipa/core/inc/wlan_ipa_core.h wlan_ipa_core.h
ln -s ../components/pmo/dispatcher/inc/wlan_pmo_hw_filter_public_struct.h wlan_pmo_hw_filter_public_struct.h
ln -s ../components/pmo/dispatcher/inc/wlan_pmo_common_public_struct.h wlan_pmo_common_public_struct.h
ln -s ../components/pmo/dispatcher/inc/wlan_pmo_tgt_api.h wlan_pmo_tgt_api.h
ln -s ../components/pmo/dispatcher/inc/wlan_pmo_obj_mgmt_public_struct.h wlan_pmo_obj_mgmt_public_struct.h
ln -s ../components/pmo/dispatcher/inc/wlan_pmo_lphb_public_struct.h wlan_pmo_lphb_public_struct.h
ln -s ../components/pmo/dispatcher/inc/wlan_pmo_obj_mgmt_api.h wlan_pmo_obj_mgmt_api.h
ln -s ../components/pmo/dispatcher/inc/wlan_pmo_pkt_filter_public_struct.h wlan_pmo_pkt_filter_public_struct.h
ln -s ../components/pmo/dispatcher/inc/wlan_pmo_mc_addr_filtering_public_struct.h wlan_pmo_mc_addr_filtering_public_struct.h
ln -s ../components/pmo/dispatcher/inc/wlan_pmo_gtk_public_struct.h wlan_pmo_gtk_public_struct.h
ln -s ../components/pmo/dispatcher/inc/wlan_pmo_cfg.h wlan_pmo_cfg.h
ln -s ../components/pmo/dispatcher/inc/wlan_pmo_ucfg_api.h wlan_pmo_ucfg_api.h
ln -s ../components/pmo/dispatcher/inc/wlan_pmo_wow_pulse_cfg.h wlan_pmo_wow_pulse_cfg.h
ln -s ../components/pmo/dispatcher/inc/wlan_pmo_runtime_pm_cfg.h wlan_pmo_runtime_pm_cfg.h
ln -s ../components/pmo/dispatcher/inc/wlan_pmo_wow_public_struct.h wlan_pmo_wow_public_struct.h
ln -s ../components/pmo/dispatcher/inc/wlan_pmo_apf_cfg.h wlan_pmo_apf_cfg.h
ln -s ../components/pmo/dispatcher/inc/wlan_pmo_gpio_wakeup_cfg.h wlan_pmo_gpio_wakeup_cfg.h
ln -s ../components/pmo/dispatcher/inc/wlan_pmo_arp_public_struct.h wlan_pmo_arp_public_struct.h
ln -s ../components/pmo/dispatcher/inc/wlan_pmo_common_cfg.h wlan_pmo_common_cfg.h
ln -s ../components/pmo/dispatcher/inc/wlan_pmo_ns_public_struct.h wlan_pmo_ns_public_struct.h
ln -s ../components/pmo/dispatcher/inc/wlan_pmo_extwow_cfg.h wlan_pmo_extwow_cfg.h
ln -s ../components/pmo/dispatcher/inc/wlan_pmo_pkt_filter_cfg.h wlan_pmo_pkt_filter_cfg.h
ln -s ../components/pmo/core/inc/wlan_pmo_gtk.h wlan_pmo_gtk.h
ln -s ../components/pmo/core/inc/wlan_pmo_hw_filter.h wlan_pmo_hw_filter.h
ln -s ../components/pmo/core/inc/wlan_pmo_main.h wlan_pmo_main.h
ln -s ../components/pmo/core/inc/wlan_pmo_icmp.h wlan_pmo_icmp.h
ln -s ../components/pmo/core/inc/wlan_pmo_pkt_filter.h wlan_pmo_pkt_filter.h
ln -s ../components/pmo/core/inc/wlan_pmo_apf.h wlan_pmo_apf.h
ln -s ../components/pmo/core/inc/wlan_pmo_lphb.h wlan_pmo_lphb.h
ln -s ../components/pmo/core/inc/wlan_pmo_priv.h wlan_pmo_priv.h
ln -s ../components/pmo/core/inc/wlan_pmo_wow.h wlan_pmo_wow.h
ln -s ../components/pmo/core/inc/wlan_pmo_ns.h wlan_pmo_ns.h
ln -s ../components/pmo/core/inc/wlan_pmo_arp.h wlan_pmo_arp.h
ln -s ../components/pmo/core/inc/wlan_pmo_static_config.h wlan_pmo_static_config.h
ln -s ../components/pmo/core/inc/wlan_pmo_suspend_resume.h wlan_pmo_suspend_resume.h
ln -s ../components/pmo/core/inc/wlan_pmo_objmgr.h wlan_pmo_objmgr.h
ln -s ../components/pmo/core/inc/wlan_pmo_mc_addr_filtering.h wlan_pmo_mc_addr_filtering.h
ln -s ../components/wmi/inc/wmi_unified_mc_cp_stats_api.h wmi_unified_mc_cp_stats_api.h
ln -s ../components/wmi/inc/wmi_unified_roam_api.h wmi_unified_roam_api.h
ln -s ../components/wmi/inc/wmi_unified_roam_param.h wmi_unified_roam_param.h
ln -s ../components/ftm_time_sync/dispatcher/inc/wlan_ftm_time_sync_tgt_api.h wlan_ftm_time_sync_tgt_api.h
ln -s ../components/ftm_time_sync/dispatcher/inc/ftm_time_sync_ucfg_api.h ftm_time_sync_ucfg_api.h
ln -s ../components/ftm_time_sync/dispatcher/inc/wlan_ftm_time_sync_public_struct.h wlan_ftm_time_sync_public_struct.h
ln -s ../components/ftm_time_sync/dispatcher/inc/cfg_ftm_time_sync.h cfg_ftm_time_sync.h
ln -s ../components/ftm_time_sync/core/inc/ftm_time_sync_objmgr.h ftm_time_sync_objmgr.h
ln -s ../components/ftm_time_sync/core/inc/ftm_time_sync_main.h ftm_time_sync_main.h
ln -s ../components/ftm_time_sync/core/inc/ftm_time_sync_priv.h ftm_time_sync_priv.h
ln -s ../components/coex/dispatcher/inc/wlan_coex_ucfg_api.h wlan_coex_ucfg_api.h
ln -s ../components/coex/dispatcher/inc/wlan_coex_utils_api.h wlan_coex_utils_api.h
ln -s ../components/coex/dispatcher/inc/wlan_coex_tgt_api.h wlan_coex_tgt_api.h
ln -s ../components/coex/core/inc/wlan_coex_main.h wlan_coex_main.h
ln -s ../components/cmn_services/interface_mgr/inc/wlan_if_mgr_roam.h wlan_if_mgr_roam.h
ln -s ../components/cmn_services/policy_mgr/inc/wlan_policy_mgr_cfg.h wlan_policy_mgr_cfg.h
ln -s ../components/cmn_services/policy_mgr/inc/wlan_policy_mgr_api.h wlan_policy_mgr_api.h
ln -s ../components/cmn_services/policy_mgr/inc/wlan_policy_mgr_public_struct.h wlan_policy_mgr_public_struct.h
ln -s ../components/cmn_services/policy_mgr/inc/wlan_policy_mgr_ucfg.h wlan_policy_mgr_ucfg.h
ln -s ../components/cmn_services/policy_mgr/src/wlan_policy_mgr_tables_no_dbs_i.h wlan_policy_mgr_tables_no_dbs_i.h
ln -s ../components/cmn_services/policy_mgr/src/wlan_policy_mgr_i.h wlan_policy_mgr_i.h
ln -s ../components/cmn_services/policy_mgr/src/wlan_policy_mgr_tables_1x1_dbs_i.h wlan_policy_mgr_tables_1x1_dbs_i.h
ln -s ../components/cmn_services/policy_mgr/src/wlan_policy_mgr_tables_2x2_2g_1x1_5g.h wlan_policy_mgr_tables_2x2_2g_1x1_5g.h
ln -s ../components/cmn_services/policy_mgr/src/wlan_policy_mgr_tables_2x2_dbs_i.h wlan_policy_mgr_tables_2x2_dbs_i.h
ln -s ../components/cmn_services/policy_mgr/src/wlan_policy_mgr_tables_2x2_5g_1x1_2g.h wlan_policy_mgr_tables_2x2_5g_1x1_2g.h
ln -s ../components/cmn_services/policy_mgr/src/wlan_policy_mgr_tables_2x2_dbs_sbs_i.h wlan_policy_mgr_tables_2x2_dbs_sbs_i.h
ln -s ../components/cmn_services/logging/inc/wlan_connectivity_logging.h wlan_connectivity_logging.h
ln -s ../components/nan/dispatcher/inc/cfg_nan_api.h cfg_nan_api.h
ln -s ../components/nan/dispatcher/inc/nan_ucfg_api.h nan_ucfg_api.h
ln -s ../components/nan/dispatcher/inc/cfg_nan.h cfg_nan.h
ln -s ../components/nan/core/inc/wlan_nan_api.h wlan_nan_api.h
ln -s ../components/nan/core/inc/nan_public_structs.h nan_public_structs.h
ln -s ../components/nan/core/src/nan_main_i.h nan_main_i.h
ln -s ../components/fw_offload/dispatcher/inc/cfg_adaptive_dwelltime.h cfg_adaptive_dwelltime.h
ln -s ../components/fw_offload/dispatcher/inc/cfg_fwol.h cfg_fwol.h
ln -s ../components/fw_offload/dispatcher/inc/cfg_fwol_generic.h cfg_fwol_generic.h
ln -s ../components/fw_offload/dispatcher/inc/wlan_fwol_public_structs.h wlan_fwol_public_structs.h
ln -s ../components/fw_offload/dispatcher/inc/wlan_fwol_ucfg_api.h wlan_fwol_ucfg_api.h
ln -s ../components/fw_offload/dispatcher/inc/cfg_ie_whitelist.h cfg_ie_whitelist.h
ln -s ../components/fw_offload/dispatcher/inc/cfg_coex.h cfg_coex.h
ln -s ../components/fw_offload/dispatcher/inc/wlan_fwol_tgt_api.h wlan_fwol_tgt_api.h
ln -s ../components/fw_offload/dispatcher/inc/cfg_neighbor_roam.h cfg_neighbor_roam.h
ln -s ../components/fw_offload/dispatcher/inc/cfg_thermal_temp.h cfg_thermal_temp.h
ln -s ../components/fw_offload/core/inc/wlan_fw_offload_main.h wlan_fw_offload_main.h
ln -s ../components/cp_stats/dispatcher/inc/wlan_cp_stats_ext_type.h wlan_cp_stats_ext_type.h
ln -s ../components/cp_stats/dispatcher/inc/wlan_cp_stats_mc_defs.h wlan_cp_stats_mc_defs.h
ln -s ../components/cp_stats/dispatcher/inc/wlan_cp_stats_mc_ucfg_api.h wlan_cp_stats_mc_ucfg_api.h
ln -s ../components/cp_stats/dispatcher/inc/wlan_cp_stats_mc_tgt_api.h wlan_cp_stats_mc_tgt_api.h
ln -s ../core/mac/inc/sir_mac_prot_def.h sir_mac_prot_def.h
ln -s ../core/mac/inc/sir_mac_prop_exts.h sir_mac_prop_exts.h
ln -s ../core/mac/inc/mac_init_api.h mac_init_api.h
ln -s ../core/mac/inc/wni_api.h wni_api.h
ln -s ../core/mac/inc/wni_cfg.h wni_cfg.h
ln -s ../core/mac/inc/sir_api.h sir_api.h
ln -s ../core/mac/inc/wlan_tgt_def_config.h wlan_tgt_def_config.h
ln -s ../core/mac/inc/qwlan_version.h qwlan_version.h
ln -s ../core/mac/inc/ani_system_defs.h ani_system_defs.h
ln -s ../core/mac/inc/sir_types.h sir_types.h
ln -s ../core/mac/inc/wlan_tgt_def_config_hl.h wlan_tgt_def_config_hl.h
ln -s ../core/mac/inc/mac_trace.h mac_trace.h
ln -s ../core/mac/inc/ani_global.h ani_global.h
ln -s ../core/mac/src/dph/dph_hash_table.h dph_hash_table.h
ln -s ../core/mac/src/sys/legacy/src/system/inc/sys_startup.h sys_startup.h
ln -s ../core/mac/src/sys/legacy/src/system/inc/sys_def.h sys_def.h
ln -s ../core/mac/src/sys/legacy/src/system/inc/sys_entry_func.h sys_entry_func.h
ln -s ../core/mac/src/sys/legacy/src/platform/inc/sys_wrapper.h sys_wrapper.h
ln -s ../core/mac/src/sys/legacy/src/utils/inc/dot11fdefs.h dot11fdefs.h
ln -s ../core/mac/src/sys/legacy/src/utils/inc/utils_parser.h utils_parser.h
ln -s ../core/mac/src/sys/common/inc/wlan_qct_sys.h wlan_qct_sys.h
ln -s ../core/mac/src/pe/sch/sch_sys_params.h sch_sys_params.h
ln -s ../core/mac/src/pe/nan/nan_datapath.h nan_datapath.h
ln -s ../core/mac/src/pe/include/lim_fils_defs.h lim_fils_defs.h
ln -s ../core/mac/src/pe/include/sch_global.h sch_global.h
ln -s ../core/mac/src/pe/include/lim_process_fils.h lim_process_fils.h
ln -s ../core/mac/src/pe/include/lim_global.h lim_global.h
ln -s ../core/mac/src/pe/include/sch_api.h sch_api.h
ln -s ../core/mac/src/pe/include/lim_ft_defs.h lim_ft_defs.h
ln -s ../core/mac/src/pe/include/lim_api.h lim_api.h
ln -s ../core/mac/src/pe/include/lim_ft.h lim_ft.h
ln -s ../core/mac/src/pe/include/lim_session.h lim_session.h
ln -s ../core/mac/src/pe/include/rrm_global.h rrm_global.h
ln -s ../core/mac/src/pe/include/rrm_api.h rrm_api.h
ln -s ../core/mac/src/pe/include/lim_admit_control.h lim_admit_control.h
ln -s ../core/mac/src/pe/include/lim_trace.h lim_trace.h
ln -s ../core/mac/src/pe/include/wmm_apsd.h wmm_apsd.h
ln -s ../core/mac/src/pe/lim/lim_types.h lim_types.h
ln -s ../core/mac/src/pe/lim/lim_prop_exts_utils.h lim_prop_exts_utils.h
ln -s ../core/mac/src/pe/lim/lim_send_messages.h lim_send_messages.h
ln -s ../core/mac/src/pe/lim/lim_security_utils.h lim_security_utils.h
ln -s ../core/mac/src/pe/lim/lim_assoc_utils.h lim_assoc_utils.h
ln -s ../core/mac/src/pe/lim/lim_mlo.h lim_mlo.h
ln -s ../core/mac/src/pe/lim/lim_sme_req_utils.h lim_sme_req_utils.h
ln -s ../core/mac/src/pe/lim/lim_timer_utils.h lim_timer_utils.h
ln -s ../core/mac/src/pe/lim/lim_utils.h lim_utils.h
ln -s ../core/mac/src/pe/lim/lim_scan_result_utils.h lim_scan_result_utils.h
ln -s ../core/mac/src/pe/lim/lim_send_sme_rsp_messages.h lim_send_sme_rsp_messages.h
ln -s ../core/mac/src/pe/lim/lim_session_utils.h lim_session_utils.h
ln -s ../core/mac/src/pe/lim/lim_ser_des_utils.h lim_ser_des_utils.h
ln -s ../core/mac/src/include/dot11f.h dot11f.h
ln -s ../core/mac/src/include/dph_global.h dph_global.h
ln -s ../core/mac/src/include/sir_common.h sir_common.h
ln -s ../core/mac/src/include/utils_api.h utils_api.h
ln -s ../core/mac/src/include/parser_api.h parser_api.h
ln -s ../core/mac/src/include/sir_params.h sir_params.h
ln -s ../core/mac/src/include/sir_debug.h sir_debug.h
ln -s ../core/mac/src/include/sys_global.h sys_global.h
ln -s ../core/sme/inc/sme_api.h sme_api.h
ln -s ../core/sme/inc/sme_qos_api.h sme_qos_api.h
ln -s ../core/sme/inc/sme_trace.h sme_trace.h
ln -s ../core/sme/inc/sme_internal.h sme_internal.h
ln -s ../core/sme/inc/csr_internal.h csr_internal.h
ln -s ../core/sme/inc/sme_rrm_internal.h sme_rrm_internal.h
ln -s ../core/sme/inc/sme_qos_internal.h sme_qos_internal.h
ln -s ../core/sme/inc/sme_nan_datapath.h sme_nan_datapath.h
ln -s ../core/sme/inc/sme_power_save_api.h sme_power_save_api.h
ln -s ../core/sme/inc/wlan_ps_wow_diag.h wlan_ps_wow_diag.h
ln -s ../core/sme/inc/csr_link_list.h csr_link_list.h
ln -s ../core/sme/inc/sme_power_save.h sme_power_save.h
ln -s ../core/sme/inc/sme_rrm_api.h sme_rrm_api.h
ln -s ../core/sme/inc/csr_api.h csr_api.h
ln -s ../core/sme/inc/sme_inside.h sme_inside.h
ln -s ../core/sme/inc/csr_support.h csr_support.h
ln -s ../core/sme/src/csr/csr_inside_api.h csr_inside_api.h
ln -s ../core/cds/inc/cds_sched.h cds_sched.h
ln -s ../core/cds/inc/cds_ieee80211_common.h cds_ieee80211_common.h
ln -s ../core/cds/inc/cds_regdomain.h cds_regdomain.h
ln -s ../core/cds/inc/cds_utils.h cds_utils.h
ln -s ../core/cds/inc/cds_api.h cds_api.h
ln -s ../core/cds/inc/cds_config.h cds_config.h
ln -s ../core/cds/inc/cds_packet.h cds_packet.h
ln -s ../core/cds/inc/cds_reg_service.h cds_reg_service.h
ln -s ../core/cds/src/i_cds_packet.h i_cds_packet.h
ln -s ../core/cds/src/cds_ieee80211_common_i.h cds_ieee80211_common_i.h
ln -s ../core/dp/txrx/ol_txrx_ipa.h ol_txrx_ipa.h
ln -s ../core/dp/txrx/ol_ctrl_txrx_api.h ol_ctrl_txrx_api.h
ln -s ../core/dp/txrx/ol_tx_sched.h ol_tx_sched.h
ln -s ../core/dp/txrx/ol_tx.h ol_tx.h
ln -s ../core/dp/txrx/ol_txrx.h ol_txrx.h
ln -s ../core/dp/txrx/wdi_event_api.h wdi_event_api.h
ln -s ../core/dp/txrx/ol_tx_send.h ol_tx_send.h
ln -s ../core/dp/txrx/ol_tx_classify.h ol_tx_classify.h
ln -s ../core/dp/txrx/ol_txrx_encap.h ol_txrx_encap.h
ln -s ../core/dp/txrx/ipv6_defs.h ipv6_defs.h
ln -s ../core/dp/txrx/ol_txrx_peer_find.h ol_txrx_peer_find.h
ln -s ../core/dp/txrx/ol_osif_txrx_api.h ol_osif_txrx_api.h
ln -s ../core/dp/txrx/ol_rx.h ol_rx.h
ln -s ../core/dp/txrx/ol_rx_fwd.h ol_rx_fwd.h
ln -s ../core/dp/txrx/ol_tx_desc.h ol_tx_desc.h
ln -s ../core/dp/txrx/ol_rx_reorder_timeout.h ol_rx_reorder_timeout.h
ln -s ../core/dp/txrx/wdi_event.h wdi_event.h
ln -s ../core/dp/txrx/ol_tx_queue.h ol_tx_queue.h
ln -s ../core/dp/txrx/ol_rx_reorder.h ol_rx_reorder.h
ln -s ../core/dp/txrx/ol_txrx_types.h ol_txrx_types.h
ln -s ../core/dp/txrx/ol_rx_defrag.h ol_rx_defrag.h
ln -s ../core/dp/txrx/ol_rx_pn.h ol_rx_pn.h
ln -s ../core/dp/txrx/ol_txrx_internal.h ol_txrx_internal.h
ln -s ../core/dp/htt/rx_desc.h rx_desc.h
ln -s ../core/dp/htt/htt_types.h htt_types.h
ln -s ../core/dp/htt/htt_internal.h htt_internal.h
ln -s ../core/dp/ol/inc/ol_txrx_htt_api.h ol_txrx_htt_api.h
ln -s ../core/dp/ol/inc/ol_txrx_stats.h ol_txrx_stats.h
ln -s ../core/dp/ol/inc/ol_txrx_api.h ol_txrx_api.h
ln -s ../core/dp/ol/inc/ol_htt_tx_api.h ol_htt_tx_api.h
ln -s ../core/dp/ol/inc/ol_defines.h ol_defines.h
ln -s ../core/dp/ol/inc/cfg_legacy_dp.h cfg_legacy_dp.h
ln -s ../core/dp/ol/inc/ol_txrx_dbg.h ol_txrx_dbg.h
ln -s ../core/dp/ol/inc/ol_vowext_dbg_defs.h ol_vowext_dbg_defs.h
ln -s ../core/dp/ol/inc/ol_cfg.h ol_cfg.h
ln -s ../core/dp/ol/inc/ol_txrx_ctrl_api.h ol_txrx_ctrl_api.h
ln -s ../core/dp/ol/inc/ol_htt_api.h ol_htt_api.h
ln -s ../core/dp/ol/inc/ol_txrx_osif_api.h ol_txrx_osif_api.h
ln -s ../core/dp/ol/inc/ol_htt_rx_api.h ol_htt_rx_api.h
ln -s ../core/dp/txrx3.0/dp_fisa_rx.h dp_fisa_rx.h
ln -s ../core/dp/txrx3.0/dp_rx_thread.h dp_rx_thread.h
ln -s ../core/dp/txrx3.0/dp_txrx.h dp_txrx.h
ln -s ../core/dp/txrx3.0/dp_swlm.h dp_swlm.h
ln -s ../core/hdd/inc/wlan_hdd_ftm_time_sync.h wlan_hdd_ftm_time_sync.h
ln -s ../core/hdd/inc/wlan_hdd_napi.h wlan_hdd_napi.h
ln -s ../core/hdd/inc/wlan_hdd_connectivity_logging.h wlan_hdd_connectivity_logging.h
ln -s ../core/hdd/inc/hdd_config.h hdd_config.h
ln -s ../core/hdd/inc/wlan_hdd_includes.h wlan_hdd_includes.h
ln -s ../core/hdd/inc/wlan_hdd_p2p.h wlan_hdd_p2p.h
ln -s ../core/hdd/inc/wlan_hdd_debugfs_llstat.h wlan_hdd_debugfs_llstat.h
ln -s ../core/hdd/inc/wlan_hdd_data_stall_detection.h wlan_hdd_data_stall_detection.h
ln -s ../core/hdd/inc/wlan_hdd_tdls.h wlan_hdd_tdls.h
ln -s ../core/hdd/inc/wlan_hdd_gpio_wakeup.h wlan_hdd_gpio_wakeup.h
ln -s ../core/hdd/inc/wlan_hdd_periodic_sta_stats.h wlan_hdd_periodic_sta_stats.h
ln -s ../core/hdd/inc/wlan_hdd_conc_ut.h wlan_hdd_conc_ut.h
ln -s ../core/hdd/inc/wlan_hdd_sysfs_tdls_peers.h wlan_hdd_sysfs_tdls_peers.h
ln -s ../core/hdd/inc/wlan_hdd_sysfs_range_ext.h wlan_hdd_sysfs_range_ext.h
ln -s ../core/hdd/inc/wlan_hdd_debugfs_config.h wlan_hdd_debugfs_config.h
ln -s ../core/hdd/inc/wlan_hdd_regulatory.h wlan_hdd_regulatory.h
ln -s ../core/hdd/inc/wlan_hdd_packet_filter_api.h wlan_hdd_packet_filter_api.h
ln -s ../core/hdd/inc/wlan_hdd_debugfs.h wlan_hdd_debugfs.h
ln -s ../core/hdd/inc/wlan_hdd_sysfs_ipa.h wlan_hdd_sysfs_ipa.h
ln -s ../core/hdd/inc/wlan_hdd_mlo.h wlan_hdd_mlo.h
ln -s ../core/hdd/inc/wlan_hdd_softap_tx_rx.h wlan_hdd_softap_tx_rx.h
ln -s ../core/hdd/inc/wlan_hdd_trace.h wlan_hdd_trace.h
ln -s ../core/hdd/inc/wlan_hdd_hang_event.h wlan_hdd_hang_event.h
ln -s ../core/hdd/inc/wlan_hdd_sysfs.h wlan_hdd_sysfs.h
ln -s ../core/hdd/inc/wlan_hdd_tx_rx.h wlan_hdd_tx_rx.h
ln -s ../core/hdd/inc/wlan_hdd_misc.h wlan_hdd_misc.h
ln -s ../core/hdd/inc/wlan_hdd_cfg.h wlan_hdd_cfg.h
ln -s ../core/hdd/inc/wlan_hdd_tsf.h wlan_hdd_tsf.h
ln -s ../core/hdd/inc/wlan_hdd_debugfs_csr.h wlan_hdd_debugfs_csr.h
ln -s ../core/hdd/inc/wlan_hdd_wmm.h wlan_hdd_wmm.h
ln -s ../core/hdd/inc/wlan_hdd_lro.h wlan_hdd_lro.h
ln -s ../core/hdd/inc/wlan_hdd_packet_filter_rules.h wlan_hdd_packet_filter_rules.h
ln -s ../core/hdd/inc/wlan_hdd_sysfs_policy_mgr.h wlan_hdd_sysfs_policy_mgr.h
ln -s ../core/hdd/inc/wlan_hdd_oemdata.h wlan_hdd_oemdata.h
ln -s ../core/hdd/inc/wlan_hdd_avoid_freq_ext.h wlan_hdd_avoid_freq_ext.h
ln -s ../core/hdd/inc/wlan_hdd_power.h wlan_hdd_power.h
ln -s ../core/hdd/inc/wlan_hdd_gpio.h wlan_hdd_gpio.h
ln -s ../core/hdd/inc/wlan_hdd_driver_ops.h wlan_hdd_driver_ops.h
ln -s ../core/hdd/inc/wlan_hdd_spectralscan.h wlan_hdd_spectralscan.h
ln -s ../core/hdd/inc/wlan_hdd_bcn_recv.h wlan_hdd_bcn_recv.h
ln -s ../core/hdd/inc/wlan_hdd_sysfs_channel.h wlan_hdd_sysfs_channel.h
ln -s ../core/hdd/inc/wlan_hdd_debugfs_unit_test.h wlan_hdd_debugfs_unit_test.h
ln -s ../core/hdd/inc/hdd_dp_cfg.h hdd_dp_cfg.h
ln -s ../core/hdd/inc/wlan_hdd_mdns_offload.h wlan_hdd_mdns_offload.h
ln -s ../core/hdd/inc/wlan_hdd_apf.h wlan_hdd_apf.h
ln -s ../core/hdd/inc/qc_sap_ioctl.h qc_sap_ioctl.h
ln -s ../core/hdd/inc/wlan_hdd_fw_state.h wlan_hdd_fw_state.h
ln -s ../core/hdd/inc/wlan_hdd_wext.h wlan_hdd_wext.h
ln -s ../core/hdd/inc/wlan_hdd_mpta_helper.h wlan_hdd_mpta_helper.h
ln -s ../core/hdd/inc/wlan_hdd_nan.h wlan_hdd_nan.h
ln -s ../core/hdd/inc/wlan_hdd_eht.h wlan_hdd_eht.h
ln -s ../core/hdd/inc/hdd_sar_safety_config.h hdd_sar_safety_config.h
ln -s ../core/hdd/inc/wlan_hdd_sysfs_pkt_log.h wlan_hdd_sysfs_pkt_log.h
ln -s ../core/hdd/inc/wlan_hdd_wowl.h wlan_hdd_wowl.h
ln -s ../core/hdd/inc/wlan_hdd_sysfs_swlm.h wlan_hdd_sysfs_swlm.h
ln -s ../core/hdd/inc/wlan_hdd_he.h wlan_hdd_he.h
ln -s ../core/hdd/inc/wlan_hdd_debugfs_coex.h wlan_hdd_debugfs_coex.h
ln -s ../core/hdd/inc/wlan_hdd_ftm.h wlan_hdd_ftm.h
ln -s ../core/hdd/inc/wlan_hdd_twt.h wlan_hdd_twt.h
ln -s ../core/hdd/inc/wlan_hdd_sysfs_dump_in_progress.h wlan_hdd_sysfs_dump_in_progress.h
ln -s ../core/hdd/inc/wlan_hdd_bootup_marker.h wlan_hdd_bootup_marker.h
ln -s ../core/hdd/inc/wlan_hdd_cfr.h wlan_hdd_cfr.h
ln -s ../core/hdd/inc/wlan_hdd_host_offload.h wlan_hdd_host_offload.h
ln -s ../core/hdd/inc/wlan_hdd_sysfs_sta_info.h wlan_hdd_sysfs_sta_info.h
ln -s ../core/hdd/inc/wlan_hdd_debugfs_mibstat.h wlan_hdd_debugfs_mibstat.h
ln -s ../core/hdd/inc/wlan_hdd_ipa.h wlan_hdd_ipa.h
ln -s ../core/hdd/inc/wlan_hdd_main.h wlan_hdd_main.h
ln -s ../core/hdd/inc/wlan_hdd_ether.h wlan_hdd_ether.h
ln -s ../core/hdd/inc/wlan_hdd_assoc.h wlan_hdd_assoc.h
ln -s ../core/hdd/inc/wlan_hdd_sysfs_connect_info.h wlan_hdd_sysfs_connect_info.h
ln -s ../core/hdd/src/wlan_hdd_sap_cond_chan_switch.h wlan_hdd_sap_cond_chan_switch.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_dp_aggregation.h wlan_hdd_sysfs_dp_aggregation.h
ln -s ../core/hdd/src/wlan_hdd_thermal.h wlan_hdd_thermal.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_wow_ito.h wlan_hdd_sysfs_wow_ito.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_scan_config.h wlan_hdd_sysfs_scan_config.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_thermal_cfg.h wlan_hdd_sysfs_thermal_cfg.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_he_bss_color.h wlan_hdd_sysfs_he_bss_color.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_bmiss.h wlan_hdd_sysfs_bmiss.h
ln -s ../core/hdd/src/wlan_hdd_hostapd_wext.h wlan_hdd_hostapd_wext.h
ln -s ../core/hdd/src/wlan_hdd_active_tos.h wlan_hdd_active_tos.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_txrx_stats.h wlan_hdd_sysfs_txrx_stats.h
ln -s ../core/hdd/src/wlan_hdd_sta_info.h wlan_hdd_sta_info.h
ln -s ../core/hdd/src/wlan_hdd_ioctl.h wlan_hdd_ioctl.h
ln -s ../core/hdd/src/wlan_hdd_son.h wlan_hdd_son.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_add_timestamp.h wlan_hdd_sysfs_add_timestamp.h
ln -s ../core/hdd/src/wlan_hdd_cm_api.h wlan_hdd_cm_api.h
ln -s ../core/hdd/src/wlan_hdd_concurrency_matrix.h wlan_hdd_concurrency_matrix.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_unit_test.h wlan_hdd_sysfs_unit_test.h
ln -s ../core/hdd/src/wlan_hdd_rx_monitor.h wlan_hdd_rx_monitor.h
ln -s ../core/hdd/src/wlan_hdd_p2p_listen_offload.h wlan_hdd_p2p_listen_offload.h
ln -s ../core/hdd/src/wlan_hdd_ocb.h wlan_hdd_ocb.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_motion_detection.h wlan_hdd_sysfs_motion_detection.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_suspend_resume.h wlan_hdd_sysfs_suspend_resume.h
ln -s ../core/hdd/src/wlan_hdd_object_manager.h wlan_hdd_object_manager.h
ln -s ../core/hdd/src/wlan_hdd_stats.h wlan_hdd_stats.h
ln -s ../core/hdd/src/wlan_hdd_btc_chain_mode.h wlan_hdd_btc_chain_mode.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_radar.h wlan_hdd_sysfs_radar.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_dp_trace.h wlan_hdd_sysfs_dp_trace.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_wowl_del_ptrn.h wlan_hdd_sysfs_wowl_del_ptrn.h
ln -s ../core/hdd/src/wlan_hdd_dcs.h wlan_hdd_dcs.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_scan_disable.h wlan_hdd_sysfs_scan_disable.h
ln -s ../core/hdd/src/wlan_hdd_hostapd.h wlan_hdd_hostapd.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_wlan_dbg.h wlan_hdd_sysfs_wlan_dbg.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_gtx_bw_mask.h wlan_hdd_sysfs_gtx_bw_mask.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_modify_acl.h wlan_hdd_sysfs_modify_acl.h
ln -s ../core/hdd/src/wlan_hdd_coex_config.h wlan_hdd_coex_config.h
ln -s ../core/hdd/src/wlan_hdd_rssi_monitor.h wlan_hdd_rssi_monitor.h
ln -s ../core/hdd/src/wlan_hdd_medium_assess.h wlan_hdd_medium_assess.h
ln -s ../core/hdd/src/wlan_hdd_scan.h wlan_hdd_scan.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_mem_stats.h wlan_hdd_sysfs_mem_stats.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_crash_inject.h wlan_hdd_sysfs_crash_inject.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_dp_tx_delay_stats.h wlan_hdd_sysfs_dp_tx_delay_stats.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_stats.h wlan_hdd_sysfs_stats.h
ln -s ../core/hdd/src/wlan_hdd_ext_scan.h wlan_hdd_ext_scan.h
ln -s ../core/hdd/src/wlan_hdd_lpass.h wlan_hdd_lpass.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_fw_mode_config.h wlan_hdd_sysfs_fw_mode_config.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_txrx_stats_console.h wlan_hdd_sysfs_txrx_stats_console.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_reassoc.h wlan_hdd_sysfs_reassoc.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_dcm.h wlan_hdd_sysfs_dcm.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_rts_cts.h wlan_hdd_sysfs_rts_cts.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_txrx_fw_st_rst.h wlan_hdd_sysfs_txrx_fw_st_rst.h
ln -s ../core/hdd/src/wlan_hdd_cfg80211.h wlan_hdd_cfg80211.h
ln -s ../core/hdd/src/wlan_hdd_bss_transition.h wlan_hdd_bss_transition.h
ln -s ../core/hdd/src/wlan_hdd_green_ap.h wlan_hdd_green_ap.h
ln -s ../core/hdd/src/wlan_hdd_station_info.h wlan_hdd_station_info.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_wowl_add_ptrn.h wlan_hdd_sysfs_wowl_add_ptrn.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_monitor_mode_channel.h wlan_hdd_sysfs_monitor_mode_channel.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_tx_stbc.h wlan_hdd_sysfs_tx_stbc.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_get_freq_for_pwr.h wlan_hdd_sysfs_get_freq_for_pwr.h
ln -s ../core/hdd/src/wlan_hdd_disa.h wlan_hdd_disa.h
ln -s ../core/hdd/src/wlan_hdd_nud_tracking.h wlan_hdd_nud_tracking.h
ln -s ../core/hdd/src/wlan_hdd_subnet_detect.h wlan_hdd_subnet_detect.h
ln -s ../core/hdd/src/wlan_hdd_nan_datapath.h wlan_hdd_nan_datapath.h
ln -s ../core/hdd/src/wlan_hdd_unit_test.h wlan_hdd_unit_test.h
ln -s ../core/hdd/src/wlan_hdd_ota_test.h wlan_hdd_ota_test.h
ln -s ../core/hdd/src/wlan_hdd_sar_limits.h wlan_hdd_sar_limits.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_temperature.h wlan_hdd_sysfs_temperature.h
ln -s ../core/hdd/src/wlan_hdd_bus_bandwidth.h wlan_hdd_bus_bandwidth.h
ln -s ../core/hdd/src/wlan_hdd_fips.h wlan_hdd_fips.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_txrx_fw_stats.h wlan_hdd_sysfs_txrx_fw_stats.h
ln -s ../core/hdd/src/wlan_hdd_sysfs_dl_modes.h wlan_hdd_sysfs_dl_modes.h
ln -s ../core/hdd/src/wlan_hdd_hw_capability.h wlan_hdd_hw_capability.h
ln -s ../core/hdd/src/wlan_hdd_tx_power.h wlan_hdd_tx_power.h
ln -s ../core/pld/inc/pld_common.h pld_common.h
ln -s ../core/pld/src/pld_snoc_fw_sim.h pld_snoc_fw_sim.h
ln -s ../core/pld/src/pld_snoc.h pld_snoc.h
ln -s ../core/pld/src/pld_sdio.h pld_sdio.h
ln -s ../core/pld/src/pld_ipci.h pld_ipci.h
ln -s ../core/pld/src/pld_usb.h pld_usb.h
ln -s ../core/pld/src/pld_pcie.h pld_pcie.h
ln -s ../core/pld/src/pld_internal.h pld_internal.h
ln -s ../core/pld/src/pld_pcie_fw_sim.h pld_pcie_fw_sim.h
ln -s ../core/bmi/inc/ol_if_athvar.h ol_if_athvar.h
ln -s ../core/bmi/inc/ol_fw.h ol_fw.h
ln -s ../core/bmi/inc/bmi.h bmi.h
ln -s ../core/bmi/src/i_bmi.h i_bmi.h
ln -s ../core/bmi/src/i_ar6320v2_regtable.h i_ar6320v2_regtable.h
ln -s ../core/sap/inc/sap_api.h sap_api.h
ln -s ../core/sap/src/sap_internal.h sap_internal.h
ln -s ../core/sap/src/sap_ch_select.h sap_ch_select.h
ln -s ../core/sap/src/sap_fsm_ext.h sap_fsm_ext.h
ln -s ../core/wma/inc/wma.h wma.h
ln -s ../core/wma/inc/wma_api.h wma_api.h
ln -s ../core/wma/inc/wma_tgt_cfg.h wma_tgt_cfg.h
ln -s ../core/wma/inc/wma_internal.h wma_internal.h
ln -s ../core/wma/inc/wma_if.h wma_if.h
ln -s ../core/wma/inc/wma_he.h wma_he.h
ln -s ../core/wma/inc/wma_twt.h wma_twt.h
ln -s ../core/wma/inc/wma_fw_state.h wma_fw_state.h
ln -s ../core/wma/inc/wma_types.h wma_types.h
ln -s ../core/wma/inc/wma_coex.h wma_coex.h
ln -s ../core/wma/src/wma_ocb.h wma_ocb.h
ln -s ../core/wma/src/wma_nan_datapath.h wma_nan_datapath.h
ln -s ../core/wma/src/wma_eht.h wma_eht.h
ln -s ../core/wma/src/wma_sar_public_structs.h wma_sar_public_structs.h
ln -s ../core/wma/src/wma_fips_api.h wma_fips_api.h
ln -s ../core/wma/src/wma_fips_public_structs.h wma_fips_public_structs.h
ln -s ../uapi/linux/osapi_linux.h osapi_linux.h
ln -s ../uapi/linux/a_types.h a_types.h
ln -s ../uapi/linux/athstartpack.h athstartpack.h
ln -s ../uapi/linux/debug_linux.h debug_linux.h
ln -s ../uapi/linux/pktlog_ac_fmt.h pktlog_ac_fmt.h
ln -s ../uapi/linux/a_debug.h a_debug.h
ln -s ../uapi/linux/dbglog_common.h dbglog_common.h