dtb-$(CONFIG_SOC_GS101) += \
	gs101.dtb

dtbo-$(CONFIG_BOARD_SLIDER) += \
	gs101-slider.dtbo

gs101-slider.dtbo-base := gs101.dtb

MKDTIMG_FLAGS += --page_size=4096  --id=/:board_id --rev=/:board_rev
