# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_TYPEC_TCPM)	+= tcpm.o
obj-$(CONFIG_TYPEC_FUSB302)	+= fusb302.o
obj-$(CONFIG_TYPEC_WCOVE)	+= typec_wcove.o
typec_wcove-y			:= wcove.o
obj-$(CONFIG_TYPEC_TCPCI)	+= tcpci.o
obj-$(CONFIG_TYPEC_RT1711H)	+= tcpci_rt1711h.o
obj-$(CONFIG_TYPEC_FUSB307)	+= tcpci_fusb307.o slg46826.o
obj-$(CONFIG_USB_PSY)		+= usb_psy.o
obj-$(CONFIG_TYPEC_MAX77759F)	+= tcpci_max77759f.o max77759f_helper.o
obj-$(CONFIG_TYPEC_MAX77759F) 	+= bc_max77759f.o
obj-$(CONFIG_TYPEC_MAX77759F)	+= max77759f_contaminant.o max77759f_contaminant_maxq.o
