# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_TYPEC_TCPM)		+= tcpm.o
obj-$(CONFIG_TYPEC_FUSB302)		+= fusb302.o
obj-$(CONFIG_TYPEC_WCOVE)		+= typec_wcove.o
typec_wcove-y				:= wcove.o
obj-$(CONFIG_TYPEC_TCPCI)		+= tcpci.o
obj-$(CONFIG_TYPEC_RT1711H)		+= tcpci_rt1711h.o
obj-$(CONFIG_TYPEC_FUSB307)		+= tcpci_fusb307.o slg46826.o
obj-$(CONFIG_USB_PSY)			+= usb_psy.o
obj-$(CONFIG_TYPEC_MAX77759)		+= tcpci_max77759.o max77759_helper.o
obj-$(CONFIG_TYPEC_MAX77759)		+= bc_max77759.o
obj-$(CONFIG_TYPEC_MAX77759)		+= max77759_contaminant.o
obj-$(CONFIG_TYPEC_MT6360)		+= tcpci_mt6360.o
obj-$(CONFIG_TYPEC_TCPCI_MAXIM)		+= tcpci_maxim.o
obj-$(CONFIG_TYPEC_COOLING_DEV)		+= usbc_cooling_dev.o
