# SPDX-License-Identifier: GPL-2.0
#
# This file should be included by external modules that need to link to this
# project.

KCFLAGS += -I$(KERNEL_SRC)/../private/google-modules/soc/gs/include
KCFLAGS += -I$(KERNEL_SRC)/../private/google-modules/soc/gs/include/uapi

EXTRA_SYMBOLS += $(O)/../private/google-modules/soc/gs/Module.symvers
