/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Google LWIS ZUMA BE_CORE Interrupt And Event Defines
 *
 * Copyright (c) 2022 Google, LLC
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef DT_BINDINGS_LWIS_PLATFORM_ZUMA_BE_CORE_H_
#define DT_BINDINGS_LWIS_PLATFORM_ZUMA_BE_CORE_H_

#include <dt-bindings/lwis/platform/common.h>

/* clang-format off */


#define BE_CORE_RGBP_INT0_BASE (HW_EVENT_MASK + 0)

#define BE_CORE_RGBP_INT0_FRAME_START 0
#define BE_CORE_RGBP_INT0_FRAME_END 1
#define BE_CORE_RGBP_INT0_CMDQ_HOLD 2
#define BE_CORE_RGBP_INT0_SETTING_DONE 3
#define BE_CORE_RGBP_INT0_C_LOADER_END 4
#define BE_CORE_RGBP_INT0_COREX_END0 5
#define BE_CORE_RGBP_INT0_COREX_END1 6
#define BE_CORE_RGBP_INT0_ROW_COL 7
#define BE_CORE_RGBP_INT0_FREEZE_ON_ROW_COL 8
#define BE_CORE_RGBP_INT0_TRANS_STOP_DONE 9
#define BE_CORE_RGBP_INT0_CMDQ_ERROR 10
#define BE_CORE_RGBP_INT0_C_LOADER_ERROR 11
#define BE_CORE_RGBP_INT0_COREX_ERROR 12
#define BE_CORE_RGBP_INT0_CINFIFO0_OVERFLOW_ERROR 13
#define BE_CORE_RGBP_INT0_CINFIFO0_OVERLAP_ERROR 14
#define BE_CORE_RGBP_INT0_CINFIFO0_PIXEL_CNT_ERROR 15
#define BE_CORE_RGBP_INT0_CINFIFO0_INPUT_PROTOCOL_ERROR 16
#define BE_CORE_RGBP_INT0_COUTFIFO0_PIXEL_CNT_ERROR 21
#define BE_CORE_RGBP_INT0_COUTFIFO0_INPUT_PROTOCOL_ERROR 22
#define BE_CORE_RGBP_INT0_COUTFIFO0_OVERFLOW_ERROR 23
#define BE_CORE_RGBP_INT0_VOTF_GLOBAL_ERROR 27
#define BE_CORE_RGBP_INT0_OTF_SEQ_ID_ERROR 28



#define BE_CORE_RGBP_INT1_BASE (HW_EVENT_MASK + 32)

#define BE_CORE_RGBP_INT1_VOTF_LOST_FLUSH 0
#define BE_CORE_RGBP_INT1_VOTF0_WDMA_GLOBAL_ERROR 1
#define BE_CORE_RGBP_INT1_VOTF0_WDMA_LOST_FLUSH 2
#define BE_CORE_RGBP_INT1_DTP_DBG_CNT_ERROR 3
#define BE_CORE_RGBP_INT1_BDNS_DBG_CNT_ERROR 4
#define BE_CORE_RGBP_INT1_DMSC_DBG_CNT_ERR 5
#define BE_CORE_RGBP_INT1_RGB_GAMMA_DBG_CNT_ERR 6
#define BE_CORE_RGBP_INT1_GTM_DBG_CNT_ERR 7
#define BE_CORE_RGBP_INT1_RGB2YUV_DBG_CNT_ERR 8
#define BE_CORE_RGBP_INT1_YUV444TO422_DBG_CNT_ERR 9
#define BE_CORE_RGBP_INT1_SATFLAG_DBG_CNT_ERR 10
#define BE_CORE_RGBP_INT1_DECOMP_DBG_CNT_ERR 11
#define BE_CORE_RGBP_INT1_CCM_DBG_CNT_ERR 12
#define BE_CORE_RGBP_INT1_YUVSC_DBG_CNT_ERR 13
#define BE_CORE_RGBP_INT1_SYNC_MERGE_COUTFIFO_DBG_CNT_ERR 14



#define BE_CORE_RGBP_CMDQ_INT_BASE (HW_EVENT_MASK + 64)

#define BE_CORE_RGBP_CMDQ_INT_STOP_CRPT_OFF_CMDQ_EN 0
#define BE_CORE_RGBP_CMDQ_INT_PRELOAD_FLUSH 1
#define BE_CORE_RGBP_CMDQ_INT_QUE0_OVERFLOW 2
#define BE_CORE_RGBP_CMDQ_INT_QUE1_OVERFLOW 3
#define BE_CORE_RGBP_CMDQ_INT_QUE_U_OVERFLOW 4
#define BE_CORE_RGBP_CMDQ_INT_QUE0_PUSH_BACK_TO_FULL_QUE 5
#define BE_CORE_RGBP_CMDQ_INT_QUE1_PUSH_BACK_TO_FULL_QUE 6
#define BE_CORE_RGBP_CMDQ_INT_QUE_U_PUSH_BACK_TO_FULL_QUE 7



#define BE_CORE_MCFP_INT0_BASE (HW_EVENT_MASK + 96)

#define BE_CORE_MCFP_INT0_FRAME_START 0
#define BE_CORE_MCFP_INT0_FRAME_END 1
#define BE_CORE_MCFP_INT0_CMDQ_HOLD 2
#define BE_CORE_MCFP_INT0_SETTING_DONE 3
#define BE_CORE_MCFP_INT0_C_LOADER_END 4
#define BE_CORE_MCFP_INT0_COREX_END0 5
#define BE_CORE_MCFP_INT0_COREX_END1 6
#define BE_CORE_MCFP_INT0_ROW_COL 7
#define BE_CORE_MCFP_INT0_FREEZE_ON_ROW_COL 8
#define BE_CORE_MCFP_INT0_TRANS_STOP_DONE 9
#define BE_CORE_MCFP_INT0_CMDQ_ERROR 10
#define BE_CORE_MCFP_INT0_C_LOADER_ERROR 11
#define BE_CORE_MCFP_INT0_COREX_ERROR 12
#define BE_CORE_MCFP_INT0_CINFIFO0_OVERFLOW_ERROR 13
#define BE_CORE_MCFP_INT0_CINFIFO0_OVERLAP_ERROR 14
#define BE_CORE_MCFP_INT0_CINFIFO0_PIXEL_CNT_ERROR 15
#define BE_CORE_MCFP_INT0_CINFIFO0_INPUT_PROTOCOL_ERROR 16
#define BE_CORE_MCFP_INT0_CINFIFO1_OVERFLOW_ERROR 17
#define BE_CORE_MCFP_INT0_CINFIFO1_OVERLAP_ERROR 18
#define BE_CORE_MCFP_INT0_CINFIFO1_PIXEL_CNT_ERROR 19
#define BE_CORE_MCFP_INT0_CINFIFO1_INPUT_PROTOCOL_ERROR 20
#define BE_CORE_MCFP_INT0_COUTFIFO0_PIXEL_CNT_ERROR 21
#define BE_CORE_MCFP_INT0_COUTFIFO0_INPUT_PROTOCOL_ERROR 22
#define BE_CORE_MCFP_INT0_COUTFIFO0_OVERFLOW_ERROR 23
#define BE_CORE_MCFP_INT0_COUTFIFO1_PIXEL_CNT_ERROR 24
#define BE_CORE_MCFP_INT0_COUTFIFO1_INPUT_PROTOCOL_ERROR 25
#define BE_CORE_MCFP_INT0_COUTFIFO1_OVERFLOW_ERROR 26
#define BE_CORE_MCFP_INT0_VOTF_GLOBAL_ERROR 27
#define BE_CORE_MCFP_INT0_VOTF_LOST_CONNECTION 28
#define BE_CORE_MCFP_INT0_OTF_SEQ_ID_ERROR 29



#define BE_CORE_MCFP_INT1_BASE (HW_EVENT_MASK + 128)

#define BE_CORE_MCFP_INT1_RDMA_M0_FINISH 1
#define BE_CORE_MCFP_INT1_RDMA_M1_FINISH 2
#define BE_CORE_MCFP_INT1_RDMA_M3_FINISH 3
#define BE_CORE_MCFP_INT1_RDMA_M4_FINISH 4
#define BE_CORE_MCFP_INT1_RDMA_M5_FINISH 5
#define BE_CORE_MCFP_INT1_RDMA_M6_FINISH 6
#define BE_CORE_MCFP_INT1_RDMA_M10_FINISH 7
#define BE_CORE_MCFP_INT1_RDMA_M11_FINISH 8
#define BE_CORE_MCFP_INT1_RDMA_M12_FINISH 9
#define BE_CORE_MCFP_INT1_RDMA_M13_FINISH 10
#define BE_CORE_MCFP_INT1_RDMA_M14_FINISH 11
#define BE_CORE_MCFP_INT1_WDMA_M10_FINISH 12
#define BE_CORE_MCFP_INT1_WDMA_M11_FINISH 13
#define BE_CORE_MCFP_INT1_WDMA_M12_FINISH 14
#define BE_CORE_MCFP_INT1_PREFETCH_LMC_FINISH 15
#define BE_CORE_MCFP_INT1_LBCTRL_MIX_FINISH 16
#define BE_CORE_MCFP_INT1_HDR_FINISH 17
#define BE_CORE_MCFP_INT1_MIXER_FINISH 18
#define BE_CORE_MCFP_INT1_LBCTRL_GF_FINISH 19
#define BE_CORE_MCFP_INT1_CROP_CLEAN_OTF_FINISH 20
#define BE_CORE_MCFP_INT1_CROP_CLEAN_DMA_Y_FINISH 21
#define BE_CORE_MCFP_INT1_CROP_CLEAN_DMA_C_FINISH 22
#define BE_CORE_MCFP_INT1_CROP_WEIGHT_DMA_FINISH 23
#define BE_CORE_MCFP_INT1_GAMMA_FINISH 24
#define BE_CORE_MCFP_INT1_SBWC_DEC_ERR_L 26
#define BE_CORE_MCFP_INT1_SBWC_DEC_ERR_C 27



#define BE_CORE_MCFP_CMDQ_INT_BASE (HW_EVENT_MASK + 160)

#define BE_CORE_MCFP_CMDQ_INT_STOP_CRPT_OFF_CMDQ_EN 0
#define BE_CORE_MCFP_CMDQ_INT_PRELOAD_FLUSH 1
#define BE_CORE_MCFP_CMDQ_INT_QUE0_OVERFLOW 2



#define BE_CORE_YUVP_INT0_BASE (HW_EVENT_MASK + 192)

#define BE_CORE_YUVP_INT0_FRAME_START 0
#define BE_CORE_YUVP_INT0_FRAME_END 1
#define BE_CORE_YUVP_INT0_CMDQ_HOLD 2
#define BE_CORE_YUVP_INT0_SETTING_DONE 3
#define BE_CORE_YUVP_INT0_C_LOADER_END 4
#define BE_CORE_YUVP_INT0_COREX_END0 5
#define BE_CORE_YUVP_INT0_COREX_END1 6
#define BE_CORE_YUVP_INT0_ROW_COL 7
#define BE_CORE_YUVP_INT0_FREEZE_ON_ROW_COL 8
#define BE_CORE_YUVP_INT0_TRANS_STOP_DONE 9
#define BE_CORE_YUVP_INT0_CMDQ_ERROR 10
#define BE_CORE_YUVP_INT0_C_LOADER_ERROR 11
#define BE_CORE_YUVP_INT0_COREX_ERROR 12
#define BE_CORE_YUVP_INT0_CINFIFO0_OVERFLOW_ERROR 13
#define BE_CORE_YUVP_INT0_CINFIFO0_OVERLAP_ERROR 14
#define BE_CORE_YUVP_INT0_CINFIFO0_PIXEL_CNT_ERROR 15
#define BE_CORE_YUVP_INT0_CINFIFO0_INPUT_PROTOCOL_ERROR 16
#define BE_CORE_YUVP_INT0_COUTFIFO0_PIXEL_CNT_ERROR 21
#define BE_CORE_YUVP_INT0_COUTFIFO0_INPUT_PROTOCOL_ERROR 22
#define BE_CORE_YUVP_INT0_COUTFIFO0_OVERFLOW_ERROR 23
#define BE_CORE_YUVP_INT0_COUTFIFO1_PIXEL_CNT_ERROR 24
#define BE_CORE_YUVP_INT0_COUTFIFO1_INPUT_PROTOCOL_ERROR 25
#define BE_CORE_YUVP_INT0_COUTFIFO1_OVERFLOW_ERROR 26
#define BE_CORE_YUVP_INT0_VOTF_GLOBAL_ERROR 27
#define BE_CORE_YUVP_INT0_VOTF_LOST_CONNECTION 28
#define BE_CORE_YUVP_INT0_OTF_SEQ_ID_ERROR 29



#define BE_CORE_YUVP_INT1_BASE (HW_EVENT_MASK + 224)

#define BE_CORE_YUVP_INT1_VOTF_LOST_FLUSH 0
#define BE_CORE_YUVP_INT1_COUTF02_MCSC_OVERLAP_ERR 1
#define BE_CORE_YUVP_INT1_COUTF02_MCSC_PIXEL_CNT_ERR 2
#define BE_CORE_YUVP_INT1_COUTF02_MCSC_INPUT_PROTOCOL_ERR 3
#define BE_CORE_YUVP_INT1_DTP_DBG_CNT_ERR 4
#define BE_CORE_YUVP_INT1_YUVNR_DBG_CNT_ERR 5
#define BE_CORE_YUVP_INT1_YUV422TO444_DBG_CNT_ERR 6
#define BE_CORE_YUVP_INT1_YUV2RGB_DBG_CNT_ERR 7
#define BE_CORE_YUVP_INT1_RGB2YUV_DBG_CNT_ERR 8
#define BE_CORE_YUVP_INT1_DITHER_DBG_CNT_ERR 9
#define BE_CORE_YUVP_INT1_INVCCM_DBG_CNT_ERR 10
#define BE_CORE_YUVP_INT1_DEGAMMA_DBG_CNT_ERR 11
#define BE_CORE_YUVP_INT1_RGB_GAMMA_DBG_CNT_ERR 12
#define BE_CORE_YUVP_INT1_OETF_GAMMA_DBG_CNT_ERR 13
#define BE_CORE_YUVP_INT1_PRC_DBG_CNT_ERR 14
#define BE_CORE_YUVP_INT1_SHARPEN_DBG_CNT_ERR 15
#define BE_CORE_YUVP_INT1_LTM_DBG_CNT_ERR 16
#define BE_CORE_YUVP_INT1_YUV2RGB_ZUMA_DBG_CNT_ERR 17
#define BE_CORE_YUVP_INT1_DEGAMMA_RGB_MAIN_DBG_CNT_ERR 18
#define BE_CORE_YUVP_INT1_DEGAMMA_RGB_LINER_DBG_CNT_ERR 19
#define BE_CORE_YUVP_INT1_RGB2YUV420_DBG_CNT_ERR 20
#define BE_CORE_YUVP_INT1_RGB2YUV422_DBG_CNT_ERR 21
#define BE_CORE_YUVP_INT1_YUV420TO422_DBG_CNT_ERR 22
#define BE_CORE_YUVP_INT1_CCM_DBG_CNT_ERR 23
#define BE_CORE_YUVP_INT1_CLUT_DBG_CNT_ERR 24



#define BE_CORE_YUVP_CMDQ_INT_BASE (HW_EVENT_MASK + 256)

#define BE_CORE_YUVP_CMDQ_INT_STOP_CRPT_OFF_CMDQ_EN 0
#define BE_CORE_YUVP_CMDQ_INT_PRELOAD_FLUSH 1
#define BE_CORE_YUVP_CMDQ_INT_QUE0_OVERFLOW 2
#define BE_CORE_YUVP_CMDQ_INT_QUE1_OVERFLOW 3
#define BE_CORE_YUVP_CMDQ_INT_QUE_U_OVERFLOW 4
#define BE_CORE_YUVP_CMDQ_INT_QUE0_PUSH_BACK_TO_FULL_QUE 5
#define BE_CORE_YUVP_CMDQ_INT_QUE1_PUSH_BACK_TO_FULL_QUE 6
#define BE_CORE_YUVP_CMDQ_INT_QUE_U_PUSH_BACK_TO_FULL_QUE 7

/* clang-format on */

#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT0_FRAME_START                                       \
	EVENT_ID(BE_CORE_RGBP_INT0_BASE, BE_CORE_RGBP_INT0_FRAME_START)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT0_FRAME_END                                         \
	EVENT_ID(BE_CORE_RGBP_INT0_BASE, BE_CORE_RGBP_INT0_FRAME_END)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT0_CMDQ_HOLD                                         \
	EVENT_ID(BE_CORE_RGBP_INT0_BASE, BE_CORE_RGBP_INT0_CMDQ_HOLD)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT0_SETTING_DONE                                      \
	EVENT_ID(BE_CORE_RGBP_INT0_BASE, BE_CORE_RGBP_INT0_SETTING_DONE)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT0_C_LOADER_END                                      \
	EVENT_ID(BE_CORE_RGBP_INT0_BASE, BE_CORE_RGBP_INT0_C_LOADER_END)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT0_COREX_END0                                        \
	EVENT_ID(BE_CORE_RGBP_INT0_BASE, BE_CORE_RGBP_INT0_COREX_END0)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT0_COREX_END1                                        \
	EVENT_ID(BE_CORE_RGBP_INT0_BASE, BE_CORE_RGBP_INT0_COREX_END1)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT0_ROW_COL                                           \
	EVENT_ID(BE_CORE_RGBP_INT0_BASE, BE_CORE_RGBP_INT0_ROW_COL)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT0_FREEZE_ON_ROW_COL                                 \
	EVENT_ID(BE_CORE_RGBP_INT0_BASE, BE_CORE_RGBP_INT0_FREEZE_ON_ROW_COL)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT0_TRANS_STOP_DONE                                   \
	EVENT_ID(BE_CORE_RGBP_INT0_BASE, BE_CORE_RGBP_INT0_TRANS_STOP_DONE)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT0_CMDQ_ERROR                                        \
	EVENT_ID(BE_CORE_RGBP_INT0_BASE, BE_CORE_RGBP_INT0_CMDQ_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT0_C_LOADER_ERROR                                    \
	EVENT_ID(BE_CORE_RGBP_INT0_BASE, BE_CORE_RGBP_INT0_C_LOADER_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT0_COREX_ERROR                                       \
	EVENT_ID(BE_CORE_RGBP_INT0_BASE, BE_CORE_RGBP_INT0_COREX_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT0_CINFIFO0_OVERFLOW_ERROR                           \
	EVENT_ID(BE_CORE_RGBP_INT0_BASE, BE_CORE_RGBP_INT0_CINFIFO0_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT0_CINFIFO0_OVERLAP_ERROR                            \
	EVENT_ID(BE_CORE_RGBP_INT0_BASE, BE_CORE_RGBP_INT0_CINFIFO0_OVERLAP_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT0_CINFIFO0_PIXEL_CNT_ERROR                          \
	EVENT_ID(BE_CORE_RGBP_INT0_BASE, BE_CORE_RGBP_INT0_CINFIFO0_PIXEL_CNT_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT0_CINFIFO0_INPUT_PROTOCOL_ERROR                     \
	EVENT_ID(BE_CORE_RGBP_INT0_BASE, BE_CORE_RGBP_INT0_CINFIFO0_INPUT_PROTOCOL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT0_COUTFIFO0_PIXEL_CNT_ERROR                         \
	EVENT_ID(BE_CORE_RGBP_INT0_BASE, BE_CORE_RGBP_INT0_COUTFIFO0_PIXEL_CNT_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT0_COUTFIFO0_INPUT_PROTOCOL_ERROR                    \
	EVENT_ID(BE_CORE_RGBP_INT0_BASE, BE_CORE_RGBP_INT0_COUTFIFO0_INPUT_PROTOCOL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT0_COUTFIFO0_OVERFLOW_ERROR                          \
	EVENT_ID(BE_CORE_RGBP_INT0_BASE, BE_CORE_RGBP_INT0_COUTFIFO0_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT0_VOTF_GLOBAL_ERROR                                 \
	EVENT_ID(BE_CORE_RGBP_INT0_BASE, BE_CORE_RGBP_INT0_VOTF_GLOBAL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT0_OTF_SEQ_ID_ERROR                                  \
	EVENT_ID(BE_CORE_RGBP_INT0_BASE, BE_CORE_RGBP_INT0_OTF_SEQ_ID_ERROR)

#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT1_VOTF_LOST_FLUSH                                   \
	EVENT_ID(BE_CORE_RGBP_INT1_BASE, BE_CORE_RGBP_INT1_VOTF_LOST_FLUSH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT1_VOTF0_WDMA_GLOBAL_ERROR                           \
	EVENT_ID(BE_CORE_RGBP_INT1_BASE, BE_CORE_RGBP_INT1_VOTF0_WDMA_GLOBAL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT1_VOTF0_WDMA_LOST_FLUSH                             \
	EVENT_ID(BE_CORE_RGBP_INT1_BASE, BE_CORE_RGBP_INT1_VOTF0_WDMA_LOST_FLUSH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT1_DTP_DBG_CNT_ERROR                                 \
	EVENT_ID(BE_CORE_RGBP_INT1_BASE, BE_CORE_RGBP_INT1_DTP_DBG_CNT_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT1_BDNS_DBG_CNT_ERROR                                \
	EVENT_ID(BE_CORE_RGBP_INT1_BASE, BE_CORE_RGBP_INT1_BDNS_DBG_CNT_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT1_DMSC_DBG_CNT_ERR                                  \
	EVENT_ID(BE_CORE_RGBP_INT1_BASE, BE_CORE_RGBP_INT1_DMSC_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT1_RGB_GAMMA_DBG_CNT_ERR                             \
	EVENT_ID(BE_CORE_RGBP_INT1_BASE, BE_CORE_RGBP_INT1_RGB_GAMMA_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT1_GTM_DBG_CNT_ERR                                   \
	EVENT_ID(BE_CORE_RGBP_INT1_BASE, BE_CORE_RGBP_INT1_GTM_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT1_RGB2YUV_DBG_CNT_ERR                               \
	EVENT_ID(BE_CORE_RGBP_INT1_BASE, BE_CORE_RGBP_INT1_RGB2YUV_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT1_YUV444TO422_DBG_CNT_ERR                           \
	EVENT_ID(BE_CORE_RGBP_INT1_BASE, BE_CORE_RGBP_INT1_YUV444TO422_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT1_SATFLAG_DBG_CNT_ERR                               \
	EVENT_ID(BE_CORE_RGBP_INT1_BASE, BE_CORE_RGBP_INT1_SATFLAG_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT1_DECOMP_DBG_CNT_ERR                                \
	EVENT_ID(BE_CORE_RGBP_INT1_BASE, BE_CORE_RGBP_INT1_DECOMP_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT1_CCM_DBG_CNT_ERR                                   \
	EVENT_ID(BE_CORE_RGBP_INT1_BASE, BE_CORE_RGBP_INT1_CCM_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT1_YUVSC_DBG_CNT_ERR                                 \
	EVENT_ID(BE_CORE_RGBP_INT1_BASE, BE_CORE_RGBP_INT1_YUVSC_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_INT1_SYNC_MERGE_COUTFIFO_DBG_CNT_ERR                   \
	EVENT_ID(BE_CORE_RGBP_INT1_BASE, BE_CORE_RGBP_INT1_SYNC_MERGE_COUTFIFO_DBG_CNT_ERR)

#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_CMDQ_INT_STOP_CRPT_OFF_CMDQ_EN                         \
	EVENT_ID(BE_CORE_RGBP_CMDQ_INT_BASE, BE_CORE_RGBP_CMDQ_INT_STOP_CRPT_OFF_CMDQ_EN)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_CMDQ_INT_PRELOAD_FLUSH                                 \
	EVENT_ID(BE_CORE_RGBP_CMDQ_INT_BASE, BE_CORE_RGBP_CMDQ_INT_PRELOAD_FLUSH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_CMDQ_INT_QUE0_OVERFLOW                                 \
	EVENT_ID(BE_CORE_RGBP_CMDQ_INT_BASE, BE_CORE_RGBP_CMDQ_INT_QUE0_OVERFLOW)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_CMDQ_INT_QUE1_OVERFLOW                                 \
	EVENT_ID(BE_CORE_RGBP_CMDQ_INT_BASE, BE_CORE_RGBP_CMDQ_INT_QUE1_OVERFLOW)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_CMDQ_INT_QUE_U_OVERFLOW                                \
	EVENT_ID(BE_CORE_RGBP_CMDQ_INT_BASE, BE_CORE_RGBP_CMDQ_INT_QUE_U_OVERFLOW)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_CMDQ_INT_QUE0_PUSH_BACK_TO_FULL_QUE                    \
	EVENT_ID(BE_CORE_RGBP_CMDQ_INT_BASE, BE_CORE_RGBP_CMDQ_INT_QUE0_PUSH_BACK_TO_FULL_QUE)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_CMDQ_INT_QUE1_PUSH_BACK_TO_FULL_QUE                    \
	EVENT_ID(BE_CORE_RGBP_CMDQ_INT_BASE, BE_CORE_RGBP_CMDQ_INT_QUE1_PUSH_BACK_TO_FULL_QUE)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_RGBP_CMDQ_INT_QUE_U_PUSH_BACK_TO_FULL_QUE                   \
	EVENT_ID(BE_CORE_RGBP_CMDQ_INT_BASE, BE_CORE_RGBP_CMDQ_INT_QUE_U_PUSH_BACK_TO_FULL_QUE)

#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_FRAME_START                                       \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_FRAME_START)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_FRAME_END                                         \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_FRAME_END)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_CMDQ_HOLD                                         \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_CMDQ_HOLD)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_SETTING_DONE                                      \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_SETTING_DONE)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_C_LOADER_END                                      \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_C_LOADER_END)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_COREX_END0                                        \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_COREX_END0)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_COREX_END1                                        \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_COREX_END1)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_ROW_COL                                           \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_ROW_COL)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_FREEZE_ON_ROW_COL                                 \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_FREEZE_ON_ROW_COL)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_TRANS_STOP_DONE                                   \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_TRANS_STOP_DONE)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_CMDQ_ERROR                                        \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_CMDQ_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_C_LOADER_ERROR                                    \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_C_LOADER_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_COREX_ERROR                                       \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_COREX_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_CINFIFO0_OVERFLOW_ERROR                           \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_CINFIFO0_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_CINFIFO0_OVERLAP_ERROR                            \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_CINFIFO0_OVERLAP_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_CINFIFO0_PIXEL_CNT_ERROR                          \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_CINFIFO0_PIXEL_CNT_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_CINFIFO0_INPUT_PROTOCOL_ERROR                     \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_CINFIFO0_INPUT_PROTOCOL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_CINFIFO1_OVERFLOW_ERROR                           \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_CINFIFO1_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_CINFIFO1_OVERLAP_ERROR                            \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_CINFIFO1_OVERLAP_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_CINFIFO1_PIXEL_CNT_ERROR                          \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_CINFIFO1_PIXEL_CNT_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_CINFIFO1_INPUT_PROTOCOL_ERROR                     \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_CINFIFO1_INPUT_PROTOCOL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_COUTFIFO0_PIXEL_CNT_ERROR                         \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_COUTFIFO0_PIXEL_CNT_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_COUTFIFO0_INPUT_PROTOCOL_ERROR                    \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_COUTFIFO0_INPUT_PROTOCOL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_COUTFIFO0_OVERFLOW_ERROR                          \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_COUTFIFO0_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_COUTFIFO1_PIXEL_CNT_ERROR                         \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_COUTFIFO1_PIXEL_CNT_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_COUTFIFO1_INPUT_PROTOCOL_ERROR                    \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_COUTFIFO1_INPUT_PROTOCOL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_COUTFIFO1_OVERFLOW_ERROR                          \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_COUTFIFO1_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_VOTF_GLOBAL_ERROR                                 \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_VOTF_GLOBAL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_VOTF_LOST_CONNECTION                              \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_VOTF_LOST_CONNECTION)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT0_OTF_SEQ_ID_ERROR                                  \
	EVENT_ID(BE_CORE_MCFP_INT0_BASE, BE_CORE_MCFP_INT0_OTF_SEQ_ID_ERROR)

#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_RDMA_M0_FINISH                                    \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_RDMA_M0_FINISH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_RDMA_M1_FINISH                                    \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_RDMA_M1_FINISH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_RDMA_M3_FINISH                                    \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_RDMA_M3_FINISH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_RDMA_M4_FINISH                                    \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_RDMA_M4_FINISH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_RDMA_M5_FINISH                                    \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_RDMA_M5_FINISH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_RDMA_M6_FINISH                                    \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_RDMA_M6_FINISH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_RDMA_M10_FINISH                                   \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_RDMA_M10_FINISH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_RDMA_M11_FINISH                                   \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_RDMA_M11_FINISH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_RDMA_M12_FINISH                                   \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_RDMA_M12_FINISH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_RDMA_M13_FINISH                                   \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_RDMA_M13_FINISH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_RDMA_M14_FINISH                                   \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_RDMA_M14_FINISH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_WDMA_M10_FINISH                                   \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_WDMA_M10_FINISH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_WDMA_M11_FINISH                                   \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_WDMA_M11_FINISH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_WDMA_M12_FINISH                                   \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_WDMA_M12_FINISH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_PREFETCH_LMC_FINISH                               \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_PREFETCH_LMC_FINISH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_LBCTRL_MIX_FINISH                                 \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_LBCTRL_MIX_FINISH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_HDR_FINISH                                        \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_HDR_FINISH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_MIXER_FINISH                                      \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_MIXER_FINISH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_LBCTRL_GF_FINISH                                  \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_LBCTRL_GF_FINISH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_CROP_CLEAN_OTF_FINISH                             \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_CROP_CLEAN_OTF_FINISH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_CROP_CLEAN_DMA_Y_FINISH                           \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_CROP_CLEAN_DMA_Y_FINISH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_CROP_CLEAN_DMA_C_FINISH                           \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_CROP_CLEAN_DMA_C_FINISH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_CROP_WEIGHT_DMA_FINISH                            \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_CROP_WEIGHT_DMA_FINISH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_GAMMA_FINISH                                      \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_GAMMA_FINISH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_SBWC_DEC_ERR_L                                    \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_SBWC_DEC_ERR_L)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_INT1_SBWC_DEC_ERR_C                                    \
	EVENT_ID(BE_CORE_MCFP_INT1_BASE, BE_CORE_MCFP_INT1_SBWC_DEC_ERR_C)

#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_CMDQ_INT_STOP_CRPT_OFF_CMDQ_EN                         \
	EVENT_ID(BE_CORE_MCFP_CMDQ_INT_BASE, BE_CORE_MCFP_CMDQ_INT_STOP_CRPT_OFF_CMDQ_EN)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_CMDQ_INT_PRELOAD_FLUSH                                 \
	EVENT_ID(BE_CORE_MCFP_CMDQ_INT_BASE, BE_CORE_MCFP_CMDQ_INT_PRELOAD_FLUSH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_MCFP_CMDQ_INT_QUE0_OVERFLOW                                 \
	EVENT_ID(BE_CORE_MCFP_CMDQ_INT_BASE, BE_CORE_MCFP_CMDQ_INT_QUE0_OVERFLOW)

#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_FRAME_START                                       \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_FRAME_START)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_FRAME_END                                         \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_FRAME_END)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_CMDQ_HOLD                                         \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_CMDQ_HOLD)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_SETTING_DONE                                      \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_SETTING_DONE)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_C_LOADER_END                                      \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_C_LOADER_END)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_COREX_END0                                        \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_COREX_END0)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_COREX_END1                                        \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_COREX_END1)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_ROW_COL                                           \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_ROW_COL)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_FREEZE_ON_ROW_COL                                 \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_FREEZE_ON_ROW_COL)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_TRANS_STOP_DONE                                   \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_TRANS_STOP_DONE)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_CMDQ_ERROR                                        \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_CMDQ_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_C_LOADER_ERROR                                    \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_C_LOADER_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_COREX_ERROR                                       \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_COREX_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_CINFIFO0_OVERFLOW_ERROR                           \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_CINFIFO0_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_CINFIFO0_OVERLAP_ERROR                            \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_CINFIFO0_OVERLAP_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_CINFIFO0_PIXEL_CNT_ERROR                          \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_CINFIFO0_PIXEL_CNT_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_CINFIFO0_INPUT_PROTOCOL_ERROR                     \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_CINFIFO0_INPUT_PROTOCOL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_COUTFIFO0_PIXEL_CNT_ERROR                         \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_COUTFIFO0_PIXEL_CNT_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_COUTFIFO0_INPUT_PROTOCOL_ERROR                    \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_COUTFIFO0_INPUT_PROTOCOL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_COUTFIFO0_OVERFLOW_ERROR                          \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_COUTFIFO0_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_COUTFIFO1_PIXEL_CNT_ERROR                         \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_COUTFIFO1_PIXEL_CNT_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_COUTFIFO1_INPUT_PROTOCOL_ERROR                    \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_COUTFIFO1_INPUT_PROTOCOL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_COUTFIFO1_OVERFLOW_ERROR                          \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_COUTFIFO1_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_VOTF_GLOBAL_ERROR                                 \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_VOTF_GLOBAL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_VOTF_LOST_CONNECTION                              \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_VOTF_LOST_CONNECTION)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT0_OTF_SEQ_ID_ERROR                                  \
	EVENT_ID(BE_CORE_YUVP_INT0_BASE, BE_CORE_YUVP_INT0_OTF_SEQ_ID_ERROR)

#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT1_VOTF_LOST_FLUSH                                   \
	EVENT_ID(BE_CORE_YUVP_INT1_BASE, BE_CORE_YUVP_INT1_VOTF_LOST_FLUSH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT1_COUTF02_MCSC_OVERLAP_ERR                          \
	EVENT_ID(BE_CORE_YUVP_INT1_BASE, BE_CORE_YUVP_INT1_COUTF02_MCSC_OVERLAP_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT1_COUTF02_MCSC_PIXEL_CNT_ERR                        \
	EVENT_ID(BE_CORE_YUVP_INT1_BASE, BE_CORE_YUVP_INT1_COUTF02_MCSC_PIXEL_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT1_COUTF02_MCSC_INPUT_PROTOCOL_ERR                   \
	EVENT_ID(BE_CORE_YUVP_INT1_BASE, BE_CORE_YUVP_INT1_COUTF02_MCSC_INPUT_PROTOCOL_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT1_DTP_DBG_CNT_ERR                                   \
	EVENT_ID(BE_CORE_YUVP_INT1_BASE, BE_CORE_YUVP_INT1_DTP_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT1_YUVNR_DBG_CNT_ERR                                 \
	EVENT_ID(BE_CORE_YUVP_INT1_BASE, BE_CORE_YUVP_INT1_YUVNR_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT1_YUV422TO444_DBG_CNT_ERR                           \
	EVENT_ID(BE_CORE_YUVP_INT1_BASE, BE_CORE_YUVP_INT1_YUV422TO444_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT1_YUV2RGB_DBG_CNT_ERR                               \
	EVENT_ID(BE_CORE_YUVP_INT1_BASE, BE_CORE_YUVP_INT1_YUV2RGB_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT1_RGB2YUV_DBG_CNT_ERR                               \
	EVENT_ID(BE_CORE_YUVP_INT1_BASE, BE_CORE_YUVP_INT1_RGB2YUV_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT1_DITHER_DBG_CNT_ERR                                \
	EVENT_ID(BE_CORE_YUVP_INT1_BASE, BE_CORE_YUVP_INT1_DITHER_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT1_INVCCM_DBG_CNT_ERR                                \
	EVENT_ID(BE_CORE_YUVP_INT1_BASE, BE_CORE_YUVP_INT1_INVCCM_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT1_DEGAMMA_DBG_CNT_ERR                               \
	EVENT_ID(BE_CORE_YUVP_INT1_BASE, BE_CORE_YUVP_INT1_DEGAMMA_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT1_RGB_GAMMA_DBG_CNT_ERR                             \
	EVENT_ID(BE_CORE_YUVP_INT1_BASE, BE_CORE_YUVP_INT1_RGB_GAMMA_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT1_OETF_GAMMA_DBG_CNT_ERR                            \
	EVENT_ID(BE_CORE_YUVP_INT1_BASE, BE_CORE_YUVP_INT1_OETF_GAMMA_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT1_PRC_DBG_CNT_ERR                                   \
	EVENT_ID(BE_CORE_YUVP_INT1_BASE, BE_CORE_YUVP_INT1_PRC_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT1_SHARPEN_DBG_CNT_ERR                               \
	EVENT_ID(BE_CORE_YUVP_INT1_BASE, BE_CORE_YUVP_INT1_SHARPEN_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT1_LTM_DBG_CNT_ERR                                   \
	EVENT_ID(BE_CORE_YUVP_INT1_BASE, BE_CORE_YUVP_INT1_LTM_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT1_YUV2RGB_ZUMA_DBG_CNT_ERR                          \
	EVENT_ID(BE_CORE_YUVP_INT1_BASE, BE_CORE_YUVP_INT1_YUV2RGB_ZUMA_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT1_DEGAMMA_RGB_MAIN_DBG_CNT_ERR                      \
	EVENT_ID(BE_CORE_YUVP_INT1_BASE, BE_CORE_YUVP_INT1_DEGAMMA_RGB_MAIN_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT1_DEGAMMA_RGB_LINER_DBG_CNT_ERR                     \
	EVENT_ID(BE_CORE_YUVP_INT1_BASE, BE_CORE_YUVP_INT1_DEGAMMA_RGB_LINER_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT1_RGB2YUV420_DBG_CNT_ERR                            \
	EVENT_ID(BE_CORE_YUVP_INT1_BASE, BE_CORE_YUVP_INT1_RGB2YUV420_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT1_RGB2YUV422_DBG_CNT_ERR                            \
	EVENT_ID(BE_CORE_YUVP_INT1_BASE, BE_CORE_YUVP_INT1_RGB2YUV422_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT1_YUV420TO422_DBG_CNT_ERR                           \
	EVENT_ID(BE_CORE_YUVP_INT1_BASE, BE_CORE_YUVP_INT1_YUV420TO422_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT1_CCM_DBG_CNT_ERR                                   \
	EVENT_ID(BE_CORE_YUVP_INT1_BASE, BE_CORE_YUVP_INT1_CCM_DBG_CNT_ERR)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_INT1_CLUT_DBG_CNT_ERR                                  \
	EVENT_ID(BE_CORE_YUVP_INT1_BASE, BE_CORE_YUVP_INT1_CLUT_DBG_CNT_ERR)

#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_CMDQ_INT_STOP_CRPT_OFF_CMDQ_EN                         \
	EVENT_ID(BE_CORE_YUVP_CMDQ_INT_BASE, BE_CORE_YUVP_CMDQ_INT_STOP_CRPT_OFF_CMDQ_EN)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_CMDQ_INT_PRELOAD_FLUSH                                 \
	EVENT_ID(BE_CORE_YUVP_CMDQ_INT_BASE, BE_CORE_YUVP_CMDQ_INT_PRELOAD_FLUSH)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_CMDQ_INT_QUE0_OVERFLOW                                 \
	EVENT_ID(BE_CORE_YUVP_CMDQ_INT_BASE, BE_CORE_YUVP_CMDQ_INT_QUE0_OVERFLOW)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_CMDQ_INT_QUE1_OVERFLOW                                 \
	EVENT_ID(BE_CORE_YUVP_CMDQ_INT_BASE, BE_CORE_YUVP_CMDQ_INT_QUE1_OVERFLOW)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_CMDQ_INT_QUE_U_OVERFLOW                                \
	EVENT_ID(BE_CORE_YUVP_CMDQ_INT_BASE, BE_CORE_YUVP_CMDQ_INT_QUE_U_OVERFLOW)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_CMDQ_INT_QUE0_PUSH_BACK_TO_FULL_QUE                    \
	EVENT_ID(BE_CORE_YUVP_CMDQ_INT_BASE, BE_CORE_YUVP_CMDQ_INT_QUE0_PUSH_BACK_TO_FULL_QUE)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_CMDQ_INT_QUE1_PUSH_BACK_TO_FULL_QUE                    \
	EVENT_ID(BE_CORE_YUVP_CMDQ_INT_BASE, BE_CORE_YUVP_CMDQ_INT_QUE1_PUSH_BACK_TO_FULL_QUE)
#define LWIS_PLATFORM_EVENT_ID_BE_CORE_YUVP_CMDQ_INT_QUE_U_PUSH_BACK_TO_FULL_QUE                   \
	EVENT_ID(BE_CORE_YUVP_CMDQ_INT_BASE, BE_CORE_YUVP_CMDQ_INT_QUE_U_PUSH_BACK_TO_FULL_QUE)

#endif /* DT_BINDINGS_LWIS_PLATFORM_ZUMA_BE_CORE_H_ */
