/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Google LWIS ZUMA GSE Interrupt And Event Defines
 *
 * Copyright (c) 2022 Google, LLC
 */

#ifndef DT_BINDINGS_LWIS_PLATFORM_ZUMA_GSE_H_
#define DT_BINDINGS_LWIS_PLATFORM_ZUMA_GSE_H_

#include <dt-bindings/lwis/platform/common.h>

/* clang-format off */

#define GSE_IRQ_BASE (HW_EVENT_MASK + 0)

#define GSE_IRQ_CORE_FINISH 0
#define GSE_IRQ_SCALER0_FINISH 1
#define GSE_IRQ_SCALER1_FINISH 2
#define GSE_IRQ_RAISR_FINISH 3
#define GSE_IRQ_WDMA0_FINISH 4
#define GSE_IRQ_WDMA1_FINISH 5
#define GSE_IRQ_ALL_FRAME_START 6
#define GSE_IRQ_ALL_FRAME_DONE 7
#define GSE_IRQ_PER_FRAME_START 8
#define GSE_IRQ_PER_FRAME_DONE 9
#define GSE_IRQ_CSR_COPY_DONE 10
#define GSE_IRQ_RDMA_ERR 11
#define GSE_IRQ_WDMA0_ERR 12
#define GSE_IRQ_WDMA1_ERR 13
#define GSE_IRQ_RESERVE_AFBC_ENC0 14
#define GSE_IRQ_RESERVE_AFBC_ENC1 15
#define GSE_IRQ_AFBC_DEC 16
#define GSE_IRQ_SBWC_DEC_LUMA 17
#define GSE_IRQ_SBWC_DEC_CHROMA 18
#define GSE_IRQ_VOTF_LOST_CONNECTION 19
#define GSE_IRQ_VOTF_SLOW_RING 20
#define GSE_IRQ_VOTF_LOST_FLUSH 21
#define GSE_IRQ_OUT_STALL_TIMEOUT 22
#define GSE_IRQ_INPUT_FRAME_CRUSH 23
#define GSE_IRQ_INPUT_HOR_OVF 24
#define GSE_IRQ_INPUT_HOR_UNF 25
#define GSE_IRQ_INPUT_VER_OVF 26
#define GSE_IRQ_INPUT_VER_UNF 27
#define GSE_IRQ_ACTIVE_APB_WR_IN_MASK_CYCLE 28

#define GSE_SEC_IRQ_BASE (HW_EVENT_MASK + 32)

#define GSE_SEC_IRQ_PDMA_ERR 0
#define GSE_SEC_IRQ_RDMA_ERR 1
#define GSE_SEC_IRQ_WDMA0_ERR 2
#define GSE_SEC_IRQ_WDMA1_ERR 3
#define GSE_SEC_IRQ_FABRIC_DEC_ERR 4
#define GSE_SEC_IRQ_FABRIC_SLV0_ERR 5
#define GSE_SEC_IRQ_FABRIC_SLV1_ERR 6
#define GSE_SEC_IRQ_FABRIC_SLV2_ERR 7
#define GSE_SEC_IRQ_FABRIC_SLV3_ERR 8
#define GSE_SEC_IRQ_FABRIC_SLV4_ERR 9
#define GSE_SEC_IRQ_FABRIC_SLV5_ERR 10
#define GSE_SEC_IRQ_FABRIC_SLV6_ERR 11
#define GSE_SEC_IRQ_FABRIC_SLV7_ERR 12

#define GSE_PDMA_BASE (HW_EVENT_MASK + 64)

#define GSE_PDMA_IRQ_CMD 0
#define GSE_PDMA_ALMOST_EMPTY 1

#define GSE_PDMA_ERR_BASE (HW_EVENT_MASK + 96)

#define GSE_PDMA_ERR_MEM_BUS_ERR 0
#define GSE_PDMA_ERR_CSR_BUS_ERR 1
#define GSE_PDMA_ERR_ILLEGAL_CMD 2
#define GSE_PDMA_ERR_RECUR_INDIR_CMD 3
#define GSE_PDMA_ERR_CMD_SIZE_MISMATCH 4

#define GSE_PDMA_RSTCTL_BASE (HW_EVENT_MASK + 128)

#define GSE_PDMA_RSTCTL_SW_RESET_DONE 0
#define GSE_PDMA_RSTCTL_INPUT_FLUSH_DONE 1
#define GSE_PDMA_RSTCTL_SW_MODE 2
#define GSE_PDMA_RSTCTL_APB_GKP_ERR 3
#define GSE_PDMA_RSTCTL_AXI_GKP_ERR 4

#define GSE_ISP_RSTCTL_BASE (HW_EVENT_MASK + 160)

#define GSE_ISP_RSTCTL_SW_RESET_DONE 0
#define GSE_ISP_RSTCTL_INPUT_FLUSH_DONE 1
#define GSE_ISP_RSTCTL_SW_MODE 2
#define GSE_ISP_RSTCTL_APB_GKP_ERR 3
#define GSE_ISP_RSTCTL_AXI_GKP_ERR 4

#define GSE_CSR_BUS_WRAP_BASE (HW_EVENT_MASK + 192)

#define GSE_CSR_BUS_WRAP_SLV0_ERR 0
#define GSE_CSR_BUS_WRAP_SLV1_ERR 1
#define GSE_CSR_BUS_WRAP_SLV2_ERR 2
#define GSE_CSR_BUS_WRAP_SLV3_ERR 3
#define GSE_CSR_BUS_WRAP_SLV4_ERR 4
#define GSE_CSR_BUS_WRAP_SLV5_ERR 5
#define GSE_CSR_BUS_WRAP_SLV6_ERR 6
#define GSE_CSR_BUS_WRAP_SLV7_ERR 7
#define GSE_CSR_BUS_WRAP_DEC_ERR 8

/* clang-format on */

#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_CORE_FINISH \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_CORE_FINISH)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_SCALER0_FINISH \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_SCALER0_FINISH)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_SCALER1_FINISH \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_SCALER1_FINISH)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_RAISR_FINISH \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_RAISR_FINISH)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_WDMA0_FINISH \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_WDMA0_FINISH)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_WDMA1_FINISH \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_WDMA1_FINISH)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_ALL_FRAME_START \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_ALL_FRAME_START)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_ALL_FRAME_DONE \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_ALL_FRAME_DONE)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_PER_FRAME_START \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_PER_FRAME_START)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_PER_FRAME_DONE \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_PER_FRAME_DONE)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_CSR_COPY_DONE \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_CSR_COPY_DONE)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_RDMA_ERR \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_RDMA_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_WDMA0_ERR \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_WDMA0_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_WDMA1_ERR \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_WDMA1_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_RESERVE_AFBC_ENC0 \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_RESERVE_AFBC_ENC0)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_RESERVE_AFBC_ENC1 \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_RESERVE_AFBC_ENC1)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_AFBC_DEC \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_AFBC_DEC)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_SBWC_DEC_LUMA \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_SBWC_DEC_LUMA)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_SBWC_DEC_CHROMA \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_SBWC_DEC_CHROMA)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_VOTF_LOST_CONNECTION \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_VOTF_LOST_CONNECTION)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_VOTF_SLOW_RING \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_VOTF_SLOW_RING)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_VOTF_LOST_FLUSH \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_VOTF_LOST_FLUSH)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_OUT_STALL_TIMEOUT \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_OUT_STALL_TIMEOUT)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_INPUT_FRAME_CRUSH \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_INPUT_FRAME_CRUSH)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_INPUT_HOR_OVF \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_INPUT_HOR_OVF)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_INPUT_HOR_UNF \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_INPUT_HOR_UNF)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_INPUT_VER_OVF \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_INPUT_VER_OVF)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_INPUT_VER_UNF \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_INPUT_VER_UNF)
#define LWIS_PLATFORM_EVENT_ID_GSE_IRQ_ACTIVE_APB_WR_IN_MASK_CYCLE \
	EVENT_ID(GSE_IRQ_BASE, \
		 GSE_IRQ_ACTIVE_APB_WR_IN_MASK_CYCLE)

#define LWIS_PLATFORM_EVENT_ID_GSE_SEC_IRQ_PDMA_ERR \
	EVENT_ID(GSE_SEC_IRQ_BASE, \
		 GSE_SEC_IRQ_PDMA_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_SEC_IRQ_RDMA_ERR \
	EVENT_ID(GSE_SEC_IRQ_BASE, \
		 GSE_SEC_IRQ_RDMA_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_SEC_IRQ_WDMA0_ERR \
	EVENT_ID(GSE_SEC_IRQ_BASE, \
		 GSE_SEC_IRQ_WDMA0_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_SEC_IRQ_WDMA1_ERR \
	EVENT_ID(GSE_SEC_IRQ_BASE, \
		 GSE_SEC_IRQ_WDMA1_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_SEC_IRQ_FABRIC_DEC_ERR \
	EVENT_ID(GSE_SEC_IRQ_BASE, \
		 GSE_SEC_IRQ_FABRIC_DEC_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_SEC_IRQ_FABRIC_SLV0_ERR \
	EVENT_ID(GSE_SEC_IRQ_BASE, \
		 GSE_SEC_IRQ_FABRIC_SLV0_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_SEC_IRQ_FABRIC_SLV1_ERR \
	EVENT_ID(GSE_SEC_IRQ_BASE, \
		 GSE_SEC_IRQ_FABRIC_SLV1_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_SEC_IRQ_FABRIC_SLV2_ERR \
	EVENT_ID(GSE_SEC_IRQ_BASE, \
		 GSE_SEC_IRQ_FABRIC_SLV2_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_SEC_IRQ_FABRIC_SLV3_ERR \
	EVENT_ID(GSE_SEC_IRQ_BASE, \
		 GSE_SEC_IRQ_FABRIC_SLV3_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_SEC_IRQ_FABRIC_SLV4_ERR \
	EVENT_ID(GSE_SEC_IRQ_BASE, \
		 GSE_SEC_IRQ_FABRIC_SLV4_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_SEC_IRQ_FABRIC_SLV5_ERR \
	EVENT_ID(GSE_SEC_IRQ_BASE, \
		 GSE_SEC_IRQ_FABRIC_SLV5_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_SEC_IRQ_FABRIC_SLV6_ERR \
	EVENT_ID(GSE_SEC_IRQ_BASE, \
		 GSE_SEC_IRQ_FABRIC_SLV6_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_SEC_IRQ_FABRIC_SLV7_ERR \
	EVENT_ID(GSE_SEC_IRQ_BASE, \
		 GSE_SEC_IRQ_FABRIC_SLV7_ERR)

#define LWIS_PLATFORM_EVENT_ID_GSE_PDMA_IRQ_CMD \
	EVENT_ID(GSE_PDMA_BASE, \
		 GSE_PDMA_IRQ_CMD)
#define LWIS_PLATFORM_EVENT_ID_GSE_PDMA_ALMOST_EMPTY \
	EVENT_ID(GSE_PDMA_BASE, \
		 GSE_PDMA_ALMOST_EMPTY)

#define LWIS_PLATFORM_EVENT_ID_GSE_PDMA_ERR_MEM_BUS_ERR \
	EVENT_ID(GSE_PDMA_ERR_BASE, \
		 GSE_PDMA_ERR_MEM_BUS_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_PDMA_ERR_CSR_BUS_ERR \
	EVENT_ID(GSE_PDMA_ERR_BASE, \
		 GSE_PDMA_ERR_CSR_BUS_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_PDMA_ERR_ILLEGAL_CMD \
	EVENT_ID(GSE_PDMA_ERR_BASE, \
		 GSE_PDMA_ERR_ILLEGAL_CMD)
#define LWIS_PLATFORM_EVENT_ID_GSE_PDMA_ERR_RECUR_INDIR_CMD \
	EVENT_ID(GSE_PDMA_ERR_BASE, \
		 GSE_PDMA_ERR_RECUR_INDIR_CMD)
#define LWIS_PLATFORM_EVENT_ID_GSE_PDMA_ERR_CMD_SIZE_MISMATCH \
	EVENT_ID(GSE_PDMA_ERR_BASE, \
		 GSE_PDMA_ERR_CMD_SIZE_MISMATCH)

#define LWIS_PLATFORM_EVENT_ID_GSE_PDMA_RSTCTL_SW_RESET_DONE \
	EVENT_ID(GSE_PDMA_RSTCTL_BASE, \
		 GSE_PDMA_RSTCTL_SW_RESET_DONE)
#define LWIS_PLATFORM_EVENT_ID_GSE_PDMA_RSTCTL_INPUT_FLUSH_DONE \
	EVENT_ID(GSE_PDMA_RSTCTL_BASE, \
		 GSE_PDMA_RSTCTL_INPUT_FLUSH_DONE)
#define LWIS_PLATFORM_EVENT_ID_GSE_PDMA_RSTCTL_SW_MODE \
	EVENT_ID(GSE_PDMA_RSTCTL_BASE, \
		 GSE_PDMA_RSTCTL_SW_MODE)
#define LWIS_PLATFORM_EVENT_ID_GSE_PDMA_RSTCTL_APB_GKP_ERR \
	EVENT_ID(GSE_PDMA_RSTCTL_BASE, \
		 GSE_PDMA_RSTCTL_APB_GKP_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_PDMA_RSTCTL_AXI_GKP_ERR \
	EVENT_ID(GSE_PDMA_RSTCTL_BASE, \
		 GSE_PDMA_RSTCTL_AXI_GKP_ERR)

#define LWIS_PLATFORM_EVENT_ID_GSE_ISP_RSTCTL_SW_RESET_DONE \
	EVENT_ID(GSE_ISP_RSTCTL_BASE, \
		 GSE_ISP_RSTCTL_SW_RESET_DONE)
#define LWIS_PLATFORM_EVENT_ID_GSE_ISP_RSTCTL_INPUT_FLUSH_DONE \
	EVENT_ID(GSE_ISP_RSTCTL_BASE, \
		 GSE_ISP_RSTCTL_INPUT_FLUSH_DONE)
#define LWIS_PLATFORM_EVENT_ID_GSE_ISP_RSTCTL_SW_MODE \
	EVENT_ID(GSE_ISP_RSTCTL_BASE, \
		 GSE_ISP_RSTCTL_SW_MODE)
#define LWIS_PLATFORM_EVENT_ID_GSE_ISP_RSTCTL_APB_GKP_ERR \
	EVENT_ID(GSE_ISP_RSTCTL_BASE, \
		 GSE_ISP_RSTCTL_APB_GKP_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_ISP_RSTCTL_AXI_GKP_ERR \
	EVENT_ID(GSE_ISP_RSTCTL_BASE, \
		 GSE_ISP_RSTCTL_AXI_GKP_ERR)

#define LWIS_PLATFORM_EVENT_ID_GSE_CSR_BUS_WRAP_SLV0_ERR \
	EVENT_ID(GSE_CSR_BUS_WRAP_BASE, \
		 GSE_CSR_BUS_WRAP_SLV0_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_CSR_BUS_WRAP_SLV1_ERR \
	EVENT_ID(GSE_CSR_BUS_WRAP_BASE, \
		 GSE_CSR_BUS_WRAP_SLV1_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_CSR_BUS_WRAP_SLV2_ERR \
	EVENT_ID(GSE_CSR_BUS_WRAP_BASE, \
		 GSE_CSR_BUS_WRAP_SLV2_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_CSR_BUS_WRAP_SLV3_ERR \
	EVENT_ID(GSE_CSR_BUS_WRAP_BASE, \
		 GSE_CSR_BUS_WRAP_SLV3_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_CSR_BUS_WRAP_SLV4_ERR \
	EVENT_ID(GSE_CSR_BUS_WRAP_BASE, \
		 GSE_CSR_BUS_WRAP_SLV4_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_CSR_BUS_WRAP_SLV5_ERR \
	EVENT_ID(GSE_CSR_BUS_WRAP_BASE, \
		 GSE_CSR_BUS_WRAP_SLV5_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_CSR_BUS_WRAP_SLV6_ERR \
	EVENT_ID(GSE_CSR_BUS_WRAP_BASE, \
		 GSE_CSR_BUS_WRAP_SLV6_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_CSR_BUS_WRAP_SLV7_ERR \
	EVENT_ID(GSE_CSR_BUS_WRAP_BASE, \
		 GSE_CSR_BUS_WRAP_SLV7_ERR)
#define LWIS_PLATFORM_EVENT_ID_GSE_CSR_BUS_WRAP_DEC_ERR \
	EVENT_ID(GSE_CSR_BUS_WRAP_BASE, \
		 GSE_CSR_BUS_WRAP_DEC_ERR)

#endif /* DT_BINDINGS_LWIS_PLATFORM_ZUMA_GSE_H_ */
