/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Google LWIS ZUMA GTNR_MERGE Interrupt And Event Defines
 *
 * Copyright (c) 2022 Google, LLC
 */

#ifndef DT_BINDINGS_LWIS_PLATFORM_ZUMA_GTNR_MERGE_H_
#define DT_BINDINGS_LWIS_PLATFORM_ZUMA_GTNR_MERGE_H_

#include <dt-bindings/lwis/platform/common.h>

/* clang-format off */


#define GTNR_MERGE_INT0_BASE (HW_EVENT_MASK + 0)

#define GTNR_MERGE_INT0_FRAME_START 0
#define GTNR_MERGE_INT0_FRAME_END 1
#define GTNR_MERGE_INT0_CMDQ_HOLD 2
#define GTNR_MERGE_INT0_SETTING_DONE 3
#define GTNR_MERGE_INT0_C_LOADER_END_INT 4
#define GTNR_MERGE_INT0_COREX_END0 5
#define GTNR_MERGE_INT0_COREX_END1 6
#define GTNR_MERGE_INT0_ROW_COL 7
#define GTNR_MERGE_INT0_FREEZE_ON_ROW_COL 8
#define GTNR_MERGE_INT0_TRANS_STOP_DONE 9
#define GTNR_MERGE_INT0_CMDQ_ERROR 10
#define GTNR_MERGE_INT0_C_LOADER_ERROR 11
#define GTNR_MERGE_INT0_COREX_ERROR 12
#define GTNR_MERGE_INT0_CINFIFO0_OVERFLOW_ERROR 13
#define GTNR_MERGE_INT0_CINFIFO0_OVERLAP_ERROR 14
#define GTNR_MERGE_INT0_CINFIFO0_PIXEL_CNT_ERROR 15
#define GTNR_MERGE_INT0_CINFIFO0_INPUT_PROTOCOL_ERROR 16
#define GTNR_MERGE_INT0_CINFIFO1_OVERFLOW_ERROR 17
#define GTNR_MERGE_INT0_CINFIFO1_OVERLAP_ERROR 18
#define GTNR_MERGE_INT0_CINFIFO1_PIXEL_CNT_ERROR 19
#define GTNR_MERGE_INT0_CINFIFO1_INPUT_PROTOCOL_ERROR 20
#define GTNR_MERGE_INT0_COUTFIFO0_PIXEL_CNT_ERROR 21
#define GTNR_MERGE_INT0_COUTFIFO0_INPUT_PROTOCOL_ERROR 22
#define GTNR_MERGE_INT0_COUTFIFO0_OVERFLOW_ERROR 23
#define GTNR_MERGE_INT0_COUTFIFO1_PIXEL_CNT_ERROR 24
#define GTNR_MERGE_INT0_COUTFIFO1_INPUT_PROTOCOL_ERROR 25
#define GTNR_MERGE_INT0_COUTFIFO1_OVERFLOW_ERROR 26
#define GTNR_MERGE_INT0_VOTF_GLOBAL_ERROR 27
#define GTNR_MERGE_INT0_VOTF_LOST_CONNECTION 28
#define GTNR_MERGE_INT0_OTF_SEQ_ID_ERROR 29



#define GTNR_MERGE_INT1_BASE (HW_EVENT_MASK + 32)

#define GTNR_MERGE_INT1_VOTF_LOST_FLUSH 0
#define GTNR_MERGE_INT1_SBWC_ERR_CUR0 1
#define GTNR_MERGE_INT1_SBWC_ERR_CUR1 2
#define GTNR_MERGE_INT1_SBWC_ERR_PRE0 3
#define GTNR_MERGE_INT1_SBWC_ERR_PRE1 4



#define GTNR_MERGE_CMDQ_INT_BASE (HW_EVENT_MASK + 64)

#define GTNR_MERGE_CMDQ_INT_STOP_CRPT_OFF_CMDQ_EN 0
#define GTNR_MERGE_CMDQ_INT_PRELOAD_FLUSH 1
#define GTNR_MERGE_CMDQ_INT_QUE0_OVERFLOW 2

/* clang-format on */

#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_FRAME_START                                         \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_FRAME_START)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_FRAME_END                                           \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_FRAME_END)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_CMDQ_HOLD                                           \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_CMDQ_HOLD)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_SETTING_DONE                                        \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_SETTING_DONE)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_C_LOADER_END_INT                                    \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_C_LOADER_END_INT)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_COREX_END0                                          \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_COREX_END0)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_COREX_END1                                          \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_COREX_END1)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_ROW_COL                                             \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_ROW_COL)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_FREEZE_ON_ROW_COL                                   \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_FREEZE_ON_ROW_COL)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_TRANS_STOP_DONE                                     \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_TRANS_STOP_DONE)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_CMDQ_ERROR                                          \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_CMDQ_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_C_LOADER_ERROR                                      \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_C_LOADER_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_COREX_ERROR                                         \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_COREX_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_CINFIFO0_OVERFLOW_ERROR                             \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_CINFIFO0_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_CINFIFO0_OVERLAP_ERROR                              \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_CINFIFO0_OVERLAP_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_CINFIFO0_PIXEL_CNT_ERROR                            \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_CINFIFO0_PIXEL_CNT_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_CINFIFO0_INPUT_PROTOCOL_ERROR                       \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_CINFIFO0_INPUT_PROTOCOL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_CINFIFO1_OVERFLOW_ERROR                             \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_CINFIFO1_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_CINFIFO1_OVERLAP_ERROR                              \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_CINFIFO1_OVERLAP_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_CINFIFO1_PIXEL_CNT_ERROR                            \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_CINFIFO1_PIXEL_CNT_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_CINFIFO1_INPUT_PROTOCOL_ERROR                       \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_CINFIFO1_INPUT_PROTOCOL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_COUTFIFO0_PIXEL_CNT_ERROR                           \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_COUTFIFO0_PIXEL_CNT_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_COUTFIFO0_INPUT_PROTOCOL_ERROR                      \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_COUTFIFO0_INPUT_PROTOCOL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_COUTFIFO0_OVERFLOW_ERROR                            \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_COUTFIFO0_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_COUTFIFO1_PIXEL_CNT_ERROR                           \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_COUTFIFO1_PIXEL_CNT_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_COUTFIFO1_INPUT_PROTOCOL_ERROR                      \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_COUTFIFO1_INPUT_PROTOCOL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_COUTFIFO1_OVERFLOW_ERROR                            \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_COUTFIFO1_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_VOTF_GLOBAL_ERROR                                   \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_VOTF_GLOBAL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_VOTF_LOST_CONNECTION                                \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_VOTF_LOST_CONNECTION)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT0_OTF_SEQ_ID_ERROR                                    \
	EVENT_ID(GTNR_MERGE_INT0_BASE, GTNR_MERGE_INT0_OTF_SEQ_ID_ERROR)

#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT1_VOTF_LOST_FLUSH                                     \
	EVENT_ID(GTNR_MERGE_INT1_BASE, GTNR_MERGE_INT1_VOTF_LOST_FLUSH)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT1_SBWC_ERR_CUR0                                       \
	EVENT_ID(GTNR_MERGE_INT1_BASE, GTNR_MERGE_INT1_SBWC_ERR_CUR0)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT1_SBWC_ERR_CUR1                                       \
	EVENT_ID(GTNR_MERGE_INT1_BASE, GTNR_MERGE_INT1_SBWC_ERR_CUR1)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT1_SBWC_ERR_PRE0                                       \
	EVENT_ID(GTNR_MERGE_INT1_BASE, GTNR_MERGE_INT1_SBWC_ERR_PRE0)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_INT1_SBWC_ERR_PRE1                                       \
	EVENT_ID(GTNR_MERGE_INT1_BASE, GTNR_MERGE_INT1_SBWC_ERR_PRE1)

#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_CMDQ_INT_STOP_CRPT_OFF_CMDQ_EN                           \
	EVENT_ID(GTNR_MERGE_CMDQ_INT_BASE, GTNR_MERGE_CMDQ_INT_STOP_CRPT_OFF_CMDQ_EN)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_CMDQ_INT_PRELOAD_FLUSH                                   \
	EVENT_ID(GTNR_MERGE_CMDQ_INT_BASE, GTNR_MERGE_CMDQ_INT_PRELOAD_FLUSH)
#define LWIS_PLATFORM_EVENT_ID_GTNR_MERGE_CMDQ_INT_QUE0_OVERFLOW                                   \
	EVENT_ID(GTNR_MERGE_CMDQ_INT_BASE, GTNR_MERGE_CMDQ_INT_QUE0_OVERFLOW)

#endif /* DT_BINDINGS_LWIS_PLATFORM_ZUMA_GTNR_MERGE_H_ */
