/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Google LWIS ZUMA MCSC Interrupt And Event Defines
 *
 * Copyright (c) 2022 Google, LLC
 */

#ifndef DT_BINDINGS_LWIS_PLATFORM_ZUMA_MCSC_H_
#define DT_BINDINGS_LWIS_PLATFORM_ZUMA_MCSC_H_

#include <dt-bindings/lwis/platform/common.h>

/* clang-format off */

#define MCSC_INT0_BASE (HW_EVENT_MASK + 0)

#define MCSC_INT0_FRAME_START 0
#define MCSC_INT0_FRAME_END 1
#define MCSC_INT0_CMDQ_HOLD 2
#define MCSC_INT0_SETTING_DONE 3
#define MCSC_INT0_C_LOADER_END 4
#define MCSC_INT0_COREX_END0 5
#define MCSC_INT0_COREX_END1 6
#define MCSC_INT0_ROW_COL 7
#define MCSC_INT0_FREEZE_ON_ROW_COL 8
#define MCSC_INT0_TRANS_STOP_DONE 9
#define MCSC_INT0_CMDQ_ERROR 10
#define MCSC_INT0_C_LOADER_ERROR 11
#define MCSC_INT0_COREX_ERROR 12
#define MCSC_INT0_CINFIFO0_OVERFLOW_ERROR 13
#define MCSC_INT0_CINFIFO0_OVERLAP_ERROR 14
#define MCSC_INT0_CINFIFO0_PIXEL_CNT_ERROR 15
#define MCSC_INT0_CINFIFO0_INPUT_PROTOCOL_ERROR 16
#define MCSC_INT0_CINFIFO1_OVERFLOW_ERROR 17
#define MCSC_INT0_CINFIFO1_OVERLAP_ERROR 18
#define MCSC_INT0_CINFIFO1_PIXEL_CNT_ERROR 19
#define MCSC_INT0_CINFIFO1_INPUT_PROTOCOL_ERROR 20
#define MCSC_INT0_COUTFIFO0_PIXEL_CNT_ERROR 21
#define MCSC_INT0_COUTFIFO0_INPUT_PROTOCOL_ERROR 22
#define MCSC_INT0_COUTFIFO0_OVERFLOW_ERROR 23
#define MCSC_INT0_COUTFIFO1_PIXEL_CNT_ERROR 24
#define MCSC_INT0_COUTFIFO1_INPUT_PROTOCOL_ERROR 25
#define MCSC_INT0_COUTFIFO1_OVERFLOW_ERROR 26
#define MCSC_INT0_VOTF_GLOBAL_ERROR 27
#define MCSC_INT0_VOTF_LOST_CONNECTION 28
#define MCSC_INT0_OTF_SEQ_ID_ERROR 29

#define MCSC_INT1_BASE (HW_EVENT_MASK + 32)

#define MCSC_INT1_VOTF_LOST_FLUSH 0
#define MCSC_INT1_RDMA_IMG_FINISH 1
#define MCSC_INT1_RDMA_HF_FINISH 2
#define MCSC_INT1_WDMA_M0_FINISH 3
#define MCSC_INT1_WDMA_M1_FINISH 4
#define MCSC_INT1_WDMA_M2_FINISH 5
#define MCSC_INT1_WDMA_M3_FINISH 6
#define MCSC_INT1_WDMA_M4_FINISH 7
#define MCSC_INT1_RDMA_VOTF_LOST_CONNECTION 8
#define MCSC_INT1_COMP_DEC_ERROR 10
#define MCSC_INT1_DJAG_FINISH 11
#define MCSC_INT1_SC0_FINISH 12
#define MCSC_INT1_SC1_FINISH 13
#define MCSC_INT1_SC2_FINISH 14
#define MCSC_INT1_SC3_FINISH 15
#define MCSC_INT1_SC4_FINISH 16
#define MCSC_INT1_PC0_FINISH 17
#define MCSC_INT1_PC1_FINISH 18
#define MCSC_INT1_PC2_FINISH 19
#define MCSC_INT1_PC3_FINISH 20
#define MCSC_INT1_PC4_FINISH 21
#define MCSC_INT1_CONV4200_FINISH 22
#define MCSC_INT1_CONV4201_FINISH 23
#define MCSC_INT1_CONV4202_FINISH 24
#define MCSC_INT1_CONV4203_FINISH 25
#define MCSC_INT1_CONV4204_FINISH 26
#define MCSC_INT1_BCHS0_FINISH 27
#define MCSC_INT1_BCHS1_FINISH 28
#define MCSC_INT1_BCHS2_FINISH 29
#define MCSC_INT1_BCHS3_FINISH 30
#define MCSC_INT1_BCHS4_FINISH 31

#define MCSC_CMDQ_INT_BASE (HW_EVENT_MASK + 64)

#define MCSC_CMDQ_INT_STOP_CRPT_OFF_CMDQ_EN 0
#define MCSC_CMDQ_INT_PRELOAD_FLUSH 1
#define MCSC_CMDQ_INT_QUE0_OVERFLOW 2

/* clang-format on */

#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_FRAME_START \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_FRAME_START)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_FRAME_END \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_FRAME_END)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_CMDQ_HOLD \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_CMDQ_HOLD)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_SETTING_DONE \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_SETTING_DONE)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_C_LOADER_END \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_C_LOADER_END)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_COREX_END0 \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_COREX_END0)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_COREX_END1 \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_COREX_END1)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_ROW_COL \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_ROW_COL)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_FREEZE_ON_ROW_COL \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_FREEZE_ON_ROW_COL)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_TRANS_STOP_DONE \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_TRANS_STOP_DONE)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_CMDQ_ERROR \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_CMDQ_ERROR)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_C_LOADER_ERROR \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_C_LOADER_ERROR)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_COREX_ERROR \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_COREX_ERROR)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_CINFIFO0_OVERFLOW_ERROR \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_CINFIFO0_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_CINFIFO0_OVERLAP_ERROR \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_CINFIFO0_OVERLAP_ERROR)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_CINFIFO0_PIXEL_CNT_ERROR \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_CINFIFO0_PIXEL_CNT_ERROR)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_CINFIFO0_INPUT_PROTOCOL_ERROR \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_CINFIFO0_INPUT_PROTOCOL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_CINFIFO1_OVERFLOW_ERROR \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_CINFIFO1_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_CINFIFO1_OVERLAP_ERROR \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_CINFIFO1_OVERLAP_ERROR)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_CINFIFO1_PIXEL_CNT_ERROR \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_CINFIFO1_PIXEL_CNT_ERROR)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_CINFIFO1_INPUT_PROTOCOL_ERROR \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_CINFIFO1_INPUT_PROTOCOL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_COUTFIFO0_PIXEL_CNT_ERROR \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_COUTFIFO0_PIXEL_CNT_ERROR)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_COUTFIFO0_INPUT_PROTOCOL_ERROR \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_COUTFIFO0_INPUT_PROTOCOL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_COUTFIFO0_OVERFLOW_ERROR \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_COUTFIFO0_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_COUTFIFO1_PIXEL_CNT_ERROR \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_COUTFIFO1_PIXEL_CNT_ERROR)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_COUTFIFO1_INPUT_PROTOCOL_ERROR \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_COUTFIFO1_INPUT_PROTOCOL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_COUTFIFO1_OVERFLOW_ERROR \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_COUTFIFO1_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_VOTF_GLOBAL_ERROR \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_VOTF_GLOBAL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_VOTF_LOST_CONNECTION \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_VOTF_LOST_CONNECTION)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT0_OTF_SEQ_ID_ERROR \
	EVENT_ID(MCSC_INT0_BASE, \
		 MCSC_INT0_OTF_SEQ_ID_ERROR)

#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_VOTF_LOST_FLUSH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_VOTF_LOST_FLUSH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_RDMA_IMG_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_RDMA_IMG_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_RDMA_HF_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_RDMA_HF_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_WDMA_M0_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_WDMA_M0_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_WDMA_M1_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_WDMA_M1_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_WDMA_M2_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_WDMA_M2_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_WDMA_M3_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_WDMA_M3_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_WDMA_M4_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_WDMA_M4_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_RDMA_VOTF_LOST_CONNECTION \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_RDMA_VOTF_LOST_CONNECTION)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_COMP_DEC_ERROR \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_COMP_DEC_ERROR)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_DJAG_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_DJAG_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_SC0_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_SC0_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_SC1_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_SC1_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_SC2_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_SC2_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_SC3_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_SC3_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_SC4_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_SC4_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_PC0_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_PC0_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_PC1_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_PC1_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_PC2_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_PC2_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_PC3_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_PC3_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_PC4_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_PC4_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_CONV4200_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_CONV4200_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_CONV4201_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_CONV4201_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_CONV4202_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_CONV4202_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_CONV4203_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_CONV4203_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_CONV4204_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_CONV4204_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_BCHS0_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_BCHS0_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_BCHS1_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_BCHS1_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_BCHS2_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_BCHS2_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_BCHS3_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_BCHS3_FINISH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_INT1_BCHS4_FINISH \
	EVENT_ID(MCSC_INT1_BASE, \
		 MCSC_INT1_BCHS4_FINISH)

#define LWIS_PLATFORM_EVENT_ID_MCSC_CMDQ_INT_STOP_CRPT_OFF_CMDQ_EN \
	EVENT_ID(MCSC_CMDQ_INT_BASE, \
		 MCSC_CMDQ_INT_STOP_CRPT_OFF_CMDQ_EN)
#define LWIS_PLATFORM_EVENT_ID_MCSC_CMDQ_INT_PRELOAD_FLUSH \
	EVENT_ID(MCSC_CMDQ_INT_BASE, \
		 MCSC_CMDQ_INT_PRELOAD_FLUSH)
#define LWIS_PLATFORM_EVENT_ID_MCSC_CMDQ_INT_QUE0_OVERFLOW \
	EVENT_ID(MCSC_CMDQ_INT_BASE, \
		 MCSC_CMDQ_INT_QUE0_OVERFLOW)

#endif /* DT_BINDINGS_LWIS_PLATFORM_ZUMA_MCSC_H_ */
