ifndef CONFIG_MCPS802154
CONFIG_MCPS802154:=m
endif

obj-$(CONFIG_MCPS802154) := mcps802154.o mcps802154_region_fira.o \
	 mcps802154_region_nfcc_coex.o \
	 mcps802154_region_pctt.o \

ccflags-$(CONFIG_MCPS802154_TESTMODE) += -DCONFIG_MCPS802154_TESTMODE

mcps802154-y := \
	ca.o \
	default_region.o \
	endless_scheduler.o \
	on_demand_scheduler.o \
	idle_region.o \
	fproc.o \
	fproc_broken.o \
	fproc_multi.o \
	fproc_vendor.o \
	fproc_nothing.o \
	fproc_idle.o \
	fproc_rx.o \
	fproc_stopped.o \
	fproc_tx.o \
	frame.o \
	ie.o \
	mcps_main.o \
	mcps_skb_frag.o \
	nl.o \
	ops.o \
	regions.o \
	schedule.o \
	schedulers.o \
	trace.o

mcps802154_region_fira-y := \
	fira_access.o \
	fira_crypto.o \
	fira_round_hopping_sequence.o \
	fira_round_hopping_crypto.o \
	fira_frame.o \
	fira_region.o \
	fira_region_call.o \
	fira_session.o \
	fira_session_fsm.o \
	fira_session_fsm_init.o \
	fira_session_fsm_idle.o \
	fira_session_fsm_active.o \
	fira_sts.o \
	fira_trace.o \
	mcps_crypto.o

mcps802154_region_nfcc_coex-y := \
	nfcc_coex_access.o \
	nfcc_coex_region.o \
	nfcc_coex_region_call.o \
	nfcc_coex_session.o \
	nfcc_coex_trace.o

mcps802154_region_pctt-y := \
	pctt_access.o \
	pctt_region.o \
	pctt_region_call.o \
	pctt_session.o \
	pctt_trace.o

CFLAGS_trace.o := -I$(src) -I$(srctree)/$(src)
CFLAGS_fira_trace.o := -I$(src) -I$(srctree)/$(src)
CFLAGS_pctt_trace.o := -I$(src) -I$(srctree)/$(src)
CFLAGS_nfcc_coex_trace.o := -I$(src) -I$(srctree)/$(src)
