## SPDX-License-Identifier: GPL-2.0-only

ccflags-y += -I$(KERNEL_SRC)/../private/google-modules/trusty/include

obj-$(CONFIG_GSA) += gsa.o
gsa-objs := gsa_core.o gsa_log.o gsa_mbox.o gsa_tz.o

obj-$(CONFIG_GSA_GSC) += gsa_gsc.o

obj-$(CONFIG_TZ_PROT) += tzprot.o
