subdir-ccflags-y += -I$(srctree)/$(src)/../common/
subdir-ccflags-y += -I$(srctree)/arch/arm64/kvm/hyp/include/
subdir-ccflags-y += -DS2MPU_V1

obj-m += pkvm-s2mpu.o

$(obj)/../common/hyp/kvm_nvhe.o: FORCE
		$(Q)$(MAKE) $(build)=$(obj)/../common/hyp $(obj)/../common/hyp/kvm_nvhe.o

clean-files := hyp/hyp.lds hyp/hyp-reloc.S

pkvm-s2mpu-y := ../common/pkvm_s2mpu.o \
		../common/s2mpu.o \
		../common/exports.o \
		../common/hyp/kvm_nvhe.o \
		pkvm-s2mpu-faults.o
