#
# Copyright (c) 2015 Samsung Electronics Co., Ltd.
#		http://www.samsung.com
#

smfc-objs := smfc-dev.o smfc-v4l2-ioctls.o smfc-regs.o smfc-stream-parser.o
obj-$(CONFIG_VIDEO_EXYNOS_SMFC) += smfc.o
