/*
 * Copyright (c) 2015 Samsung Electronics Co., Ltd.
 *		http://www.samsung.com
 *
 * The SFR definition file of Samsung Exynos SMFC Driver
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef _MEDIA_EXYNOS_SMFC_REGS_H_
#define _MEDIA_EXYNOS_SMFC_REGS_H_

/********** H/W RESTRICTIONS **************************************************/
#define SMFC_MAX_WIDTH	16368U
#define SMFC_MAX_HEIGHT	16368U
#define SMFC_MIN_WIDTH	8U
#define SMFC_MIN_HEIGHT	8U

#define REG_MAIN_IMAGE_FORMAT		0x040
#define REG_SECD_IMAGE_FORMAT		0x0B8

#define REG_IP_VERSION_NUMBER		0x064

/* Value definitions of MAIN/SECONDARY_IMAGE_FORMAT */
enum {
	IMGSEL_GRAY,
	IMGSEL_RGB,
	IMGSEL_444,	/* YUV */
	IMGSEL_422,	/* YUV */
	IMGSEL_420,	/* YUV */
	IMGSEL_422V,	/* YUV */
	IMGSEL_411	/* YUV */
};
#define IMGFMT_RGBSHIFT		6
enum {
	RGBSEL_RGB565 = 4,
	RGBSEL_ARGB32,
	RGBSEL_RGB24,
};
#define IMGFMT_444SHIFT		9
#define IMGFMT_422SHIFT		12
#define IMGFMT_420SHIFT		15
#define IMGFMT_422VSHIFT	18
#define IMGFMT_411SHIFT		21
enum {
	YUVSEL_2P = 4,
	YUVSEL_3P = 5,
	YUV422SEL_1P = 4,
	YUV422SEL_2P = 5,
	YUV422SEL_3P = 6,
};

#define IMGFMT_RGBSWAP		(1 << 30)
#define IMGFMT_UVSWAP		(1 << 27)
enum {
	YUVSEL_YUYV = 0,
	YUVSEL_YVYU = 1 << 28,
	YUVSEL_UYVY = 2 << 28,
	YUVSEL_VYUY = 3 << 28,
};

#define SMFC_IMGFMT_RGB565 (IMGSEL_RGB | (RGBSEL_RGB565 << IMGFMT_RGBSHIFT))
#define SMFC_IMGFMT_BGR565 (IMGSEL_RGB | (RGBSEL_RGB565 << IMGFMT_RGBSHIFT)\
				| IMGFMT_RGBSWAP)
#define SMFC_IMGFMT_RGB24  (IMGSEL_RGB | (RGBSEL_RGB24 << IMGFMT_RGBSHIFT))
#define SMFC_IMGFMT_BGR24  (IMGSEL_RGB | (RGBSEL_RGB24 << IMGFMT_RGBSHIFT) \
				| IMGFMT_RGBSWAP)
#define SMFC_IMGFMT_BGRA32  (IMGSEL_RGB | (RGBSEL_ARGB32 << IMGFMT_RGBSHIFT))
#define SMFC_IMGFMT_RGBA32  (IMGSEL_RGB | (RGBSEL_ARGB32 << IMGFMT_RGBSHIFT)\
				| IMGFMT_RGBSWAP)
#define SMFC_IMGFMT_NV12    (IMGSEL_420 | (YUVSEL_2P << IMGFMT_420SHIFT))
#define SMFC_IMGFMT_NV21    (IMGSEL_420 | (YUVSEL_2P << IMGFMT_420SHIFT) \
				| IMGFMT_UVSWAP)
#define SMFC_IMGFMT_YUV420P (IMGSEL_420 | (YUVSEL_3P << IMGFMT_420SHIFT))
#define SMFC_IMGFMT_YVU420P (IMGSEL_420 | (YUVSEL_3P << IMGFMT_420SHIFT) \
				| IMGFMT_UVSWAP)
#define SMFC_IMGFMT_YUYV    (IMGSEL_422 | (YUV422SEL_1P << IMGFMT_422SHIFT) \
				| YUVSEL_YUYV)
#define SMFC_IMGFMT_YVYU    (IMGSEL_422 | (YUV422SEL_1P << IMGFMT_422SHIFT) \
				| YUVSEL_YVYU)
#define SMFC_IMGFMT_UYVY    (IMGSEL_422 | (YUV422SEL_1P << IMGFMT_422SHIFT) \
				| YUVSEL_UYVY)
#define SMFC_IMGFMT_VYUY    (IMGSEL_422 | (YUV422SEL_1P << IMGFMT_422SHIFT) \
				| YUVSEL_VYUY)
#define SMFC_IMGFMT_NV16    (IMGSEL_422 | (YUV422SEL_2P << IMGFMT_422SHIFT))
#define SMFC_IMGFMT_NV61    (IMGSEL_422 | (YUV422SEL_2P << IMGFMT_422SHIFT) \
				| IMGFMT_UVSWAP)
#define SMFC_IMGFMT_YUV422  (IMGSEL_422 | (YUV422SEL_3P << IMGFMT_422SHIFT))
#define SMFC_IMGFMT_YUV444  (IMGSEL_444 | (YUVSEL_3P << IMGFMT_444SHIFT))

#define SMFC_IMGFMT_JPEG444  (1 << 24)
#define SMFC_IMGFMT_JPEG422  (2 << 24)
#define SMFC_IMGFMT_JPEG420  (3 << 24)
#define SMFC_IMGFMT_JPEG422V (4 << 24)
#define SMFC_IMGFMT_JPEG411  (5 << 24)

#endif /* _MEDIA_EXYNOS_SMFC_REGS_H_ */
