/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Google LWIS GS101 PDP Interrupt And Event Defines
 *
 * Copyright (c) 2020 Google, LLC
 */

#ifndef DT_BINDINGS_LWIS_PLATFORM_GS101_PDP_H_
#define DT_BINDINGS_LWIS_PLATFORM_GS101_PDP_H_

#include <dt-bindings/lwis/platform/common.h>

/* clang-format off */


#define PDP_INT_SRC1_CTX0_BASE (HW_EVENT_MASK + 0)

#define PDP_INT_SRC1_CTX0_FRAME_START 0
#define PDP_INT_SRC1_CTX0_FRAME_END_INTERRUPT 1
#define PDP_INT_SRC1_CTX0_FRAME_INT_ON_ROW_COL_INFO 2
#define PDP_INT_SRC1_CTX0_IRQ_CORRUPTED 3
#define PDP_INT_SRC1_CTX0_COREX_ERROR_INT 4
#define PDP_INT_SRC1_CTX0_PRE_FRAME_END_INTERRUPT 6
#define PDP_INT_SRC1_CTX0_LIC_INPUT_FRAME_END 7
#define PDP_INT_SRC1_CTX0_LIC_OUTPUT_FRAME_END 8
#define PDP_INT_SRC1_CTX0_AFIDENT_DATA_IN_LAST 9
#define PDP_INT_SRC1_CTX0_COUTFIFO_DATA_OUT_END_INT 10
#define PDP_INT_SRC1_CTX0_COUTFIFO_FRAME_OUT_END_INT 11
#define PDP_INT_SRC1_CTX0_RCB_OUTPUT_LAST 12
#define PDP_INT_SRC1_CTX0_MPD_IR_OUTPUT_LAST 13
#define PDP_INT_SRC1_CTX0_YEXT_OUTPUT_LAST 14
#define PDP_INT_SRC1_CTX0_BPC_IR_OUTPUT_LAST 15
#define PDP_INT_SRC1_CTX0_REORDER_IR_OUTPUT_LAST 16
#define PDP_INT_SRC1_CTX0_GAMMA0_OUTPUT_LAST 17
#define PDP_INT_SRC1_CTX0_GAMMA1_IR_OUTPUT_LAST 18
#define PDP_INT_SRC1_CTX0_ALC_IR_LAST_G3AAY_FRAME_OUT_END_INT 19
#define PDP_INT_SRC1_CTX0_COREX_END_INT0 20
#define PDP_INT_SRC1_CTX0_COREX_END_INT1 21
#define PDP_INT_SRC1_CTX0_COUTFIFO_G3AAB_DATA_OUT_END_INT 22
#define PDP_INT_SRC1_CTX0_COUTFIFO_G3AAB_FRAME_OUT_END_INT 23
#define PDP_INT_SRC1_CTX0_COUTFIFO_G3AAY_DATA_OUT_END_INT 24
#define PDP_INT_SRC1_CTX0_COUTFIFO_G3AAY_FRAME_OUT_END_INT 25

#define PDP_INT_SRC1_CTX1_BASE (HW_EVENT_MASK + 32)

#define PDP_INT_SRC1_CTX1_FRAME_START 0
#define PDP_INT_SRC1_CTX1_FRAME_END_INTERRUPT 1
#define PDP_INT_SRC1_CTX1_FRAME_INT_ON_ROW_COL_INFO 2
#define PDP_INT_SRC1_CTX1_IRQ_CORRUPTED 3
#define PDP_INT_SRC1_CTX1_COREX_ERROR_INT 4
#define PDP_INT_SRC1_CTX1_PRE_FRAME_END_INTERRUPT 6
#define PDP_INT_SRC1_CTX1_LIC_INPUT_FRAME_END 7
#define PDP_INT_SRC1_CTX1_LIC_OUTPUT_FRAME_END 8
#define PDP_INT_SRC1_CTX1_AFIDENT_DATA_IN_LAST 9
#define PDP_INT_SRC1_CTX1_COUTFIFO_DATA_OUT_END_INT 10
#define PDP_INT_SRC1_CTX1_COUTFIFO_FRAME_OUT_END_INT 11
#define PDP_INT_SRC1_CTX1_RCB_OUTPUT_LAST 12
#define PDP_INT_SRC1_CTX1_MPD_IR_OUTPUT_LAST 13
#define PDP_INT_SRC1_CTX1_YEXT_OUTPUT_LAST 14
#define PDP_INT_SRC1_CTX1_BPC_IR_OUTPUT_LAST 15
#define PDP_INT_SRC1_CTX1_REORDER_IR_OUTPUT_LAST 16
#define PDP_INT_SRC1_CTX1_GAMMA0_OUTPUT_LAST 17
#define PDP_INT_SRC1_CTX1_GAMMA1_IR_OUTPUT_LAST 18
#define PDP_INT_SRC1_CTX1_ALC_IR_LAST_G3AAY_FRAME_OUT_END_INT 19
#define PDP_INT_SRC1_CTX1_COREX_END_INT0 20
#define PDP_INT_SRC1_CTX1_COREX_END_INT1 21
#define PDP_INT_SRC1_CTX1_COUTFIFO_G3AAB_DATA_OUT_END_INT 22
#define PDP_INT_SRC1_CTX1_COUTFIFO_G3AAB_FRAME_OUT_END_INT 23
#define PDP_INT_SRC1_CTX1_COUTFIFO_G3AAY_DATA_OUT_END_INT 24
#define PDP_INT_SRC1_CTX1_COUTFIFO_G3AAY_FRAME_OUT_END_INT 25

#define PDP_INT_SRC1_CTX2_BASE (HW_EVENT_MASK + 64)

#define PDP_INT_SRC1_CTX2_FRAME_START 0
#define PDP_INT_SRC1_CTX2_FRAME_END_INTERRUPT 1
#define PDP_INT_SRC1_CTX2_FRAME_INT_ON_ROW_COL_INFO 2
#define PDP_INT_SRC1_CTX2_IRQ_CORRUPTED 3
#define PDP_INT_SRC1_CTX2_COREX_ERROR_INT 4
#define PDP_INT_SRC1_CTX2_PRE_FRAME_END_INTERRUPT 6
#define PDP_INT_SRC1_CTX2_LIC_INPUT_FRAME_END 7
#define PDP_INT_SRC1_CTX2_LIC_OUTPUT_FRAME_END 8
#define PDP_INT_SRC1_CTX2_AFIDENT_DATA_IN_LAST 9
#define PDP_INT_SRC1_CTX2_COUTFIFO_DATA_OUT_END_INT 10
#define PDP_INT_SRC1_CTX2_COUTFIFO_FRAME_OUT_END_INT 11
#define PDP_INT_SRC1_CTX2_RCB_OUTPUT_LAST 12
#define PDP_INT_SRC1_CTX2_MPD_IR_OUTPUT_LAST 13
#define PDP_INT_SRC1_CTX2_YEXT_OUTPUT_LAST 14
#define PDP_INT_SRC1_CTX2_BPC_IR_OUTPUT_LAST 15
#define PDP_INT_SRC1_CTX2_REORDER_IR_OUTPUT_LAST 16
#define PDP_INT_SRC1_CTX2_GAMMA0_OUTPUT_LAST 17
#define PDP_INT_SRC1_CTX2_GAMMA1_IR_OUTPUT_LAST 18
#define PDP_INT_SRC1_CTX2_ALC_IR_LAST_G3AAY_FRAME_OUT_END_INT 19
#define PDP_INT_SRC1_CTX2_COREX_END_INT0 20
#define PDP_INT_SRC1_CTX2_COREX_END_INT1 21
#define PDP_INT_SRC1_CTX2_COUTFIFO_G3AAB_DATA_OUT_END_INT 22
#define PDP_INT_SRC1_CTX2_COUTFIFO_G3AAB_FRAME_OUT_END_INT 23
#define PDP_INT_SRC1_CTX2_COUTFIFO_G3AAY_DATA_OUT_END_INT 24
#define PDP_INT_SRC1_CTX2_COUTFIFO_G3AAY_FRAME_OUT_END_INT 25



#define PDP_INT_SRC2_CTX0_BASE (HW_EVENT_MASK + 96)

#define PDP_INT_SRC2_CTX0_COUTFIFO_FRAME_OUT_START_INT 1
#define PDP_INT_SRC2_CTX0_VOTF_LOST_FLUSH_IMG 5
#define PDP_INT_SRC2_CTX0_VOTF_LOST_FLUSH_AF 6
#define PDP_INT_SRC2_CTX0_C2SER_SLOW_RING 7
#define PDP_INT_SRC2_CTX0_PDAF_STAT_INT 8
#define PDP_INT_SRC2_CTX0_SBWC_ERR 9
#define PDP_INT_SRC2_CTX0_VOTF_LOSTCON_IMG 10
#define PDP_INT_SRC2_CTX0_VOTF_LOSTCON_AF 11
#define PDP_INT_SRC2_CTX0_COUTFIFO_G3AA_BFRAME_OUT_START_INT 12
#define PDP_INT_SRC2_CTX0_COUTFIFO_G3AA_YFRAME_OUT_START_INT 13
#define PDP_INT_SRC2_CTX0_COUTFIFO_SIZE_ERROR 14
#define PDP_INT_SRC2_CTX0_COUTFIFO_LINE_ERROR 15
#define PDP_INT_SRC2_CTX0_COUTFIFO_COL_ERROR 16
#define PDP_INT_SRC2_CTX0_COUTFIFO_OVERFLOW_ERROR 17
#define PDP_INT_SRC2_CTX0_CINFIFO_TOTAL_SIZE_ERROR_INT 18
#define PDP_INT_SRC2_CTX0_CINFIFO_LINES_ERROR_INT 19
#define PDP_INT_SRC2_CTX0_CINFIFO_COLUMNS_ERROR_INT 20
#define PDP_INT_SRC2_CTX0_CINFIFO_STREAM_OVERFLOW_SIG 21
#define PDP_INT_SRC2_CTX0_COUTFIFO_G3AAB_SIZE_ERROR 24
#define PDP_INT_SRC2_CTX0_COUTFIFO_G3AAB_LINE_ERROR 25
#define PDP_INT_SRC2_CTX0_COUTFIFO_G3AAB_COL_ERROR 26
#define PDP_INT_SRC2_CTX0_COUTFIFO_G3AAB_OVERFLOW_ERROR 27
#define PDP_INT_SRC2_CTX0_COUTFIFO_G3AAY_SIZE_ERROR 28
#define PDP_INT_SRC2_CTX0_COUTFIFO_G3AAY_LINE_ERROR 29
#define PDP_INT_SRC2_CTX0_COUTFIFO_G3AAY_COL_ERROR 30
#define PDP_INT_SRC2_CTX0_COUTFIFO_G3AAY_OVERFLOW_ERROR 31

#define PDP_INT_SRC2_CTX1_BASE (HW_EVENT_MASK + 128)

#define PDP_INT_SRC2_CTX1_COUTFIFO_FRAME_OUT_START_INT 1
#define PDP_INT_SRC2_CTX1_VOTF_LOST_FLUSH_IMG 5
#define PDP_INT_SRC2_CTX1_VOTF_LOST_FLUSH_AF 6
#define PDP_INT_SRC2_CTX1_C2SER_SLOW_RING 7
#define PDP_INT_SRC2_CTX1_PDAF_STAT_INT 8
#define PDP_INT_SRC2_CTX1_SBWC_ERR 9
#define PDP_INT_SRC2_CTX1_VOTF_LOSTCON_IMG 10
#define PDP_INT_SRC2_CTX1_VOTF_LOSTCON_AF 11
#define PDP_INT_SRC2_CTX1_COUTFIFO_G3AA_BFRAME_OUT_START_INT 12
#define PDP_INT_SRC2_CTX1_COUTFIFO_G3AA_YFRAME_OUT_START_INT 13
#define PDP_INT_SRC2_CTX1_COUTFIFO_SIZE_ERROR 14
#define PDP_INT_SRC2_CTX1_COUTFIFO_LINE_ERROR 15
#define PDP_INT_SRC2_CTX1_COUTFIFO_COL_ERROR 16
#define PDP_INT_SRC2_CTX1_COUTFIFO_OVERFLOW_ERROR 17
#define PDP_INT_SRC2_CTX1_CINFIFO_TOTAL_SIZE_ERROR_INT 18
#define PDP_INT_SRC2_CTX1_CINFIFO_LINES_ERROR_INT 19
#define PDP_INT_SRC2_CTX1_CINFIFO_COLUMNS_ERROR_INT 20
#define PDP_INT_SRC2_CTX1_CINFIFO_STREAM_OVERFLOW_SIG 21
#define PDP_INT_SRC2_CTX1_COUTFIFO_G3AAB_SIZE_ERROR 24
#define PDP_INT_SRC2_CTX1_COUTFIFO_G3AAB_LINE_ERROR 25
#define PDP_INT_SRC2_CTX1_COUTFIFO_G3AAB_COL_ERROR 26
#define PDP_INT_SRC2_CTX1_COUTFIFO_G3AAB_OVERFLOW_ERROR 27
#define PDP_INT_SRC2_CTX1_COUTFIFO_G3AAY_SIZE_ERROR 28
#define PDP_INT_SRC2_CTX1_COUTFIFO_G3AAY_LINE_ERROR 29
#define PDP_INT_SRC2_CTX1_COUTFIFO_G3AAY_COL_ERROR 30
#define PDP_INT_SRC2_CTX1_COUTFIFO_G3AAY_OVERFLOW_ERROR 31

#define PDP_INT_SRC2_CTX2_BASE (HW_EVENT_MASK + 160)

#define PDP_INT_SRC2_CTX2_COUTFIFO_FRAME_OUT_START_INT 1
#define PDP_INT_SRC2_CTX2_VOTF_LOST_FLUSH_IMG 5
#define PDP_INT_SRC2_CTX2_VOTF_LOST_FLUSH_AF 6
#define PDP_INT_SRC2_CTX2_C2SER_SLOW_RING 7
#define PDP_INT_SRC2_CTX2_PDAF_STAT_INT 8
#define PDP_INT_SRC2_CTX2_SBWC_ERR 9
#define PDP_INT_SRC2_CTX2_VOTF_LOSTCON_IMG 10
#define PDP_INT_SRC2_CTX2_VOTF_LOSTCON_AF 11
#define PDP_INT_SRC2_CTX2_COUTFIFO_G3AA_BFRAME_OUT_START_INT 12
#define PDP_INT_SRC2_CTX2_COUTFIFO_G3AA_YFRAME_OUT_START_INT 13
#define PDP_INT_SRC2_CTX2_COUTFIFO_SIZE_ERROR 14
#define PDP_INT_SRC2_CTX2_COUTFIFO_LINE_ERROR 15
#define PDP_INT_SRC2_CTX2_COUTFIFO_COL_ERROR 16
#define PDP_INT_SRC2_CTX2_COUTFIFO_OVERFLOW_ERROR 17
#define PDP_INT_SRC2_CTX2_CINFIFO_TOTAL_SIZE_ERROR_INT 18
#define PDP_INT_SRC2_CTX2_CINFIFO_LINES_ERROR_INT 19
#define PDP_INT_SRC2_CTX2_CINFIFO_COLUMNS_ERROR_INT 20
#define PDP_INT_SRC2_CTX2_CINFIFO_STREAM_OVERFLOW_SIG 21
#define PDP_INT_SRC2_CTX2_COUTFIFO_G3AAB_SIZE_ERROR 24
#define PDP_INT_SRC2_CTX2_COUTFIFO_G3AAB_LINE_ERROR 25
#define PDP_INT_SRC2_CTX2_COUTFIFO_G3AAB_COL_ERROR 26
#define PDP_INT_SRC2_CTX2_COUTFIFO_G3AAB_OVERFLOW_ERROR 27
#define PDP_INT_SRC2_CTX2_COUTFIFO_G3AAY_SIZE_ERROR 28
#define PDP_INT_SRC2_CTX2_COUTFIFO_G3AAY_LINE_ERROR 29
#define PDP_INT_SRC2_CTX2_COUTFIFO_G3AAY_COL_ERROR 30
#define PDP_INT_SRC2_CTX2_COUTFIFO_G3AAY_OVERFLOW_ERROR 31




/* clang-format on */


#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_FRAME_START \
  EVENT_ID(PDP_INT_SRC1_CTX0_BASE, \
           PDP_INT_SRC1_CTX0_FRAME_START)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_FRAME_END_INTERRUPT \
  EVENT_ID(PDP_INT_SRC1_CTX0_BASE, \
           PDP_INT_SRC1_CTX0_FRAME_END_INTERRUPT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_FRAME_INT_ON_ROW_COL_INFO \
  EVENT_ID(PDP_INT_SRC1_CTX0_BASE, \
           PDP_INT_SRC1_CTX0_FRAME_INT_ON_ROW_COL_INFO)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_IRQ_CORRUPTED \
  EVENT_ID(PDP_INT_SRC1_CTX0_BASE, \
           PDP_INT_SRC1_CTX0_IRQ_CORRUPTED)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_COREX_ERROR_INT \
  EVENT_ID(PDP_INT_SRC1_CTX0_BASE, \
           PDP_INT_SRC1_CTX0_COREX_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_PRE_FRAME_END_INTERRUPT \
  EVENT_ID(PDP_INT_SRC1_CTX0_BASE, \
           PDP_INT_SRC1_CTX0_PRE_FRAME_END_INTERRUPT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_LIC_INPUT_FRAME_END \
  EVENT_ID(PDP_INT_SRC1_CTX0_BASE, \
           PDP_INT_SRC1_CTX0_LIC_INPUT_FRAME_END)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_LIC_OUTPUT_FRAME_END \
  EVENT_ID(PDP_INT_SRC1_CTX0_BASE, \
           PDP_INT_SRC1_CTX0_LIC_OUTPUT_FRAME_END)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_AFIDENT_DATA_IN_LAST \
  EVENT_ID(PDP_INT_SRC1_CTX0_BASE, \
           PDP_INT_SRC1_CTX0_AFIDENT_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_COUTFIFO_DATA_OUT_END_INT \
  EVENT_ID(PDP_INT_SRC1_CTX0_BASE, \
           PDP_INT_SRC1_CTX0_COUTFIFO_DATA_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_COUTFIFO_FRAME_OUT_END_INT \
  EVENT_ID(PDP_INT_SRC1_CTX0_BASE, \
           PDP_INT_SRC1_CTX0_COUTFIFO_FRAME_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_RCB_OUTPUT_LAST \
  EVENT_ID(PDP_INT_SRC1_CTX0_BASE, \
           PDP_INT_SRC1_CTX0_RCB_OUTPUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_MPD_IR_OUTPUT_LAST \
  EVENT_ID(PDP_INT_SRC1_CTX0_BASE, \
           PDP_INT_SRC1_CTX0_MPD_IR_OUTPUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_YEXT_OUTPUT_LAST \
  EVENT_ID(PDP_INT_SRC1_CTX0_BASE, \
           PDP_INT_SRC1_CTX0_YEXT_OUTPUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_BPC_IR_OUTPUT_LAST \
  EVENT_ID(PDP_INT_SRC1_CTX0_BASE, \
           PDP_INT_SRC1_CTX0_BPC_IR_OUTPUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_REORDER_IR_OUTPUT_LAST \
  EVENT_ID(PDP_INT_SRC1_CTX0_BASE, \
           PDP_INT_SRC1_CTX0_REORDER_IR_OUTPUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_GAMMA0_OUTPUT_LAST \
  EVENT_ID(PDP_INT_SRC1_CTX0_BASE, \
           PDP_INT_SRC1_CTX0_GAMMA0_OUTPUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_GAMMA1_IR_OUTPUT_LAST \
  EVENT_ID(PDP_INT_SRC1_CTX0_BASE, \
           PDP_INT_SRC1_CTX0_GAMMA1_IR_OUTPUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_ALC_IR_LAST_G3AAY_FRAME_OUT_END_INT \
  EVENT_ID(PDP_INT_SRC1_CTX0_BASE, \
           PDP_INT_SRC1_CTX0_ALC_IR_LAST_G3AAY_FRAME_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_COREX_END_INT0 \
  EVENT_ID(PDP_INT_SRC1_CTX0_BASE, \
           PDP_INT_SRC1_CTX0_COREX_END_INT0)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_COREX_END_INT1 \
  EVENT_ID(PDP_INT_SRC1_CTX0_BASE, \
           PDP_INT_SRC1_CTX0_COREX_END_INT1)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_COUTFIFO_G3AAB_DATA_OUT_END_INT \
  EVENT_ID(PDP_INT_SRC1_CTX0_BASE, \
           PDP_INT_SRC1_CTX0_COUTFIFO_G3AAB_DATA_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_COUTFIFO_G3AAB_FRAME_OUT_END_INT \
  EVENT_ID(PDP_INT_SRC1_CTX0_BASE, \
           PDP_INT_SRC1_CTX0_COUTFIFO_G3AAB_FRAME_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_COUTFIFO_G3AAY_DATA_OUT_END_INT \
  EVENT_ID(PDP_INT_SRC1_CTX0_BASE, \
           PDP_INT_SRC1_CTX0_COUTFIFO_G3AAY_DATA_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_COUTFIFO_G3AAY_FRAME_OUT_END_INT \
  EVENT_ID(PDP_INT_SRC1_CTX0_BASE, \
           PDP_INT_SRC1_CTX0_COUTFIFO_G3AAY_FRAME_OUT_END_INT)

#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_FRAME_START \
  EVENT_ID(PDP_INT_SRC1_CTX1_BASE, \
           PDP_INT_SRC1_CTX1_FRAME_START)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_FRAME_END_INTERRUPT \
  EVENT_ID(PDP_INT_SRC1_CTX1_BASE, \
           PDP_INT_SRC1_CTX1_FRAME_END_INTERRUPT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_FRAME_INT_ON_ROW_COL_INFO \
  EVENT_ID(PDP_INT_SRC1_CTX1_BASE, \
           PDP_INT_SRC1_CTX1_FRAME_INT_ON_ROW_COL_INFO)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_IRQ_CORRUPTED \
  EVENT_ID(PDP_INT_SRC1_CTX1_BASE, \
           PDP_INT_SRC1_CTX1_IRQ_CORRUPTED)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_COREX_ERROR_INT \
  EVENT_ID(PDP_INT_SRC1_CTX1_BASE, \
           PDP_INT_SRC1_CTX1_COREX_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_PRE_FRAME_END_INTERRUPT \
  EVENT_ID(PDP_INT_SRC1_CTX1_BASE, \
           PDP_INT_SRC1_CTX1_PRE_FRAME_END_INTERRUPT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_LIC_INPUT_FRAME_END \
  EVENT_ID(PDP_INT_SRC1_CTX1_BASE, \
           PDP_INT_SRC1_CTX1_LIC_INPUT_FRAME_END)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_LIC_OUTPUT_FRAME_END \
  EVENT_ID(PDP_INT_SRC1_CTX1_BASE, \
           PDP_INT_SRC1_CTX1_LIC_OUTPUT_FRAME_END)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_AFIDENT_DATA_IN_LAST \
  EVENT_ID(PDP_INT_SRC1_CTX1_BASE, \
           PDP_INT_SRC1_CTX1_AFIDENT_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_COUTFIFO_DATA_OUT_END_INT \
  EVENT_ID(PDP_INT_SRC1_CTX1_BASE, \
           PDP_INT_SRC1_CTX1_COUTFIFO_DATA_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_COUTFIFO_FRAME_OUT_END_INT \
  EVENT_ID(PDP_INT_SRC1_CTX1_BASE, \
           PDP_INT_SRC1_CTX1_COUTFIFO_FRAME_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_RCB_OUTPUT_LAST \
  EVENT_ID(PDP_INT_SRC1_CTX1_BASE, \
           PDP_INT_SRC1_CTX1_RCB_OUTPUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_MPD_IR_OUTPUT_LAST \
  EVENT_ID(PDP_INT_SRC1_CTX1_BASE, \
           PDP_INT_SRC1_CTX1_MPD_IR_OUTPUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_YEXT_OUTPUT_LAST \
  EVENT_ID(PDP_INT_SRC1_CTX1_BASE, \
           PDP_INT_SRC1_CTX1_YEXT_OUTPUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_BPC_IR_OUTPUT_LAST \
  EVENT_ID(PDP_INT_SRC1_CTX1_BASE, \
           PDP_INT_SRC1_CTX1_BPC_IR_OUTPUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_REORDER_IR_OUTPUT_LAST \
  EVENT_ID(PDP_INT_SRC1_CTX1_BASE, \
           PDP_INT_SRC1_CTX1_REORDER_IR_OUTPUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_GAMMA0_OUTPUT_LAST \
  EVENT_ID(PDP_INT_SRC1_CTX1_BASE, \
           PDP_INT_SRC1_CTX1_GAMMA0_OUTPUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_GAMMA1_IR_OUTPUT_LAST \
  EVENT_ID(PDP_INT_SRC1_CTX1_BASE, \
           PDP_INT_SRC1_CTX1_GAMMA1_IR_OUTPUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_ALC_IR_LAST_G3AAY_FRAME_OUT_END_INT \
  EVENT_ID(PDP_INT_SRC1_CTX1_BASE, \
           PDP_INT_SRC1_CTX1_ALC_IR_LAST_G3AAY_FRAME_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_COREX_END_INT0 \
  EVENT_ID(PDP_INT_SRC1_CTX1_BASE, \
           PDP_INT_SRC1_CTX1_COREX_END_INT0)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_COREX_END_INT1 \
  EVENT_ID(PDP_INT_SRC1_CTX1_BASE, \
           PDP_INT_SRC1_CTX1_COREX_END_INT1)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_COUTFIFO_G3AAB_DATA_OUT_END_INT \
  EVENT_ID(PDP_INT_SRC1_CTX1_BASE, \
           PDP_INT_SRC1_CTX1_COUTFIFO_G3AAB_DATA_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_COUTFIFO_G3AAB_FRAME_OUT_END_INT \
  EVENT_ID(PDP_INT_SRC1_CTX1_BASE, \
           PDP_INT_SRC1_CTX1_COUTFIFO_G3AAB_FRAME_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_COUTFIFO_G3AAY_DATA_OUT_END_INT \
  EVENT_ID(PDP_INT_SRC1_CTX1_BASE, \
           PDP_INT_SRC1_CTX1_COUTFIFO_G3AAY_DATA_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_COUTFIFO_G3AAY_FRAME_OUT_END_INT \
  EVENT_ID(PDP_INT_SRC1_CTX1_BASE, \
           PDP_INT_SRC1_CTX1_COUTFIFO_G3AAY_FRAME_OUT_END_INT)

#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_FRAME_START \
  EVENT_ID(PDP_INT_SRC1_CTX2_BASE, \
           PDP_INT_SRC1_CTX2_FRAME_START)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_FRAME_END_INTERRUPT \
  EVENT_ID(PDP_INT_SRC1_CTX2_BASE, \
           PDP_INT_SRC1_CTX2_FRAME_END_INTERRUPT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_FRAME_INT_ON_ROW_COL_INFO \
  EVENT_ID(PDP_INT_SRC1_CTX2_BASE, \
           PDP_INT_SRC1_CTX2_FRAME_INT_ON_ROW_COL_INFO)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_IRQ_CORRUPTED \
  EVENT_ID(PDP_INT_SRC1_CTX2_BASE, \
           PDP_INT_SRC1_CTX2_IRQ_CORRUPTED)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_COREX_ERROR_INT \
  EVENT_ID(PDP_INT_SRC1_CTX2_BASE, \
           PDP_INT_SRC1_CTX2_COREX_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_PRE_FRAME_END_INTERRUPT \
  EVENT_ID(PDP_INT_SRC1_CTX2_BASE, \
           PDP_INT_SRC1_CTX2_PRE_FRAME_END_INTERRUPT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_LIC_INPUT_FRAME_END \
  EVENT_ID(PDP_INT_SRC1_CTX2_BASE, \
           PDP_INT_SRC1_CTX2_LIC_INPUT_FRAME_END)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_LIC_OUTPUT_FRAME_END \
  EVENT_ID(PDP_INT_SRC1_CTX2_BASE, \
           PDP_INT_SRC1_CTX2_LIC_OUTPUT_FRAME_END)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_AFIDENT_DATA_IN_LAST \
  EVENT_ID(PDP_INT_SRC1_CTX2_BASE, \
           PDP_INT_SRC1_CTX2_AFIDENT_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_COUTFIFO_DATA_OUT_END_INT \
  EVENT_ID(PDP_INT_SRC1_CTX2_BASE, \
           PDP_INT_SRC1_CTX2_COUTFIFO_DATA_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_COUTFIFO_FRAME_OUT_END_INT \
  EVENT_ID(PDP_INT_SRC1_CTX2_BASE, \
           PDP_INT_SRC1_CTX2_COUTFIFO_FRAME_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_RCB_OUTPUT_LAST \
  EVENT_ID(PDP_INT_SRC1_CTX2_BASE, \
           PDP_INT_SRC1_CTX2_RCB_OUTPUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_MPD_IR_OUTPUT_LAST \
  EVENT_ID(PDP_INT_SRC1_CTX2_BASE, \
           PDP_INT_SRC1_CTX2_MPD_IR_OUTPUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_YEXT_OUTPUT_LAST \
  EVENT_ID(PDP_INT_SRC1_CTX2_BASE, \
           PDP_INT_SRC1_CTX2_YEXT_OUTPUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_BPC_IR_OUTPUT_LAST \
  EVENT_ID(PDP_INT_SRC1_CTX2_BASE, \
           PDP_INT_SRC1_CTX2_BPC_IR_OUTPUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_REORDER_IR_OUTPUT_LAST \
  EVENT_ID(PDP_INT_SRC1_CTX2_BASE, \
           PDP_INT_SRC1_CTX2_REORDER_IR_OUTPUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_GAMMA0_OUTPUT_LAST \
  EVENT_ID(PDP_INT_SRC1_CTX2_BASE, \
           PDP_INT_SRC1_CTX2_GAMMA0_OUTPUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_GAMMA1_IR_OUTPUT_LAST \
  EVENT_ID(PDP_INT_SRC1_CTX2_BASE, \
           PDP_INT_SRC1_CTX2_GAMMA1_IR_OUTPUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_ALC_IR_LAST_G3AAY_FRAME_OUT_END_INT \
  EVENT_ID(PDP_INT_SRC1_CTX2_BASE, \
           PDP_INT_SRC1_CTX2_ALC_IR_LAST_G3AAY_FRAME_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_COREX_END_INT0 \
  EVENT_ID(PDP_INT_SRC1_CTX2_BASE, \
           PDP_INT_SRC1_CTX2_COREX_END_INT0)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_COREX_END_INT1 \
  EVENT_ID(PDP_INT_SRC1_CTX2_BASE, \
           PDP_INT_SRC1_CTX2_COREX_END_INT1)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_COUTFIFO_G3AAB_DATA_OUT_END_INT \
  EVENT_ID(PDP_INT_SRC1_CTX2_BASE, \
           PDP_INT_SRC1_CTX2_COUTFIFO_G3AAB_DATA_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_COUTFIFO_G3AAB_FRAME_OUT_END_INT \
  EVENT_ID(PDP_INT_SRC1_CTX2_BASE, \
           PDP_INT_SRC1_CTX2_COUTFIFO_G3AAB_FRAME_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_COUTFIFO_G3AAY_DATA_OUT_END_INT \
  EVENT_ID(PDP_INT_SRC1_CTX2_BASE, \
           PDP_INT_SRC1_CTX2_COUTFIFO_G3AAY_DATA_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_COUTFIFO_G3AAY_FRAME_OUT_END_INT \
  EVENT_ID(PDP_INT_SRC1_CTX2_BASE, \
           PDP_INT_SRC1_CTX2_COUTFIFO_G3AAY_FRAME_OUT_END_INT)



#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_COUTFIFO_FRAME_OUT_START_INT \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_COUTFIFO_FRAME_OUT_START_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_VOTF_LOST_FLUSH_IMG \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_VOTF_LOST_FLUSH_IMG)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_VOTF_LOST_FLUSH_AF \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_VOTF_LOST_FLUSH_AF)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_C2SER_SLOW_RING \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_C2SER_SLOW_RING)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_PDAF_STAT_INT \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_PDAF_STAT_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_SBWC_ERR \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_SBWC_ERR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_VOTF_LOSTCON_IMG \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_VOTF_LOSTCON_IMG)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_VOTF_LOSTCON_AF \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_VOTF_LOSTCON_AF)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_COUTFIFO_G3AA_BFRAME_OUT_START_INT \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_COUTFIFO_G3AA_BFRAME_OUT_START_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_COUTFIFO_G3AA_YFRAME_OUT_START_INT \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_COUTFIFO_G3AA_YFRAME_OUT_START_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_COUTFIFO_SIZE_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_COUTFIFO_SIZE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_COUTFIFO_LINE_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_COUTFIFO_LINE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_COUTFIFO_COL_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_COUTFIFO_COL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_COUTFIFO_OVERFLOW_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_COUTFIFO_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_CINFIFO_TOTAL_SIZE_ERROR_INT \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_CINFIFO_TOTAL_SIZE_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_CINFIFO_LINES_ERROR_INT \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_CINFIFO_LINES_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_CINFIFO_COLUMNS_ERROR_INT \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_CINFIFO_COLUMNS_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_CINFIFO_STREAM_OVERFLOW_SIG \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_CINFIFO_STREAM_OVERFLOW_SIG)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_COUTFIFO_G3AAB_SIZE_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_COUTFIFO_G3AAB_SIZE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_COUTFIFO_G3AAB_LINE_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_COUTFIFO_G3AAB_LINE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_COUTFIFO_G3AAB_COL_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_COUTFIFO_G3AAB_COL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_COUTFIFO_G3AAB_OVERFLOW_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_COUTFIFO_G3AAB_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_COUTFIFO_G3AAY_SIZE_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_COUTFIFO_G3AAY_SIZE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_COUTFIFO_G3AAY_LINE_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_COUTFIFO_G3AAY_LINE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_COUTFIFO_G3AAY_COL_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_COUTFIFO_G3AAY_COL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX0_COUTFIFO_G3AAY_OVERFLOW_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX0_BASE, \
           PDP_INT_SRC2_CTX0_COUTFIFO_G3AAY_OVERFLOW_ERROR)

#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_COUTFIFO_FRAME_OUT_START_INT \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_COUTFIFO_FRAME_OUT_START_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_VOTF_LOST_FLUSH_IMG \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_VOTF_LOST_FLUSH_IMG)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_VOTF_LOST_FLUSH_AF \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_VOTF_LOST_FLUSH_AF)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_C2SER_SLOW_RING \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_C2SER_SLOW_RING)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_PDAF_STAT_INT \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_PDAF_STAT_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_SBWC_ERR \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_SBWC_ERR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_VOTF_LOSTCON_IMG \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_VOTF_LOSTCON_IMG)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_VOTF_LOSTCON_AF \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_VOTF_LOSTCON_AF)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_COUTFIFO_G3AA_BFRAME_OUT_START_INT \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_COUTFIFO_G3AA_BFRAME_OUT_START_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_COUTFIFO_G3AA_YFRAME_OUT_START_INT \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_COUTFIFO_G3AA_YFRAME_OUT_START_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_COUTFIFO_SIZE_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_COUTFIFO_SIZE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_COUTFIFO_LINE_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_COUTFIFO_LINE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_COUTFIFO_COL_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_COUTFIFO_COL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_COUTFIFO_OVERFLOW_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_COUTFIFO_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_CINFIFO_TOTAL_SIZE_ERROR_INT \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_CINFIFO_TOTAL_SIZE_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_CINFIFO_LINES_ERROR_INT \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_CINFIFO_LINES_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_CINFIFO_COLUMNS_ERROR_INT \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_CINFIFO_COLUMNS_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_CINFIFO_STREAM_OVERFLOW_SIG \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_CINFIFO_STREAM_OVERFLOW_SIG)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_COUTFIFO_G3AAB_SIZE_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_COUTFIFO_G3AAB_SIZE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_COUTFIFO_G3AAB_LINE_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_COUTFIFO_G3AAB_LINE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_COUTFIFO_G3AAB_COL_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_COUTFIFO_G3AAB_COL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_COUTFIFO_G3AAB_OVERFLOW_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_COUTFIFO_G3AAB_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_COUTFIFO_G3AAY_SIZE_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_COUTFIFO_G3AAY_SIZE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_COUTFIFO_G3AAY_LINE_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_COUTFIFO_G3AAY_LINE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_COUTFIFO_G3AAY_COL_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_COUTFIFO_G3AAY_COL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX1_COUTFIFO_G3AAY_OVERFLOW_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX1_BASE, \
           PDP_INT_SRC2_CTX1_COUTFIFO_G3AAY_OVERFLOW_ERROR)

#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_COUTFIFO_FRAME_OUT_START_INT \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_COUTFIFO_FRAME_OUT_START_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_VOTF_LOST_FLUSH_IMG \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_VOTF_LOST_FLUSH_IMG)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_VOTF_LOST_FLUSH_AF \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_VOTF_LOST_FLUSH_AF)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_C2SER_SLOW_RING \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_C2SER_SLOW_RING)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_PDAF_STAT_INT \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_PDAF_STAT_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_SBWC_ERR \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_SBWC_ERR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_VOTF_LOSTCON_IMG \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_VOTF_LOSTCON_IMG)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_VOTF_LOSTCON_AF \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_VOTF_LOSTCON_AF)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_COUTFIFO_G3AA_BFRAME_OUT_START_INT \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_COUTFIFO_G3AA_BFRAME_OUT_START_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_COUTFIFO_G3AA_YFRAME_OUT_START_INT \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_COUTFIFO_G3AA_YFRAME_OUT_START_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_COUTFIFO_SIZE_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_COUTFIFO_SIZE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_COUTFIFO_LINE_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_COUTFIFO_LINE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_COUTFIFO_COL_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_COUTFIFO_COL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_COUTFIFO_OVERFLOW_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_COUTFIFO_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_CINFIFO_TOTAL_SIZE_ERROR_INT \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_CINFIFO_TOTAL_SIZE_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_CINFIFO_LINES_ERROR_INT \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_CINFIFO_LINES_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_CINFIFO_COLUMNS_ERROR_INT \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_CINFIFO_COLUMNS_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_CINFIFO_STREAM_OVERFLOW_SIG \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_CINFIFO_STREAM_OVERFLOW_SIG)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_COUTFIFO_G3AAB_SIZE_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_COUTFIFO_G3AAB_SIZE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_COUTFIFO_G3AAB_LINE_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_COUTFIFO_G3AAB_LINE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_COUTFIFO_G3AAB_COL_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_COUTFIFO_G3AAB_COL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_COUTFIFO_G3AAB_OVERFLOW_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_COUTFIFO_G3AAB_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_COUTFIFO_G3AAY_SIZE_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_COUTFIFO_G3AAY_SIZE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_COUTFIFO_G3AAY_LINE_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_COUTFIFO_G3AAY_LINE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_COUTFIFO_G3AAY_COL_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_COUTFIFO_G3AAY_COL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_PDP_CTX2_COUTFIFO_G3AAY_OVERFLOW_ERROR \
  EVENT_ID(PDP_INT_SRC2_CTX2_BASE, \
           PDP_INT_SRC2_CTX2_COUTFIFO_G3AAY_OVERFLOW_ERROR)



#endif /* DT_BINDINGS_LWIS_PLATFORM_GS101_PDP_H_ */
