/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Google LWIS GS101 SCSC Interrupt And Event Defines
 *
 * Copyright (c) 2020 Google, LLC
 */

#ifndef DT_BINDINGS_LWIS_PLATFORM_GS101_SCSC_H_
#define DT_BINDINGS_LWIS_PLATFORM_GS101_SCSC_H_

#include <dt-bindings/lwis/platform/common.h>

/* clang-format off */
#define SCSC_SCALER_INTERRUPT0_BASE (HW_EVENT_MASK + 0)

#define SCSC_SCALER_INTERRUPT0_FRAME_END_INT 0
#define SCSC_SCALER_INTERRUPT0_FRAME_START_INT 1
#define SCSC_SCALER_INTERRUPT0_WDMA_FINISH_INT 2
#define SCSC_SCALER_INTERRUPT0_CORE_FINISH_INT 3
#define SCSC_SCALER_INTERRUPT0_INPUT_HORIZONTAL_OVF_INT 7
#define SCSC_SCALER_INTERRUPT0_INPUT_HORIZONTAL_UNF_INT 8
#define SCSC_SCALER_INTERRUPT0_INPUT_VERTICAL_OVF_INT 9
#define SCSC_SCALER_INTERRUPT0_INPUT_VERITCAL_UNF_INT 10
#define SCSC_SCALER_INTERRUPT0_SCALER_OVERFLOW_INT 11
#define SCSC_SCALER_INTERRUPT0_INPUT_FRAME_CRUSH_INT 12
#define SCSC_SCALER_INTERRUPT0_SHADOW_COPY_FINISH_INT 16
#define SCSC_SCALER_INTERRUPT0_SHADOW_COPY_FINISH_OVER_INT 17
#define SCSC_SCALER_INTERRUPT0_FM_SUB_FRAME_FINISH_INT 20
#define SCSC_SCALER_INTERRUPT0_FM_SUB_FRAME_START_INT 21
#define SCSC_SCALER_INTERRUPT0_STALL_TIMEOUT_INT 24
#define SCSC_SCALER_INTERRUPT0_COMP_DEC_ERR_INT 25
#define SCSC_SCALER_INTERRUPT0_VOTF_RDMA0_ERR_LOST_INT 27
#define SCSC_SCALER_INTERRUPT0_VOTF_RDMA_SLOW_RING_STATUS_INT 28
#define SCSC_SCALER_INTERRUPT0_VOTF_RDMA_LOST_FLUSH_INT 29

#define SCSC_SECU_INTERRUPT_MUTE_BASE (HW_EVENT_MASK + 32)

#define SCSC_SECU_INTERRUPT_MUTE_SECU_INT_MUTE 0
#define SCSC_SECU_INTERRUPT_MUTE_SECU_INT_UNMUTE 1


/* clang-format on */

#define LWIS_PLATFORM_EVENT_ID_SCSC_FRAME_END_INT \
  EVENT_ID(SCSC_SCALER_INTERRUPT0_BASE, \
	   SCSC_SCALER_INTERRUPT0_FRAME_END_INT)
#define LWIS_PLATFORM_EVENT_ID_SCSC_FRAME_START_INT \
  EVENT_ID(SCSC_SCALER_INTERRUPT0_BASE, \
	   SCSC_SCALER_INTERRUPT0_FRAME_START_INT)
#define LWIS_PLATFORM_EVENT_ID_SCSC_WDMA_FINISH_INT \
  EVENT_ID(SCSC_SCALER_INTERRUPT0_BASE, \
	   SCSC_SCALER_INTERRUPT0_WDMA_FINISH_INT)
#define LWIS_PLATFORM_EVENT_ID_SCSC_CORE_FINISH_INT \
  EVENT_ID(SCSC_SCALER_INTERRUPT0_BASE, \
	   SCSC_SCALER_INTERRUPT0_CORE_FINISH_INT)
#define LWIS_PLATFORM_EVENT_ID_SCSC_INPUT_HORIZONTAL_OVF_INT \
  EVENT_ID(SCSC_SCALER_INTERRUPT0_BASE, \
	   SCSC_SCALER_INTERRUPT0_INPUT_HORIZONTAL_OVF_INT)
#define LWIS_PLATFORM_EVENT_ID_SCSC_INPUT_HORIZONTAL_UNF_INT \
  EVENT_ID(SCSC_SCALER_INTERRUPT0_BASE, \
	   SCSC_SCALER_INTERRUPT0_INPUT_HORIZONTAL_UNF_INT)
#define LWIS_PLATFORM_EVENT_ID_SCSC_INPUT_VERTICAL_OVF_INT \
  EVENT_ID(SCSC_SCALER_INTERRUPT0_BASE, \
	   SCSC_SCALER_INTERRUPT0_INPUT_VERTICAL_OVF_INT)
#define LWIS_PLATFORM_EVENT_ID_SCSC_INPUT_VERITCAL_UNF_INT \
  EVENT_ID(SCSC_SCALER_INTERRUPT0_BASE, \
	   SCSC_SCALER_INTERRUPT0_INPUT_VERITCAL_UNF_INT)
#define LWIS_PLATFORM_EVENT_ID_SCSC_SCALER_OVERFLOW_INT \
  EVENT_ID(SCSC_SCALER_INTERRUPT0_BASE, \
	   SCSC_SCALER_INTERRUPT0_SCALER_OVERFLOW_INT)
#define LWIS_PLATFORM_EVENT_ID_SCSC_INPUT_FRAME_CRUSH_INT \
  EVENT_ID(SCSC_SCALER_INTERRUPT0_BASE, \
	   SCSC_SCALER_INTERRUPT0_INPUT_FRAME_CRUSH_INT)
#define LWIS_PLATFORM_EVENT_ID_SCSC_SHADOW_COPY_FINISH_INT \
  EVENT_ID(SCSC_SCALER_INTERRUPT0_BASE, \
	   SCSC_SCALER_INTERRUPT0_SHADOW_COPY_FINISH_INT)
#define LWIS_PLATFORM_EVENT_ID_SCSC_SHADOW_COPY_FINISH_OVER_INT \
  EVENT_ID(SCSC_SCALER_INTERRUPT0_BASE, \
	   SCSC_SCALER_INTERRUPT0_SHADOW_COPY_FINISH_OVER_INT)
#define LWIS_PLATFORM_EVENT_ID_SCSC_FM_SUB_FRAME_FINISH_INT \
  EVENT_ID(SCSC_SCALER_INTERRUPT0_BASE, \
	   SCSC_SCALER_INTERRUPT0_FM_SUB_FRAME_FINISH_INT)
#define LWIS_PLATFORM_EVENT_ID_SCSC_FM_SUB_FRAME_START_INT \
  EVENT_ID(SCSC_SCALER_INTERRUPT0_BASE, \
	   SCSC_SCALER_INTERRUPT0_FM_SUB_FRAME_START_INT)
#define LWIS_PLATFORM_EVENT_ID_SCSC_STALL_TIMEOUT_INT \
  EVENT_ID(SCSC_SCALER_INTERRUPT0_BASE, \
	   SCSC_SCALER_INTERRUPT0_STALL_TIMEOUT_INT)
#define LWIS_PLATFORM_EVENT_ID_SCSC_COMP_DEC_ERR_INT \
  EVENT_ID(SCSC_SCALER_INTERRUPT0_BASE, \
	   SCSC_SCALER_INTERRUPT0_COMP_DEC_ERR_INT)
#define LWIS_PLATFORM_EVENT_ID_SCSC_VOTF_RDMA0_ERR_LOST_INT \
  EVENT_ID(SCSC_SCALER_INTERRUPT0_BASE, \
	   SCSC_SCALER_INTERRUPT0_VOTF_RDMA0_ERR_LOST_INT)
#define LWIS_PLATFORM_EVENT_ID_SCSC_VOTF_RDMA_SLOW_RING_STATUS_INT \
  EVENT_ID(SCSC_SCALER_INTERRUPT0_BASE, \
	   SCSC_SCALER_INTERRUPT0_VOTF_RDMA_SLOW_RING_STATUS_INT)
#define LWIS_PLATFORM_EVENT_ID_SCSC_VOTF_RDMA_LOST_FLUSH_INT \
  EVENT_ID(SCSC_SCALER_INTERRUPT0_BASE, \
	   SCSC_SCALER_INTERRUPT0_VOTF_RDMA_LOST_FLUSH_INT)

#define LWIS_PLATFORM_EVENT_ID_SCSC_SECU_INT_MUTE \
  EVENT_ID(SCSC_SECU_INTERRUPT_MUTE_BASE, \
	   SCSC_SECU_INTERRUPT_MUTE_SECU_INT_MUTE)
#define LWIS_PLATFORM_EVENT_ID_SCSC_SECU_INT_UNMUTE \
  EVENT_ID(SCSC_SECU_INTERRUPT_MUTE_BASE, \
	   SCSC_SECU_INTERRUPT_MUTE_SECU_INT_UNMUTE)




#endif /* DT_BINDINGS_LWIS_PLATFORM_GS101_SCSC_H_ */
