# SPDX-License-Identifier: GPL-2.0-only

# Kbuild doesn't recognize that we want overlays, since there aren't any in
# this directory. But we're going to build and apply those from other trees, so
# force __symbols__ generation.
DTC_FLAGS += -@

dtb-y += gs201-a0.dtb
dtb-y += gs201-b0.dtb
dtb-y += gs201-b0_v2-ipop.dtb
