/* SPDX-License-Identifier: GPL-2.0 */

#ifndef DEBUG_SNAPSHOT_DEF_H
#define DEBUG_SNAPSHOT_DEF_H

#define SZ_64K			0x00010000
#define SZ_512K			0x00080000
#define SZ_1M			0x00100000

/* Size parameters */
#define DSS_CORE_NUM		9
#define DSS_SYSREG_PER_CORE_SZ	SZ_512
#define DSS_COREREG_PER_CORE_SZ	SZ_512

/* DSS regions */
#define DSS_HEADER_SIZE			SZ_64K
#define DSS_LOG_KEVENTS_SIZE		(7 * SZ_1M)
#define DSS_LOG_S2D_SIZE		(24 * SZ_1M)
#define DSS_LOG_ARRAYRESET_SIZE		(10 * SZ_1M)
#define DSS_LOG_ARRAYPANIC_SIZE		(10 * SZ_1M)
#define DSS_LOG_SLCDUMP_SIZE		(17 * SZ_1M)
#define DSS_LOG_BCM_SIZE		(4 * SZ_1M)
#define DSS_LOG_ITMON_SIZE		SZ_64K
#define DSS_LOG_S2D_EXTRACT_SIZE	(6 * SZ_1M)

#define DSS_START_ADDR			0xD8100000
#define DSS_HEADER_ADDR			DSS_START_ADDR
#define DSS_LOG_KEVENTS_ADDR		(DSS_HEADER_ADDR + DSS_HEADER_SIZE)
#define DSS_LOG_S2D_ADDR		(DSS_LOG_KEVENTS_ADDR + DSS_LOG_KEVENTS_SIZE)
#define DSS_LOG_ARRAYRESET_ADDR		(DSS_LOG_S2D_ADDR + DSS_LOG_S2D_SIZE)
#define DSS_LOG_ARRAYPANIC_ADDR		(DSS_LOG_ARRAYRESET_ADDR + DSS_LOG_ARRAYRESET_SIZE)
#define DSS_LOG_SLCDUMP_ADDR		(DSS_LOG_ARRAYPANIC_ADDR + DSS_LOG_ARRAYPANIC_SIZE)
#define DSS_LOG_PRE_SLCDUMP_ADDR	(DSS_LOG_SLCDUMP_ADDR + DSS_LOG_SLCDUMP_SIZE)
#define DSS_LOG_BCM_ADDR		(DSS_LOG_PRE_SLCDUMP_ADDR + DSS_LOG_SLCDUMP_SIZE)
#define DSS_LOG_ITMON_ADDR		(DSS_LOG_BCM_ADDR + DSS_LOG_BCM_SIZE)
#define DSS_LOG_S2D_EXTRACT_ADDR	(DSS_LOG_ITMON_ADDR + DSS_LOG_ITMON_SIZE)

/* DSS Header contents */
#define DSS_HDR_INFO_BLOCK_SZ		SZ_4K
#define DSS_HDR_SYSREG_SZ		(DSS_SYSREG_PER_CORE_SZ * DSS_CORE_NUM)
#define DSS_HDR_COREREG_SZ		(DSS_COREREG_PER_CORE_SZ * DSS_CORE_NUM)
#define DSS_HDR_APM_COREREG_SZ		SZ_256
#define DSS_HDR_DBGC_VERSION_SZ		48
#define DSS_HDR_DBGC_SRAM_LOG_SZ	(SZ_4K + SZ_1K)
#define DSS_HDR_DBGC_REGDUMP_SZ		SZ_256
#define DSS_HDR_DPM_NS_SZ		SZ_8K
#define DSS_HDR_SJTAG_EXCHG_BUFF_SZ	SZ_256
#define DSS_HDR_DBGC_DRAM_LOG_SZ	(15 * SZ_1K)
#define DSS_HDR_DBGC_MBOX_DUMP_SZ	SZ_256
#define DSS_HDR_DBGC_STATE_DUMP_SZ	SZ_512
#define DSS_HDR_PCSR_SZ			SZ_512

#define DSS_HDR_INFO_BLOCK_KEEP_SZ	(SZ_256 * 3)

#define DSS_HDR_INFO_BLOCK_OFFS		0
#define DSS_HDR_SYSREG_OFFS		(DSS_HDR_INFO_BLOCK_OFFS + DSS_HDR_INFO_BLOCK_SZ)
#define DSS_HDR_COREREG_OFFS		(DSS_HDR_SYSREG_OFFS + DSS_HDR_SYSREG_SZ)
#define DSS_HDR_APM_COREREG_OFFS	(DSS_HDR_COREREG_OFFS + DSS_HDR_COREREG_SZ)
#define DSS_HDR_DBGC_VERSION_OFFS	(DSS_HDR_APM_COREREG_OFFS + DSS_HDR_APM_COREREG_SZ)
#define DSS_HDR_DBGC_SRAM_LOG_OFFS	(DSS_HDR_DBGC_VERSION_OFFS + DSS_HDR_DBGC_VERSION_SZ)
#define DSS_HDR_DBGC_REGDUMP_OFFS	(DSS_HDR_DBGC_SRAM_LOG_OFFS + DSS_HDR_DBGC_SRAM_LOG_SZ)
#define DSS_HDR_DPM_NS_OFFS		0x4F00
#define DSS_HDR_SJTAG_EXCHG_BUFF_OFFS	(DSS_HDR_DPM_NS_OFFS + DSS_HDR_DPM_NS_SZ)
#define DSS_HDR_DBGC_DRAM_LOG_OFFS	(DSS_HDR_SJTAG_EXCHG_BUFF_OFFS + \
							DSS_HDR_SJTAG_EXCHG_BUFF_SZ)
#define DSS_HDR_DBGC_MBOX_DUMP_OFFS	(DSS_HDR_DBGC_DRAM_LOG_OFFS + DSS_HDR_DBGC_DRAM_LOG_SZ)
#define DSS_HDR_DBGC_STATE_DUMP_OFFS	(DSS_HDR_DBGC_MBOX_DUMP_OFFS + DSS_HDR_DBGC_MBOX_DUMP_SZ)
#define DSS_HDR_PCSR_OFFS		0xB000

/*  DSS Header Info Block contents */
#define DSS_OFFSET_SCRATCH		(0x100)
#define DSS_OFFSET_NONE_DPM_DUMP_MODE	(0x108)
#define DSS_OFFSET_DEBUG_TEST_BUFFER(n)	(0x190 + (0x8 * n))
#define DSS_OFFSET_SLCDUMP_MAGIC	(0x270)
#define DSS_OFFSET_SLCDUMP_STATUS	(0x274)
#define DSS_OFFSET_SLCDUMP_BASE_REG	(0x278)
#define DSS_OFFSET_PRE_SLCDUMP_BASE_REG	(0x27C)
#define DSS_OFFSET_PMIC_REG_INT_MAGIC	(0x280)
#define DSS_OFFSET_PMIC_REG_INT_1	(0x284)
#define DSS_OFFSET_PMIC_REG_INT_2	(0x285)
#define DSS_OFFSET_PMIC_REG_INT_3	(0x286)
#define DSS_OFFSET_PMIC_REG_INT_4	(0x287)
#define DSS_OFFSET_PMIC_REG_INT_5	(0x288)
#define DSS_OFFSET_PMIC_REG_INT_6	(0x289)
#define DSS_OFFSET_PMIC_REASON		(0x290)
#define DSS_OFFSET_PMIC_REG_INT_1_S	(0x294)
#define DSS_OFFSET_PMIC_REG_INT_2_S	(0x295)
#define DSS_OFFSET_PMIC_REG_INT_3_S	(0x296)
#define DSS_OFFSET_PMIC_REG_INT_4_S	(0x297)
#define DSS_OFFSET_PMIC_REG_INT_5_S	(0x298)
#define DSS_OFFSET_SUB_PMIC_REASON	(0x2A0)
#define DSS_OFFSET_BL31_LOG_BUF_RSVD_STAT	(0x2A4)
#define DSS_OFFSET_BL31_PSCI_CRUMBS	(0x2A8)
#define DSS_OFFSET_PBL_LOG_BUF_RSVD_STAT	(0x2BC)
#define DSS_OFFSET_MEM_PROTECT_REASON	(0x2C0)
#define DSS_OFFSET_ABL_DUMP_STAT	(0x2C8)
#define DSS_OFFSET_BL31_DUMP_RSVD_STAT	(0x2D0)
#define DSS_OFFSET_EMERGENCY_REASON	(0x300)
#define DSS_OFFSET_WDT_CALLER		(0x310)
#define DSS_OFFSET_DUMP_GPR_WAIT	(0x380)
#define DSS_OFFSET_WAKEUP_WAIT		(0x390)
#define DSS_OFFSET_CORE_POWER_STAT	(0x400)
#define DSS_OFFSET_CORE_PMU_VAL		(0x440)
#define DSS_OFFSET_CORE_EHLD_STAT	(0x480)
#define DSS_OFFSET_GPR_POWER_STAT	(0x4C0)
#define DSS_OFFSET_PANIC_STAT		(0x500)
#define DSS_OFFSET_CFLUSH_STAT		(0x524)
#define DSS_OFFSET_CORE_LAST_PC		(0x600)
#define DSS_OFFSET_QD_ENTRY		(0x660)
#define DSS_OFFSET_PANIC_STRING		(0xC00)

#define DSS_PANIC_STRING_SZ		SZ_1K


/* KEVENT ID */
#define DSS_ITEM_HEADER		"header"
#define DSS_ITEM_KEVENTS	"log_kevents"
#define DSS_ITEM_S2D		"log_s2d"
#define DSS_ITEM_ARRDUMP_RESET	"log_array_reset"
#define DSS_ITEM_ARRDUMP_PANIC	"log_array_panic"
#define DSS_ITEM_SLCDUMP	"log_slcdump"
#define DSS_ITEM_PRE_SLCDUMP	"log_preslcdump"
#define DSS_ITEM_BCM		"log_bcm"
#define DSS_ITEM_ITMON		"log_itmon"

#define DSS_LOG_TASK		"task_log"
#define DSS_LOG_WORK		"work_log"
#define DSS_LOG_CPUIDLE		"cpuidle_log"
#define DSS_LOG_SUSPEND		"suspend_log"
#define DSS_LOG_IRQ		"irq_log"
#define DSS_LOG_HRTIMER		"hrtimer_log"
#define DSS_LOG_CLK		"clk_log"
#define DSS_LOG_PMU		"pmu_log"
#define DSS_LOG_FREQ		"freq_log"
#define DSS_LOG_DM		"dm_log"
#define DSS_LOG_REGULATOR	"regulator_log"
#define DSS_LOG_THERMAL		"thermal_log"
#define DSS_LOG_ACPM		"acpm_log"
#define DSS_LOG_PRINTK		"printk_log"

/* MODE */
#define NONE_DUMP		0
#define FULL_DUMP		1
#define QUICK_DUMP		2

/* ACTION */
#define GO_DEFAULT		"default"
#define GO_DEFAULT_ID		0
#define GO_PANIC		"panic"
#define GO_PANIC_ID		1
#define GO_WATCHDOG		"watchdog"
#define GO_WATCHDOG_ID		2
#define GO_S2D			"s2d"
#define GO_S2D_ID		3
#define GO_ARRAYDUMP		"arraydump"
#define GO_ARRAYDUMP_ID		4
#define GO_SCANDUMP		"scandump"
#define GO_SCANDUMP_ID		5
#define GO_HALT			"halt"
#define GO_HALT_ID		6
#define GO_ACTION_MAX		7

/* EXCEPTION POLICY */
#define DPM_F			"feature"
#define DPM_P			"policy"

#define DPM_P_EL1_DA		"el1_da"
#define DPM_P_EL1_IA		"el1_ia"
#define DPM_P_EL1_UNDEF		"el1_undef"
#define DPM_P_EL1_SP_PC		"el1_sp_pc"
#define DPM_P_EL1_INV		"el1_inv"
#define DPM_P_EL1_SERROR	"el1_serror"

/* Enable by DPM */
#define DPM_ENABLE			1
/* Enable by Privileged Debug */
#define PRIVILEGED_ENABLE		2
#endif
