# SPDX-License-Identifier: GPL-2.0
#
# Makefile for USB Host Controller Drivers
#

ccflags-y			+= -I$(srctree)/drivers/usb

obj-$(CONFIG_USB_XHCI_EXYNOS)	+= xhci-exynos.o
obj-$(CONFIG_USB_XHCI_GOOG_DMA)	+= xhci-goog-dma.o
