# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(srctree)/$(src)/../cal_common

obj-$(CONFIG_DRM_PANEL_GOOGLE_COMMON)		+= panel-common.o
obj-$(CONFIG_DRM_PANEL_SAMSUNG_COMMON)		+= panel-samsung-drv.o
obj-$(CONFIG_DRM_PANEL_SAMSUNG_EMUL)		+= panel-samsung-emul.o
obj-$(CONFIG_DRM_PANEL_SAMSUNG_S6E3HC2)		+= panel-samsung-s6e3hc2.o
obj-$(CONFIG_DRM_PANEL_SAMSUNG_S6E3FC3)		+= panel-samsung-s6e3fc3.o
obj-$(CONFIG_DRM_PANEL_SAMSUNG_S6E3FC3_P10)		+= panel-samsung-s6e3fc3-p10.o
obj-$(CONFIG_DRM_PANEL_SAMSUNG_SOFEF01)		+= panel-samsung-sofef01.o
obj-$(CONFIG_DRM_PANEL_SAMSUNG_S6E3HC3)		+= panel-samsung-s6e3hc3.o
obj-$(CONFIG_DRM_PANEL_SAMSUNG_S6E3HC3_C10)		+= panel-samsung-s6e3hc3-c10.o
obj-$(CONFIG_DRM_PANEL_SAMSUNG_S6E3HC4)		+= panel-samsung-s6e3hc4.o
obj-$(CONFIG_DRM_PANEL_BOE_NT37290)		+= panel-boe-nt37290.o

