obj-$(CONFIG_VIDEO_EXYNOS_MFC) := exynos_mfc.o
exynos_mfc-y += mfc_perf_measure.o
exynos_mfc-y += mfc_dec_ctrl.o mfc_enc_ctrl.o
exynos_mfc-y += mfc_debugfs.o mfc_core_otf.o
exynos_mfc-y += mfc_llc.o
exynos_mfc-y += mfc_meminfo.o
exynos_mfc-y += mfc_memlog.o mfc_sysevent.o
#Dev interface layer
exynos_mfc-y += mfc.o mfc_dec_v4l2.o mfc_dec_vb2.o mfc_enc_v4l2.o mfc_enc_vb2.o
#Dev control layer
exynos_mfc-y += mfc_rm.o mfc_meerkat.o mfc_sync.o mfc_qos.o
#Core interface layer
exynos_mfc-y += mfc_core.o mfc_core_ops.o mfc_core_nal_q.o mfc_core_isr.o
#Core control layer
exynos_mfc-y += mfc_core_hwlock.o mfc_core_intlock.o mfc_core_pm.o mfc_core_qos.o
exynos_mfc-y += mfc_core_run.o mfc_core_meerkat.o
#Core HW access layer
exynos_mfc-y += mfc_core_enc_param.o mfc_core_cmd.o
exynos_mfc-y += mfc_core_hw_reg_api.o mfc_core_reg_api.o
#Common base layer
exynos_mfc-y += mfc_queue.o mfc_buf.o mfc_utils.o mfc_mem.o
