#
# Makefile for ACPM.
#
obj-$(CONFIG_GS_ACPM)			+= gs_acpm.o
gs_acpm-$(CONFIG_GS_ACPM)		+= acpm.o acpm_ipc.o
gs_acpm-$(CONFIG_GS_ACPM_MFD)		+= acpm_mfd.o
gs_acpm-$(CONFIG_GS_FLEXPMU_DBG)	+= acpm_flexpmu_dbg.o
