#
# Makefile for ACPM.
#
obj-$(CONFIG_GS_ACPM)		+= gs_acpm.o
gs_acpm-$(CONFIG_GS_ACPM)	+= acpm.o acpm_ipc.o
gs_acpm-$(CONFIG_ACPM_MFD)	+= acpm_mfd.o
obj-$(CONFIG_ACPM_FLEXPMU_DBG)	+= acpm_flexpmu_dbg.o
obj-$(CONFIG_ACPM_POWER_STATS)	+= power_stats.o
obj-$(CONFIG_ACPM_MBOX_TEST)	+= acpm_mbox_test.o
