# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the kernel USB device drivers.
#

obj-$(CONFIG_USB_DWC3)		+= dwc3/
obj-$(CONFIG_USB_XHCI_HCD)	+= host/
obj-$(CONFIG_USB_GADGET)	+= gadget/
obj-$(CONFIG_TYPEC)		+= typec/
