// SPDX-License-Identifier: GPL-2.0-only
/*
 * Common Clock Framework support for GS101 SoC.
 *
 * Copyright (c) 2019 Google LLC
 */

#include <linux/clk.h>
#include <linux/clkdev.h>
#include <linux/clk-provider.h>
#include <linux/module.h>
#include <linux/of_platform.h>
#include <linux/of.h>
#include <linux/of_address.h>
#include <soc/google/cal-if.h>
#include <dt-bindings/clock/gs101.h>

#include "../../soc/google/cal-if/gs101/cmucal-vclk.h"
#include "../../soc/google/cal-if/gs101/cmucal-node.h"
#include "../../soc/google/cal-if/gs101/cmucal-qch.h"
#include "../../soc/google/cal-if/gs101/clkout_gs101.h"
#include "composite.h"

static struct samsung_clk_provider *gs101_clk_provider;
/*
 * list of controller registers to be saved and restored during a
 * suspend/resume cycle.
 */
/* fixed rate clocks generated outside the soc */
struct samsung_fixed_rate gs101_fixed_rate_ext_clks[] = {
	FRATE(OSCCLK,
		"fin_pll",
		NULL,
		0,
		24576000),
};

/* HWACG VCLK */
struct init_vclk gs101_apm_hwacg_vclks[] = {
	HWACG_VCLK(MUX_APM_FUNCSRC,
		MUX_CLKCMU_APM_FUNCSRC,
		"MUX_APM_FUNCSRC",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(MUX_APM_FUNC,
		MUX_CLKCMU_APM_FUNC,
		"MUX_APM_FUNC",
		NULL,
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_top_hwacg_vclks[] = {
	HWACG_VCLK(GATE_DFTMUX_CMU_CIS_CLK0,
		DFTMUX_CMU_QCH_CIS_CLK0,
		"GATE_DFTMUX_CMU_CIS_CLK0",
		NULL,
		0,
		VCLK_GATE | VCLK_QCH_DIS,
		NULL),
	HWACG_VCLK(GATE_DFTMUX_CMU_CIS_CLK1,
		DFTMUX_CMU_QCH_CIS_CLK1,
		"GATE_DFTMUX_CMU_CIS_CLK1",
		NULL,
		0,
		VCLK_GATE | VCLK_QCH_DIS,
		NULL),
	HWACG_VCLK(GATE_DFTMUX_CMU_CIS_CLK2,
		DFTMUX_CMU_QCH_CIS_CLK2,
		"GATE_DFTMUX_CMU_CIS_CLK2",
		NULL,
		0,
		VCLK_GATE | VCLK_QCH_DIS,
		NULL),
	HWACG_VCLK(GATE_DFTMUX_CMU_CIS_CLK3,
		DFTMUX_CMU_QCH_CIS_CLK3,
		"GATE_DFTMUX_CMU_CIS_CLK3",
		NULL,
		0,
		VCLK_GATE | VCLK_QCH_DIS,
		NULL),
	HWACG_VCLK(GATE_DFTMUX_CMU_CIS_CLK4,
		DFTMUX_CMU_QCH_CIS_CLK4,
		"GATE_DFTMUX_CMU_CIS_CLK4",
		NULL,
		0,
		VCLK_GATE | VCLK_QCH_DIS,
		NULL),
	HWACG_VCLK(GATE_DFTMUX_CMU_CIS_CLK5,
		DFTMUX_CMU_QCH_CIS_CLK5,
		"GATE_DFTMUX_CMU_CIS_CLK5",
		NULL,
		0,
		VCLK_GATE | VCLK_QCH_DIS,
		NULL),
	HWACG_VCLK(GATE_DFTMUX_CMU_CIS_CLK6,
		DFTMUX_CMU_QCH_CIS_CLK6,
		"GATE_DFTMUX_CMU_CIS_CLK6",
		NULL,
		0,
		VCLK_GATE | VCLK_QCH_DIS,
		NULL),
	HWACG_VCLK(GATE_DFTMUX_CMU_CIS_CLK7,
		DFTMUX_CMU_QCH_CIS_CLK7,
		"GATE_DFTMUX_CMU_CIS_CLK7",
		NULL,
		0,
		VCLK_GATE | VCLK_QCH_DIS,
		NULL),
};

struct init_vclk gs101_bus0_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_BUS0_BUS,
		MUX_CLKCMU_BUS0_BUS_USER,
		"UMUX_CLKCMU_BUS0_BUS",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(MUX_BUS0_BUS_OPTION1,
		MUX_CLK_BUS0_BUS_OPTION1,
		"MUX_BUS0_BUS_OPTION1",
		NULL,
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_bus1_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_BUS1_BUS,
		MUX_CLKCMU_BUS1_BUS_USER,
		"UMUX_CLKCMU_BUS1_BUS",
		NULL,
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_bus2_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_BUS2_BUS,
		MUX_CLKCMU_BUS2_BUS_USER,
		"UMUX_CLKCMU_BUS2_BUS",
		NULL,
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_core_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_CORE_BUS,
		MUX_CLKCMU_CORE_BUS_USER,
		"UMUX_CLKCMU_CORE_BUS",
		NULL,
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_eh_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_EH_BUS,
		MUX_CLKCMU_EH_BUS_USER,
		"UMUX_CLKCMU_EH_BUS",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(UMUX_CLKCMU_EH_PLL_CORE,
		UMUX_CLKCMU_EH_PLL_CORE,
		"UMUX_CLKCMU_EH_PLL_CORE",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(MUX_EH_BUS,
		MUX_CLK_EH_BUS,
		"MUX_EH_BUS",
		NULL,
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_g3d_hwacg_vclks[] = {
	HWACG_VCLK(GATE_GPU,
		GPU_QCH,
		"GATE_GPU",
		NULL,
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_dpu_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_DPU_BUS,
		MUX_CLKCMU_DPU_BUS_USER,
		"UMUX_CLKCMU_DPU_BUS",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_DPUF_DMA,
		DPUF_QCH_DPU_DMA,
		"GATE_DPUF_DMA",
		"UMUX_CLKCMU_DPU_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_DPUF_DPP,
		DPUF_QCH_DPU_DPP,
		"GATE_DPUF_DPP",
		"UMUX_CLKCMU_DPU_BUS",
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_disp_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_DISP_BUS,
		MUX_CLKCMU_DISP_BUS_USER,
		"UMUX_CLKCMU_DISP_BUS",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_DPUB,
		DPUB_QCH,
		"GATE_DPUB",
		"UMUX_CLKCMU_DISP_BUS",
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_g2d_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_G2D_G2D,
		MUX_CLKCMU_G2D_G2D_USER,
		"UMUX_CLKCMU_G2D_G2D",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(UMUX_CLKCMU_G2D_MSCL,
		MUX_CLKCMU_G2D_MSCL_USER,
		"UMUX_CLKCMU_G2D_MSCL",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_G2D,
		G2D_QCH,
		"GATE_G2D",
		"UMUX_CLKCMU_G2D_G2D",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_JPEG,
		JPEG_QCH,
		"GATE_JPEG",
		"UMUX_CLKCMU_G2D_MSCL",
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_hsi0_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_HSI0_TCXO,
		MUX_CLKCMU_HSI0_TCXO_USER,
		"UMUX_CLKCMU_HSI0_TCXO",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(MUX_HSI0_USB20_REF,
		MUX_CLK_HSI0_USB20_REF,
		"MUX_HSI0_USB20_REF",
		NULL,
		0,
		0,
		NULL),
	HWACG_VCLK(UMUX_CLKCMU_HSI0_USB31DRD,
		MUX_CLKCMU_HSI0_USB31DRD_USER,
		"UMUX_CLKCMU_HSI0_USB31DRD",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(UMUX_CLKCMU_HSI0_USB20,
		MUX_CLKCMU_HSI0_USB20_USER,
		"UMUX_CLKCMU_HSI0_USB20",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(MUX_HSI0_USB31DRD,
		MUX_CLK_HSI0_USB31DRD,
		"MUX_HSI0_USB31DRD",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(UMUX_CLKCMU_HSI0_BUS,
		MUX_CLKCMU_HSI0_BUS_USER,
		"UMUX_CLKCMU_HSI0_BUS",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(UMUX_CLKCMU_HSI0_ALT,
		MUX_CLKCMU_HSI0_ALT_USER,
		"UMUX_CLKCMU_HSI0_ALT",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(MUX_HSI0_BUS,
		MUX_CLK_HSI0_BUS,
		"MUX_HSI0_BUS",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(UMUX_CLKCMU_HSI0_DPGTC,
		MUX_CLKCMU_HSI0_DPGTC_USER,
		"UMUX_CLKCMU_HSI0_DPGTC",
		NULL,
		0,
		VCLK_GATE,
		NULL),

	HWACG_VCLK(GATE_USB31DRD_SLV_LINK,
		USB31DRD_QCH_SLV_LINK,
		"GATE_USB31DRD_SLV_LINK",
		"MUX_HSI0_USB31DRD",
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_hsi1_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_HSI1_BUS,
		MUX_CLKCMU_HSI1_BUS_USER,
		"UMUX_CLKCMU_HSI1_BUS",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(UMUX_CLKCMU_HSI1_PCIE,
		MUX_CLKCMU_HSI1_PCIE_USER,
		"UMUX_CLKCMU_HSI1_PCIE",
		NULL,
		0,
		VCLK_GATE,
		NULL),

	HWACG_VCLK(GATE_PCIE_GEN4_0_DBG_1,
		PCIE_GEN4_0_QCH_DBG_1,
		"GATE_PCIE_GEN4_0_DBG_1",
		"UMUX_CLKCMU_HSI1_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_0_AXI_1,
		PCIE_GEN4_0_QCH_AXI_1,
		"GATE_PCIE_GEN4_0_AXI_1",
		"UMUX_CLKCMU_HSI1_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_0_APB_1,
		PCIE_GEN4_0_QCH_APB_1,
		"GATE_PCIE_GEN4_0_APB_1",
		"UMUX_CLKCMU_HSI1_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_0_SCLK_1,
		PCIE_GEN4_0_QCH_SCLK_1,
		"GATE_PCIE_GEN4_0_SCLK_1",
		"UMUX_CLKCMU_HSI1_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_0_PCS_APB,
		PCIE_GEN4_0_QCH_PCS_APB,
		"GATE_PCIE_GEN4_0_PCS_APB",
		"UMUX_CLKCMU_HSI1_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_0_PMA_APB,
		PCIE_GEN4_0_QCH_PMA_APB,
		"GATE_PCIE_GEN4_0_PMA_APB",
		"UMUX_CLKCMU_HSI1_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_0_DBG_2,
		PCIE_GEN4_0_QCH_DBG_2,
		"GATE_PCIE_GEN4_0_DBG_2",
		"UMUX_CLKCMU_HSI1_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_0_AXI_2,
		PCIE_GEN4_0_QCH_AXI_2,
		"GATE_PCIE_GEN4_0_AXI_2",
		"UMUX_CLKCMU_HSI1_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_0_APB_2,
		PCIE_GEN4_0_QCH_APB_2,
		"GATE_PCIE_GEN4_0_APB_2",
		"UMUX_CLKCMU_HSI1_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_0_UDBG,
		PCIE_GEN4_0_QCH_UDBG,
		"GATE_PCIE_GEN4_0_UDBG",
		"UMUX_CLKCMU_HSI1_BUS",
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_hsi2_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_HSI2_BUS,
		MUX_CLKCMU_HSI2_BUS_USER,
		"UMUX_CLKCMU_HSI2_BUS",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(UMUX_CLKCMU_HSI2_PCIE,
		MUX_CLKCMU_HSI2_PCIE_USER,
		"UMUX_CLKCMU_HSI2_PCIE",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(UMUX_CLKCMU_HSI2_UFS_EMBD,
		MUX_CLKCMU_HSI2_UFS_EMBD_USER,
		"UMUX_CLKCMU_HSI2_UFS_EMBD",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(UMUX_CLKCMU_HSI2_MMC_CARD,
		MUX_CLKCMU_HSI2_MMC_CARD_USER,
		"UMUX_CLKCMU_HSI2_MMC_CARD",
		NULL,
		0,
		VCLK_GATE,
		NULL),

	HWACG_VCLK(GATE_MMC_CARD,
		MMC_CARD_QCH,
		"GATE_MMC_CARD",
		"UMUX_CLKCMU_HSI2_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_1_AXI_1,
		PCIE_GEN4_1_QCH_AXI_1,
		"GATE_PCIE_GEN4_1_AXI_1",
		"UMUX_CLKCMU_HSI2_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_1_APB_1,
		PCIE_GEN4_1_QCH_APB_1,
		"GATE_PCIE_GEN4_1_APB_1",
		"UMUX_CLKCMU_HSI2_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_1_DBG_1,
		PCIE_GEN4_1_QCH_DBG_1,
		"GATE_PCIE_GEN4_1_DBG_1",
		"UMUX_CLKCMU_HSI2_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_1_PCS_APB,
		PCIE_GEN4_1_QCH_PCS_APB,
		"GATE_PCIE_GEN4_1_PCS_APB",
		"UMUX_CLKCMU_HSI2_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_1_SCLK_1,
		PCIE_GEN4_1_QCH_SCLK_1,
		"GATE_PCIE_GEN4_1_SCLK_1",
		"UMUX_CLKCMU_HSI2_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_1_PMA_APB,
		PCIE_GEN4_1_QCH_PMA_APB,
		"GATE_PCIE_GEN4_1_PMA_APB",
		"UMUX_CLKCMU_HSI2_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_1_AXI_2,
		PCIE_GEN4_1_QCH_AXI_2,
		"GATE_PCIE_GEN4_1_AXI_2",
		"UMUX_CLKCMU_HSI2_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_1_DBG_2,
		PCIE_GEN4_1_QCH_DBG_2,
		"GATE_PCIE_GEN4_1_DBG_2",
		"UMUX_CLKCMU_HSI2_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_1_APB_2,
		PCIE_GEN4_1_QCH_APB_2,
		"GATE_PCIE_GEN4_1_APB_2",
		"UMUX_CLKCMU_HSI2_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_1_UDBG,
		PCIE_GEN4_1_QCH_UDBG,
		"GATE_PCIE_GEN4_1_UDBG",
		"UMUX_CLKCMU_HSI2_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_UFS_EMBD,
		UFS_EMBD_QCH,
		"GATE_UFS_EMBD",
		"UMUX_CLKCMU_HSI2_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_UFS_EMBD_FMP,
		UFS_EMBD_QCH_FMP,
		"GATE_UFS_EMBD_FMP",
		"UMUX_CLKCMU_HSI2_BUS",
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_csis_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_CSIS_BUS,
		MUX_CLKCMU_CSIS_BUS_USER,
		"UMUX_CLKCMU_CSIS_BUS",
		NULL,
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_pdp_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_PDP_BUS,
		MUX_CLKCMU_PDP_BUS_USER,
		"UMUX_CLKCMU_PDP_BUS",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(UMUX_CLKCMU_PDP_VRA,
		MUX_CLKCMU_PDP_VRA_USER,
		"UMUX_CLKCMU_PDP_VRA",
		NULL,
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_ipp_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_IPP_BUS,
		MUX_CLKCMU_IPP_BUS_USER,
		"UMUX_CLKCMU_IPP_BUS",
		NULL,
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_g3aa_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_G3AA_G3AA,
		MUX_CLKCMU_G3AA_G3AA_USER,
		"UMUX_CLKCMU_G3AA_G3AA",
		NULL,
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_itp_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_ITP_BUS,
		MUX_CLKCMU_ITP_BUS_USER,
		"UMUX_CLKCMU_ITP_BUS",
		NULL,
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_dns_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_DNS_BUS,
		MUX_CLKCMU_DNS_BUS_USER,
		"UMUX_CLKCMU_DNS_BUS",
		NULL,
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_tnr_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_TNR_BUS,
		MUX_CLKCMU_TNR_BUS_USER,
		"UMUX_CLKCMU_TNR_BUS",
		NULL,
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_mcsc_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_MCSC_ITSC,
		MUX_CLKCMU_MCSC_ITSC_USER,
		"UMUX_CLKCMU_MCSC_ITSC",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(UMUX_CLKCMU_MCSC_MCSC,
		MUX_CLKCMU_MCSC_MCSC_USER,
		"UMUX_CLKCMU_MCSC_MCSC",
		NULL,
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_gdc_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_GDC_SCSC,
		MUX_CLKCMU_GDC_SCSC_USER,
		"UMUX_CLKCMU_GDC_SCSC",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(UMUX_CLKCMU_GDC_GDC0,
		MUX_CLKCMU_GDC_GDC0_USER,
		"UMUX_CLKCMU_GDC_GDC0",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(UMUX_CLKCMU_GDC_GDC1,
		MUX_CLKCMU_GDC_GDC1_USER,
		"UMUX_CLKCMU_GDC_GDC1",
		NULL,
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_mfc_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_MFC_MFC,
		MUX_CLKCMU_MFC_MFC_USER,
		"UMUX_CLKCMU_MFC_MFC",
		NULL,
		0,
		0,
		NULL),
	HWACG_VCLK(GATE_MFC,
		MFC_QCH,
		"GATE_MFC",
		"UMUX_CLKCMU_MFC_MFC",
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_mif_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_MIF_DDRPHY2X,
		CLKMUX_MIF_DDRPHY2X,
		"UMUX_MIF_DDRPHY2X",
		NULL,
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_misc_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_MISC_BUS,
		MUX_CLKCMU_MISC_BUS_USER,
		"UMUX_CLKCMU_MISC_BUS",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(UMUX_CLKCMU_MISC_SSS,
		MUX_CLKCMU_MISC_SSS_USER,
		"UMUX_CLKCMU_MISC_SSS",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_MCT,
		MCT_QCH,
		"GATE_MCT",
		"DOUT_CLK_MISC_BUSP",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_WDT_CL0,
		WDT_CLUSTER0_QCH,
		"GATE_WDT_CL0",
			"DOUT_CLK_MISC_BUSP",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_WDT_CL1,
		WDT_CLUSTER1_QCH,
		"GATE_WDT_CL1",
			"DOUT_CLK_MISC_BUSP",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PDMA,
		PDMA_QCH,
		"GATE_PDMA",
			"DOUT_CLK_MISC_BUSP",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK_QACTIVE(ATCLK,
		"ATCLK",
		"DOUT_CLK_MISC_BUSP",
		0,
		VCLK_QACTIVE,
		NULL,
		0x2500c02c,
		0x1,
		0x1),
};

struct init_vclk gs101_peric0_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_PERIC0_BUS,
		MUX_CLKCMU_PERIC0_BUS_USER,
		"UMUX_CLKCMU_PERIC0_BUS",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(UMUX_CLKCMU_PERIC0_USI0_UART,
		MUX_CLKCMU_PERIC0_USI0_UART_USER,
		"UMUX_CLKCMU_PERIC0_USI0_UART",
		NULL,
		0,
		VCLK_GATE,
		NULL),

	HWACG_VCLK(GATE_PERIC0_TOP0_USI1_USI,
		PERIC0_TOP0_QCH_USI1_USI,
		"GATE_PERIC0_TOP0_USI1_USI",
		"UMUX_CLKCMU_PERIC0_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_USI2_USI,
		PERIC0_TOP0_QCH_USI2_USI,
		"GATE_PERIC0_TOP0_USI2_USI",
		"UMUX_CLKCMU_PERIC0_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_USI3_USI,
		PERIC0_TOP0_QCH_USI3_USI,
		"GATE_PERIC0_TOP0_USI3_USI",
		"UMUX_CLKCMU_PERIC0_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_USI4_USI,
		PERIC0_TOP0_QCH_USI4_USI,
		"GATE_PERIC0_TOP0_USI4_USI",
		"UMUX_CLKCMU_PERIC0_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_USI5_USI,
		PERIC0_TOP0_QCH_USI5_USI,
		"GATE_PERIC0_TOP0_USI5_USI",
		"UMUX_CLKCMU_PERIC0_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_USI6_USI,
		PERIC0_TOP0_QCH_USI6_USI,
		"GATE_PERIC0_TOP0_USI6_USI",
		"UMUX_CLKCMU_PERIC0_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_USI7_USI,
		PERIC0_TOP0_QCH_USI7_USI,
		"GATE_PERIC0_TOP0_USI7_USI",
		"UMUX_CLKCMU_PERIC0_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_USI8_USI,
		PERIC0_TOP0_QCH_USI8_USI,
		"GATE_PERIC0_TOP0_USI8_USI",
		"UMUX_CLKCMU_PERIC0_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_I3C1,
		PERIC0_TOP0_QCH_I3C1,
		"GATE_PERIC0_TOP0_I3C1",
		"UMUX_CLKCMU_PERIC0_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_I3C2,
		PERIC0_TOP0_QCH_I3C2,
		"GATE_PERIC0_TOP0_I3C2",
		"UMUX_CLKCMU_PERIC0_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_I3C3,
		PERIC0_TOP0_QCH_I3C3,
		"GATE_PERIC0_TOP0_I3C3",
		"UMUX_CLKCMU_PERIC0_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_I3C4,
		PERIC0_TOP0_QCH_I3C4,
		"GATE_PERIC0_TOP0_I3C4",
		"UMUX_CLKCMU_PERIC0_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_I3C5,
		PERIC0_TOP0_QCH_I3C5,
		"GATE_PERIC0_TOP0_I3C5",
		"UMUX_CLKCMU_PERIC0_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_I3C6,
		PERIC0_TOP0_QCH_I3C6,
		"GATE_PERIC0_TOP0_I3C6",
		"UMUX_CLKCMU_PERIC0_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_I3C7,
		PERIC0_TOP0_QCH_I3C7,
		"GATE_PERIC0_TOP0_I3C7",
		"UMUX_CLKCMU_PERIC0_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_I3C8,
		PERIC0_TOP0_QCH_I3C8,
		"GATE_PERIC0_TOP0_I3C8",
		"UMUX_CLKCMU_PERIC0_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_S1,
		PERIC0_TOP0_QCH_S1,
		"GATE_PERIC0_TOP0_S1",
		"UMUX_CLKCMU_PERIC0_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_S2,
		PERIC0_TOP0_QCH_S2,
		"GATE_PERIC0_TOP0_S2",
		"UMUX_CLKCMU_PERIC0_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_S3,
		PERIC0_TOP0_QCH_S3,
		"GATE_PERIC0_TOP0_S3",
		"UMUX_CLKCMU_PERIC0_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_S4,
		PERIC0_TOP0_QCH_S4,
		"GATE_PERIC0_TOP0_S4",
		"UMUX_CLKCMU_PERIC0_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_S5,
		PERIC0_TOP0_QCH_S5,
		"GATE_PERIC0_TOP0_S5",
		"UMUX_CLKCMU_PERIC0_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_S6,
		PERIC0_TOP0_QCH_S6,
		"GATE_PERIC0_TOP0_S6",
		"UMUX_CLKCMU_PERIC0_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_S7,
		PERIC0_TOP0_QCH_S7,
		"GATE_PERIC0_TOP0_S7",
		"UMUX_CLKCMU_PERIC0_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_S8,
		PERIC0_TOP0_QCH_S8,
		"GATE_PERIC0_TOP0_S8",
		"UMUX_CLKCMU_PERIC0_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC0_TOP1_USI0_UART,
		PERIC0_TOP1_QCH_USI0_UART,
		"GATE_PERIC0_TOP1_USI0_UART",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC0_TOP1_USI14_USI,
		PERIC0_TOP1_QCH_USI14_USI,
		"GATE_PERIC0_TOP1_USI14_USI",
		"UMUX_CLKCMU_PERIC0_BUS",
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_peric1_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_PERIC1_BUS,
		MUX_CLKCMU_PERIC1_BUS_USER,
		"UMUX_CLKCMU_PERIC1_BUS",
		NULL,
		0,
		VCLK_GATE,
		NULL),

	HWACG_VCLK(GATE_PERIC1_TOP0_USI0_USI,
		PERIC1_TOP0_QCH_USI0_USI,
		"GATE_PERIC1_TOP0_USI0_USI",
		"UMUX_CLKCMU_PERIC1_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC1_TOP0_USI9_USI,
		PERIC1_TOP0_QCH_USI9_USI,
		"GATE_PERIC1_TOP0_USI9_USI",
		"UMUX_CLKCMU_PERIC1_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC1_TOP0_USI10_USI,
		PERIC1_TOP0_QCH_USI10_USI,
		"GATE_PERIC1_TOP0_USI10_USI",
		"UMUX_CLKCMU_PERIC1_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC1_TOP0_USI11_USI,
		PERIC1_TOP0_QCH_USI11_USI,
		"GATE_PERIC1_TOP0_USI11_USI",
		"UMUX_CLKCMU_PERIC1_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC1_TOP0_USI12_USI,
		PERIC1_TOP0_QCH_USI12_USI,
		"GATE_PERIC1_TOP0_USI12_USI",
		"UMUX_CLKCMU_PERIC1_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC1_TOP0_USI13_USI,
		PERIC1_TOP0_QCH_USI13_USI,
		"GATE_PERIC1_TOP0_USI13_USI",
		"UMUX_CLKCMU_PERIC1_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC1_TOP0_I3C0,
		PERIC1_TOP0_QCH_I3C0,
		"GATE_PERIC1_TOP0_I3C0",
		"UMUX_CLKCMU_PERIC1_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC1_TOP0_PWM,
		PERIC1_TOP0_QCH_PWM,
		"GATE_PERIC1_TOP0_PWM",
		"UMUX_CLKCMU_PERIC1_BUS",
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(GATE_PERIC1_TOP0_S,
		PERIC1_TOP0_QCH_S,
		"GATE_PERIC1_TOP0_S",
		"UMUX_CLKCMU_PERIC1_BUS",
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_tpu_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_TPU_TPU,
		MUX_CLKCMU_TPU_TPU_USER,
		"UMUX_CLKCMU_TPU_TPU",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(UMUX_CLKCMU_TPU_TPUCTL,
		MUX_CLKCMU_TPU_TPUCTL_USER,
		"UMUX_CLKCMU_TPU_TPUCTL",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(UMUX_CLKCMU_TPU_BUS,
		MUX_CLKCMU_TPU_BUS_USER,
		"UMUX_CLKCMU_TPU_BUS",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(UMUX_CLKCMU_TPU_UART,
		MUX_CLKCMU_TPU_UART_USER,
		"UMUX_CLKCMU_TPU_UART",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(MUX_TPU_TPU,
		MUX_CLK_TPU_TPU,
		"MUX_TPU_TPU",
		NULL,
		0,
		VCLK_GATE,
		NULL),
	HWACG_VCLK(MUX_TPU_TPUCTL,
		MUX_CLK_TPU_TPUCTL,
		"MUX_TPU_TPUCTL",
		NULL,
		0,
		VCLK_GATE,
		NULL),
};

struct init_vclk gs101_bo_hwacg_vclks[] = {
	HWACG_VCLK(UMUX_CLKCMU_BO_BUS,
		MUX_CLKCMU_BO_BUS_USER,
		"UMUX_CLKCMU_BO_BUS",
		NULL,
		0,
		VCLK_GATE,
		NULL),
};



/* Special VCLK */
struct init_vclk gs101_apm_vclks[] = {
	VCLK(DOUT_CLK_APM_BOOST,
		DIV_CLK_APM_BOOST,
		"DOUT_CLK_APM_BOOST",
		0,
		0,
		NULL),
	VCLK(DOUT_CLK_APM_USI0_UART,
		DIV_CLK_APM_USI0_UART,
		"DOUT_CLK_APM_USI0_UART",
		0,
		0,
		NULL),
	VCLK(DOUT_CLK_APM_USI1_UART,
		DIV_CLK_APM_USI1_UART,
		"DOUT_CLK_APM_USI1_UART",
		0,
		0,
		NULL),
	VCLK(DOUT_CLK_APM_USI0_USI,
		DIV_CLK_APM_USI0_USI,
		"DOUT_CLK_APM_USI0_USI",
		0,
		0,
		NULL),
};

struct init_vclk gs101_bus0_vclks[] = {
	VCLK(DOUT_CLK_BUS0_BUSP,
		DIV_CLK_BUS0_BUSP,
		"DOUT_CLK_BUS0_BUSP",
		0,
		0,
		NULL),
};

struct init_vclk gs101_bus1_vclks[] = {
	VCLK(DOUT_CLK_BUS1_BUSP,
		DIV_CLK_BUS1_BUSP,
		"DOUT_CLK_BUS1_BUSP",
		0,
		0,
		NULL),
};

struct init_vclk gs101_bus2_vclks[] = {
	VCLK(DOUT_CLK_BUS2_BUSP,
		DIV_CLK_BUS2_BUSP,
		"DOUT_CLK_BUS2_BUSP",
		0,
		0,
		NULL),
};

struct init_vclk gs101_eh_vclks[] = {
	VCLK(DOUT_CLK_EH_BUSP,
		DIV_CLK_EH_BUSP,
		"DOUT_CLK_EH_BUSP",
		0,
		0,
		NULL),
};

struct init_vclk gs101_dpu_vclks[] = {
	VCLK(DOUT_CLK_DPU_BUSP,
		DIV_CLK_DPU_BUSP,
		"DOUT_CLK_DPU_BUSP",
		0,
		0,
		NULL),
};

struct init_vclk gs101_disp_vclks[] = {
	VCLK(DOUT_CLK_DISP_BUSP,
		DIV_CLK_DISP_BUSP,
		"DOUT_CLK_DISP_BUSP",
		0,
		0,
		NULL),
};

struct init_vclk gs101_g2d_vclks[] = {
	VCLK(DOUT_CLK_G2D_BUSP,
		DIV_CLK_G2D_BUSP,
		"DOUT_CLK_G2D_BUSP",
		0,
		0,
		NULL),
};

struct init_vclk gs101_hsi0_vclks[] = {
	VCLK(DOUT_CLK_HSI0_USB31DRD,
		DIV_CLK_HSI0_USB31DRD,
		"DOUT_CLK_HSI0_USB31DRD",
		0,
		0,
		NULL),
};

struct init_vclk gs101_csis_vclks[] = {
	VCLK(DOUT_CLK_CSIS_BUSP,
		DIV_CLK_CSIS_BUSP,
		"DOUT_CLK_CSIS_BUSP",
		0,
		0,
		NULL),
};

struct init_vclk gs101_pdp_vclks[] = {
	VCLK(DOUT_CLK_PDP_BUSP,
		DIV_CLK_PDP_BUSP,
		"DOUT_CLK_PDP_BUSP",
		0,
		0,
		NULL),
};

struct init_vclk gs101_ipp_vclks[] = {
	VCLK(DOUT_CLK_IPP_BUSP,
		DIV_CLK_IPP_BUSP,
		"DOUT_CLK_IPP_BUSP",
		0,
		0,
		NULL),
};

struct init_vclk gs101_g3aa_vclks[] = {
	VCLK(DOUT_CLK_G3AA_BUSP,
		DIV_CLK_G3AA_BUSP,
		"DOUT_CLK_G3AA_BUSP",
		0,
		0,
		NULL),
};

struct init_vclk gs101_itp_vclks[] = {
	VCLK(DOUT_CLK_ITP_BUSP,
		DIV_CLK_ITP_BUSP,
		"DOUT_CLK_ITP_BUSP",
		0,
		0,
		NULL),
};

struct init_vclk gs101_dns_vclks[] = {
	VCLK(DOUT_CLK_DNS_BUSP,
		DIV_CLK_DNS_BUSP,
		"DOUT_CLK_DNS_BUSP",
		0,
		0,
		NULL),
};

struct init_vclk gs101_tnr_vclks[] = {
	VCLK(DOUT_CLK_TNR_BUSP,
		DIV_CLK_TNR_BUSP,
		"DOUT_CLK_TNR_BUSP",
		0,
		0,
		NULL),
};

struct init_vclk gs101_mcsc_vclks[] = {
	VCLK(DOUT_CLK_MCSC_BUSP,
		DIV_CLK_MCSC_BUSP,
		"DOUT_CLK_MCSC_BUSP",
		0,
		0,
		NULL),
};

struct init_vclk gs101_gdc_vclks[] = {
	VCLK(DOUT_CLK_GDC_BUSP,
		DIV_CLK_GDC_BUSP,
		"DOUT_CLK_GDC_BUSP",
		0,
		0,
		NULL),
};

struct init_vclk gs101_mfc_vclks[] = {
	VCLK(DOUT_CLK_MFC_BUSP,
		DIV_CLK_MFC_BUSP,
		"DOUT_CLK_MFC_BUSP",
		0,
		0,
		NULL),
};

struct init_vclk gs101_misc_vclks[] = {
	VCLK(DOUT_CLK_MISC_BUSP,
		DIV_CLK_MISC_BUSP,
		"DOUT_CLK_MISC_BUSP",
		0,
		0,
		NULL),
};

struct init_vclk gs101_top_vclks[] = {
	VCLK(VDOUT_CLK_TOP_HSI0_BUS,
		VCLK_DIV_CLK_TOP_HSI0_BUS,
		"VDOUT_CLK_TOP_HSI0_BUS",
		0,
		0,
		NULL),
	VCLK(CIS_CLK0,
		CLKCMU_CIS_CLK0,
		"CIS_CLK0",
		0,
		0,
		NULL),
	VCLK(CIS_CLK1,
		CLKCMU_CIS_CLK1,
		"CIS_CLK1",
		0,
		0,
		NULL),
	VCLK(CIS_CLK2,
		CLKCMU_CIS_CLK2,
		"CIS_CLK2",
		0,
		0,
		NULL),
	VCLK(CIS_CLK3,
		CLKCMU_CIS_CLK3,
		"CIS_CLK3",
		0,
		0,
		NULL),
	VCLK(CIS_CLK4,
		CLKCMU_CIS_CLK4,
		"CIS_CLK4",
		0,
		0,
		NULL),
	VCLK(CIS_CLK5,
		CLKCMU_CIS_CLK5,
		"CIS_CLK5",
		0,
		0,
		NULL),
	VCLK(CIS_CLK6,
		CLKCMU_CIS_CLK6,
		"CIS_CLK6",
		0,
		0,
		NULL),
	VCLK(CIS_CLK7,
		CLKCMU_CIS_CLK7,
		"CIS_CLK7",
		0,
		0,
		NULL),
};

struct init_vclk gs101_hsi2_vclks[] = {
	VCLK(DOUT_CLKCMU_HSI2_MMC_CARD,
		CLKCMU_HSI2_MMC_CARD,
		"DOUT_CLKCMU_HSI2_MMC_CARD",
		0,
		0,
		NULL),
	VCLK(UFS_EMBD,
		CLKCMU_HSI2_UFS_EMBD,
		"UFS_EMBD",
		0,
		0,
		NULL),
};

struct init_vclk gs101_peric0_vclks[] = {
	VCLK(VDOUT_CLK_PERIC0_USI0_UART,
		VCLK_DIV_CLK_PERIC0_USI0_UART,
		"VDOUT_CLK_PERIC0_USI0_UART",
		0,
		0,
		NULL),
	VCLK(VDOUT_CLK_PERIC0_USI1_USI,
		VCLK_DIV_CLK_PERIC0_USI1_USI,
		"VDOUT_CLK_PERIC0_USI1_USI",
		0,
		0,
		NULL),
	VCLK(VDOUT_CLK_PERIC0_USI2_USI,
		VCLK_DIV_CLK_PERIC0_USI2_USI,
		"VDOUT_CLK_PERIC0_USI2_USI",
		0,
		0,
		NULL),
	VCLK(VDOUT_CLK_PERIC0_USI3_USI,
		VCLK_DIV_CLK_PERIC0_USI3_USI,
		"VDOUT_CLK_PERIC0_USI3_USI",
		0,
		0,
		NULL),
	VCLK(VDOUT_CLK_PERIC0_USI4_USI,
		VCLK_DIV_CLK_PERIC0_USI4_USI,
		"VDOUT_CLK_PERIC0_USI4_USI",
		0,
		0,
		NULL),
	VCLK(VDOUT_CLK_PERIC0_USI5_USI,
		VCLK_DIV_CLK_PERIC0_USI5_USI,
		"VDOUT_CLK_PERIC0_USI5_USI",
		0,
		0,
		NULL),
	VCLK(VDOUT_CLK_PERIC0_USI6_USI,
		VCLK_DIV_CLK_PERIC0_USI6_USI,
		"VDOUT_CLK_PERIC0_USI6_USI",
		0,
		0,
		NULL),
	VCLK(VDOUT_CLK_PERIC0_USI7_USI,
		VCLK_DIV_CLK_PERIC0_USI7_USI,
		"VDOUT_CLK_PERIC0_USI7_USI",
		0,
		0,
		NULL),
	VCLK(VDOUT_CLK_PERIC0_USI8_USI,
		VCLK_DIV_CLK_PERIC0_USI8_USI,
		"VDOUT_CLK_PERIC0_USI8_USI",
		0,
		0,
		NULL),
	VCLK(VDOUT_CLK_PERIC0_USI14_USI,
		VCLK_DIV_CLK_PERIC0_USI14_USI,
		"VDOUT_CLK_PERIC0_USI14_USI",
		0,
		0,
		NULL),
	VCLK(VDOUT_CLK_PERIC0_I3C,
		VCLK_DIV_CLK_PERIC0_I3C,
		"VDOUT_CLK_PERIC0_I3C",
		0,
		0,
		NULL),
};

struct init_vclk gs101_peric1_vclks[] = {
	VCLK(VDOUT_CLK_PERIC1_USI0_USI,
		VCLK_DIV_CLK_PERIC1_USI0_USI,
		"VDOUT_CLK_PERIC1_USI0_USI",
		0,
		0,
		NULL),
	VCLK(VDOUT_CLK_PERIC1_USI9_USI,
		VCLK_DIV_CLK_PERIC1_USI9_USI,
		"VDOUT_CLK_PERIC1_USI9_USI",
		0,
		0,
		NULL),
	VCLK(VDOUT_CLK_PERIC1_USI10_USI,
		VCLK_DIV_CLK_PERIC1_USI10_USI,
		"VDOUT_CLK_PERIC1_USI10_USI",
		0,
		0,
		NULL),
	VCLK(VDOUT_CLK_PERIC1_USI11_USI,
		VCLK_DIV_CLK_PERIC1_USI11_USI,
		"VDOUT_CLK_PERIC1_USI11_USI",
		0,
		0,
		NULL),
	VCLK(VDOUT_CLK_PERIC1_USI12_USI,
		VCLK_DIV_CLK_PERIC1_USI12_USI,
		"VDOUT_CLK_PERIC1_USI12_USI",
		0,
		0,
		NULL),
	VCLK(VDOUT_CLK_PERIC1_USI13_USI,
		VCLK_DIV_CLK_PERIC1_USI13_USI,
		"VDOUT_CLK_PERIC1_USI13_USI",
		0,
		0,
		NULL),
	VCLK(VDOUT_CLK_PERIC1_I3C,
		VCLK_DIV_CLK_PERIC1_I3C,
		"VDOUT_CLK_PERIC1_I3C",
		0,
		0,
		NULL),
};

struct init_vclk gs101_tpu_vclks[] = {
	VCLK(DOUT_CLK_TPU_TPU,
		DIV_CLK_TPU_TPU,
		"DOUT_CLK_TPU_TPU",
		0,
		0,
		NULL),
	VCLK(DOUT_CLK_TPU_TPUCTL,
		DIV_CLK_TPU_TPUCTL,
		"DOUT_CLK_TPU_TPUCTL",
		0,
		0,
		NULL),
	VCLK(DOUT_CLK_TPU_BUSP,
		DIV_CLK_TPU_BUSP,
		"DOUT_CLK_TPU_BUSP",
		0,
		0,
		NULL),
};

struct init_vclk gs101_bo_vclks[] = {
	VCLK(DOUT_CLK_BO_BUSP,
		DIV_CLK_BO_BUSP,
		"DOUT_CLK_BO_BUSP",
		0,
		0,
		NULL),
};

static struct init_vclk gs101_clkout_vclks[] = {
	VCLK(CLKOUT1,
		VCLK_CLKOUT1,
		"CLKOUT1",
		0,
		0,
		NULL),
	VCLK(CLKOUT0,
		VCLK_CLKOUT0,
		"CLKOUT0",
		0,
		0,
		NULL),
};

static const struct of_device_id ext_clk_match[] = {
	{.compatible = "samsung,gs101-oscclk", .data = (void *)0},
	{},
};

void gs101_vclk_init(void)
{
	/* Common clock init */
}

/* register gs101 clocks */
static int gs101_clock_probe(struct platform_device *pdev)
{
	struct device_node *np = pdev->dev.of_node;
	void __iomem *reg_base;

	if (np) {
		reg_base = of_iomap(np, 0);
		if (!reg_base)
			panic("%s: failed to map registers\n", __func__);
	} else {
		panic("%s: unable to determine soc\n", __func__);
	}

	gs101_clk_provider = samsung_clk_init(np, reg_base, CLK_NR_CLKS);
	if (!gs101_clk_provider)
		panic("%s: unable to allocate context.\n", __func__);

	samsung_register_of_fixed_ext(gs101_clk_provider,
					gs101_fixed_rate_ext_clks,
					ARRAY_SIZE(gs101_fixed_rate_ext_clks),
					ext_clk_match);

	/* register HWACG vclk */
	samsung_register_vclk(gs101_clk_provider,
				gs101_apm_hwacg_vclks,
				ARRAY_SIZE(gs101_apm_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_top_hwacg_vclks,
				ARRAY_SIZE(gs101_top_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_bus0_hwacg_vclks,
				ARRAY_SIZE(gs101_bus0_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_bus1_hwacg_vclks,
				ARRAY_SIZE(gs101_bus1_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_bus2_hwacg_vclks,
				ARRAY_SIZE(gs101_bus2_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_core_hwacg_vclks,
				ARRAY_SIZE(gs101_core_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_eh_hwacg_vclks,
				ARRAY_SIZE(gs101_eh_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_g3d_hwacg_vclks,
				ARRAY_SIZE(gs101_g3d_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_dpu_hwacg_vclks,
				ARRAY_SIZE(gs101_dpu_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_disp_hwacg_vclks,
				ARRAY_SIZE(gs101_disp_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_g2d_hwacg_vclks,
				ARRAY_SIZE(gs101_g2d_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_hsi0_hwacg_vclks,
				ARRAY_SIZE(gs101_hsi0_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_hsi1_hwacg_vclks,
				ARRAY_SIZE(gs101_hsi1_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_hsi2_hwacg_vclks,
				ARRAY_SIZE(gs101_hsi2_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_csis_hwacg_vclks,
				ARRAY_SIZE(gs101_csis_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_pdp_hwacg_vclks,
				ARRAY_SIZE(gs101_pdp_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_ipp_hwacg_vclks,
				ARRAY_SIZE(gs101_ipp_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_g3aa_hwacg_vclks,
				ARRAY_SIZE(gs101_g3aa_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_itp_hwacg_vclks,
				ARRAY_SIZE(gs101_itp_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_dns_hwacg_vclks,
				ARRAY_SIZE(gs101_dns_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_tnr_hwacg_vclks,
				ARRAY_SIZE(gs101_tnr_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_mcsc_hwacg_vclks,
				ARRAY_SIZE(gs101_mcsc_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_gdc_hwacg_vclks,
				ARRAY_SIZE(gs101_gdc_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_mfc_hwacg_vclks,
				ARRAY_SIZE(gs101_mfc_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_mif_hwacg_vclks,
				ARRAY_SIZE(gs101_mif_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_misc_hwacg_vclks,
				ARRAY_SIZE(gs101_misc_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_peric0_hwacg_vclks,
				ARRAY_SIZE(gs101_peric0_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_peric1_hwacg_vclks,
				ARRAY_SIZE(gs101_peric1_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_tpu_hwacg_vclks,
				ARRAY_SIZE(gs101_tpu_hwacg_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_bo_hwacg_vclks,
				ARRAY_SIZE(gs101_bo_hwacg_vclks));

	/* register special vclk */
	samsung_register_vclk(gs101_clk_provider,
				gs101_apm_vclks,
				ARRAY_SIZE(gs101_apm_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_bus0_vclks,
				ARRAY_SIZE(gs101_bus0_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_bus1_vclks,
				ARRAY_SIZE(gs101_bus1_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_bus2_vclks,
				ARRAY_SIZE(gs101_bus2_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_eh_vclks,
				ARRAY_SIZE(gs101_eh_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_dpu_vclks,
				ARRAY_SIZE(gs101_dpu_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_disp_vclks,
				ARRAY_SIZE(gs101_disp_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_g2d_vclks,
				ARRAY_SIZE(gs101_g2d_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_hsi0_vclks,
				ARRAY_SIZE(gs101_hsi0_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_csis_vclks,
				ARRAY_SIZE(gs101_csis_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_pdp_vclks,
				ARRAY_SIZE(gs101_pdp_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_ipp_vclks,
				ARRAY_SIZE(gs101_ipp_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_g3aa_vclks,
				ARRAY_SIZE(gs101_g3aa_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_itp_vclks,
				ARRAY_SIZE(gs101_itp_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_dns_vclks,
				ARRAY_SIZE(gs101_dns_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_tnr_vclks,
				ARRAY_SIZE(gs101_tnr_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_mcsc_vclks,
				ARRAY_SIZE(gs101_mcsc_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_gdc_vclks,
				ARRAY_SIZE(gs101_gdc_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_mfc_vclks,
				ARRAY_SIZE(gs101_mfc_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_misc_vclks,
				ARRAY_SIZE(gs101_misc_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_top_vclks,
				ARRAY_SIZE(gs101_top_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_hsi2_vclks,
				ARRAY_SIZE(gs101_hsi2_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_peric0_vclks,
				ARRAY_SIZE(gs101_peric0_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_peric1_vclks,
				ARRAY_SIZE(gs101_peric1_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_tpu_vclks,
				ARRAY_SIZE(gs101_tpu_vclks));
	samsung_register_vclk(gs101_clk_provider,
				gs101_bo_vclks,
				ARRAY_SIZE(gs101_bo_vclks));

	samsung_register_vclk(gs101_clk_provider,
				gs101_clkout_vclks,
				ARRAY_SIZE(gs101_clkout_vclks));

	clk_register_fixed_factor(NULL,
				"pwm-clock",
				"fin_pll",
				CLK_SET_RATE_PARENT,
				1,
				1);

	samsung_clk_of_add_provider(np, gs101_clk_provider);

	gs101_vclk_init();

	pr_info("GS101: Clock setup completed\n");

	return 0;
}

static const struct of_device_id of_exynos_clock_match[] = {
	{ .compatible = "samsung,gs101-clock", },
	{ },
};
MODULE_DEVICE_TABLE(of, of_exynos_clock_match);

static const struct platform_device_id exynos_clock_ids[] = {
	{ "gs101-clock", },
	{ }
};

static struct platform_driver gs101_clock_driver = {
	.driver = {
		.name = "gs101_clock",
		.of_match_table = of_exynos_clock_match,
	},
	.probe		= gs101_clock_probe,
	.id_table	= exynos_clock_ids,
};

static int gs101_clock_init(void)
{
	return platform_driver_register(&gs101_clock_driver);
}
arch_initcall(gs101_clock_init);

static void gs101_clock_exit(void)
{
	return platform_driver_unregister(&gs101_clock_driver);
}
module_exit(gs101_clock_exit);

MODULE_LICENSE("GPL");
