/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Google LWIS ZUMA GDC Interrupt And Event Defines
 *
 * Copyright (c) 2022 Google, LLC
 */

#ifndef DT_BINDINGS_LWIS_PLATFORM_ZUMA_GDC_H_
#define DT_BINDINGS_LWIS_PLATFORM_ZUMA_GDC_H_

#include <dt-bindings/lwis/platform/common.h>

/* clang-format off */

#define GDC_INT0_BASE (HW_EVENT_MASK + 0)

#define GDC_INT0_FRAME_START 0
#define GDC_INT0_FRAME_END 1
#define GDC_INT0_CMDQ_HOLD 2
#define GDC_INT0_SETTING_DONE 3
#define GDC_INT0_C_LOADER_END 4
#define GDC_INT0_COREX_END0 5
#define GDC_INT0_COREX_END1 6
#define GDC_INT0_ROW_COL 7
#define GDC_INT0_FREEZE_ON_ROW_COL 8
#define GDC_INT0_TRANS_STOP_DONE 9
#define GDC_INT0_CMDQ_ERROR 10
#define GDC_INT0_C_LOADER_ERROR 11
#define GDC_INT0_COREX_ERROR 12
#define GDC_INT0_CINFIFO0_OVERFLOW_ERROR 13
#define GDC_INT0_CINFIFO0_OVERLAP_ERROR 14
#define GDC_INT0_CINFIFO0_PIXEL_CNT_ERROR 15
#define GDC_INT0_CINFIFO0_INPUT_PROTOCOL_ERROR 16
#define GDC_INT0_CINFIFO1_OVERFLOW_ERROR 17
#define GDC_INT0_CINFIFO1_OVERLAP_ERROR 18
#define GDC_INT0_CINFIFO1_PIXEL_CNT_ERROR 19
#define GDC_INT0_CINFIFO1_INPUT_PROTOCOL_ERROR 20
#define GDC_INT0_COUTFIFO0_PIXEL_CNT_ERROR 21
#define GDC_INT0_COUTFIFO0_INPUT_PROTOCOL_ERROR 22
#define GDC_INT0_COUTFIFO0_OVERFLOW_ERROR 23
#define GDC_INT0_COUTFIFO1_PIXEL_CNT_ERROR 24
#define GDC_INT0_COUTFIFO1_INPUT_PROTOCOL_ERROR 25
#define GDC_INT0_COUTFIFO1_OVERFLOW_ERROR 26
#define GDC_INT0_VOTF_GLOBAL_ERROR 27
#define GDC_INT0_VOTF_LOST_CONNECTION 28
#define GDC_INT0_OTF_SEQ_ID_ERROR 29

#define GDC_INT1_BASE (HW_EVENT_MASK + 32)

#define GDC_INT1_VOTF_LOST_FLUSH 0

#define GDC_CMDQ_INT_BASE (HW_EVENT_MASK + 64)

#define GDC_CMDQ_INT_STOP_CRPT_OFF_CMDQ_EN 0
#define GDC_CMDQ_INT_PRELOAD_FLUSH 1
#define GDC_CMDQ_INT_QUE0_OVERFLOW 2
#define GDC_CMDQ_INT_QUE1_OVERFLOW 3
#define GDC_CMDQ_INT_QUE_U_OVERFLOW 4
#define GDC_CMDQ_INT_QUE0_PUSH_BACK_TO_FULL_QUE 5
#define GDC_CMDQ_INT_QUE1_PUSH_BACK_TO_FULL_QUE 6
#define GDC_CMDQ_INT_QUE_U_PUSH_BACK_TO_FULL_QUE 7

/* clang-format on */

#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_FRAME_START \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_FRAME_START)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_FRAME_END \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_FRAME_END)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_CMDQ_HOLD \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_CMDQ_HOLD)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_SETTING_DONE \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_SETTING_DONE)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_C_LOADER_END \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_C_LOADER_END)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_COREX_END0 \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_COREX_END0)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_COREX_END1 \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_COREX_END1)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_ROW_COL \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_ROW_COL)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_FREEZE_ON_ROW_COL \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_FREEZE_ON_ROW_COL)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_TRANS_STOP_DONE \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_TRANS_STOP_DONE)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_CMDQ_ERROR \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_CMDQ_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_C_LOADER_ERROR \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_C_LOADER_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_COREX_ERROR \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_COREX_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_CINFIFO0_OVERFLOW_ERROR \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_CINFIFO0_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_CINFIFO0_OVERLAP_ERROR \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_CINFIFO0_OVERLAP_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_CINFIFO0_PIXEL_CNT_ERROR \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_CINFIFO0_PIXEL_CNT_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_CINFIFO0_INPUT_PROTOCOL_ERROR \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_CINFIFO0_INPUT_PROTOCOL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_CINFIFO1_OVERFLOW_ERROR \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_CINFIFO1_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_CINFIFO1_OVERLAP_ERROR \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_CINFIFO1_OVERLAP_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_CINFIFO1_PIXEL_CNT_ERROR \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_CINFIFO1_PIXEL_CNT_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_CINFIFO1_INPUT_PROTOCOL_ERROR \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_CINFIFO1_INPUT_PROTOCOL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_COUTFIFO0_PIXEL_CNT_ERROR \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_COUTFIFO0_PIXEL_CNT_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_COUTFIFO0_INPUT_PROTOCOL_ERROR \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_COUTFIFO0_INPUT_PROTOCOL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_COUTFIFO0_OVERFLOW_ERROR \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_COUTFIFO0_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_COUTFIFO1_PIXEL_CNT_ERROR \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_COUTFIFO1_PIXEL_CNT_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_COUTFIFO1_INPUT_PROTOCOL_ERROR \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_COUTFIFO1_INPUT_PROTOCOL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_COUTFIFO1_OVERFLOW_ERROR \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_COUTFIFO1_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_VOTF_GLOBAL_ERROR \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_VOTF_GLOBAL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_VOTF_LOST_CONNECTION \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_VOTF_LOST_CONNECTION)
#define LWIS_PLATFORM_EVENT_ID_GDC_INT0_OTF_SEQ_ID_ERROR \
	EVENT_ID(GDC_INT0_BASE, \
		 GDC_INT0_OTF_SEQ_ID_ERROR)

#define LWIS_PLATFORM_EVENT_ID_GDC_INT1_VOTF_LOST_FLUSH \
	EVENT_ID(GDC_INT1_BASE, \
		 GDC_INT1_VOTF_LOST_FLUSH)

#define LWIS_PLATFORM_EVENT_ID_GDC_CMDQ_INT_STOP_CRPT_OFF_CMDQ_EN \
	EVENT_ID(GDC_CMDQ_INT_BASE, \
		 GDC_CMDQ_INT_STOP_CRPT_OFF_CMDQ_EN)
#define LWIS_PLATFORM_EVENT_ID_GDC_CMDQ_INT_PRELOAD_FLUSH \
	EVENT_ID(GDC_CMDQ_INT_BASE, \
		 GDC_CMDQ_INT_PRELOAD_FLUSH)
#define LWIS_PLATFORM_EVENT_ID_GDC_CMDQ_INT_QUE0_OVERFLOW \
	EVENT_ID(GDC_CMDQ_INT_BASE, \
		 GDC_CMDQ_INT_QUE0_OVERFLOW)
#define LWIS_PLATFORM_EVENT_ID_GDC_CMDQ_INT_QUE1_OVERFLOW \
	EVENT_ID(GDC_CMDQ_INT_BASE, \
		 GDC_CMDQ_INT_QUE1_OVERFLOW)
#define LWIS_PLATFORM_EVENT_ID_GDC_CMDQ_INT_QUE_U_OVERFLOW \
	EVENT_ID(GDC_CMDQ_INT_BASE, \
		 GDC_CMDQ_INT_QUE_U_OVERFLOW)
#define LWIS_PLATFORM_EVENT_ID_GDC_CMDQ_INT_QUE0_PUSH_BACK_TO_FULL_QUE \
	EVENT_ID(GDC_CMDQ_INT_BASE, \
		 GDC_CMDQ_INT_QUE0_PUSH_BACK_TO_FULL_QUE)
#define LWIS_PLATFORM_EVENT_ID_GDC_CMDQ_INT_QUE1_PUSH_BACK_TO_FULL_QUE \
	EVENT_ID(GDC_CMDQ_INT_BASE, \
		 GDC_CMDQ_INT_QUE1_PUSH_BACK_TO_FULL_QUE)
#define LWIS_PLATFORM_EVENT_ID_GDC_CMDQ_INT_QUE_U_PUSH_BACK_TO_FULL_QUE \
	EVENT_ID(GDC_CMDQ_INT_BASE, \
		 GDC_CMDQ_INT_QUE_U_PUSH_BACK_TO_FULL_QUE)

#endif /* DT_BINDINGS_LWIS_PLATFORM_ZUMA_GDC_H_ */
