/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Google LWIS ZUMA LME Interrupt And Event Defines
 *
 * Copyright (c) 2022 Google, LLC
 */

#ifndef DT_BINDINGS_LWIS_PLATFORM_ZUMA_LME_H_
#define DT_BINDINGS_LWIS_PLATFORM_ZUMA_LME_H_

#include <dt-bindings/lwis/platform/common.h>

/* clang-format off */

#define LME_INT1_BASE (HW_EVENT_MASK + 0)

#define LME_INT1_FRAME_START 0
#define LME_INT1_FRAME_END 1
#define LME_INT1_FRAME_ROW_COL_INFO 2
#define LME_INT1_IRQ_CORRUPTED 3
#define LME_INT1_COREX_ERROR 4
#define LME_INT1_PRE_FRAME_END 5
#define LME_INT1_MVCT_DONE 6
#define LME_INT1_COREX_END0 7
#define LME_INT1_COREX_END1 8
#define LME_INT1_MVCT_TRS_CONN_LOST 9
#define LME_INT1_CTRL_ERROR 10
#define LME_INT1_DMA_CLIENTS_ERROR 11
#define LME_INT1_DMA_CLIENTS_INFO 12
#define LME_INT1_C2COM_SLOW_RING 13
#define LME_INT1_TRS0_LOST_FLUSH 14
#define LME_INT1_TRS1_LOST_FLUSH 15

/* clang-format on */

#define LWIS_PLATFORM_EVENT_ID_LME_INT1_FRAME_START EVENT_ID(LME_INT1_BASE, LME_INT1_FRAME_START)
#define LWIS_PLATFORM_EVENT_ID_LME_INT1_FRAME_END EVENT_ID(LME_INT1_BASE, LME_INT1_FRAME_END)
#define LWIS_PLATFORM_EVENT_ID_LME_INT1_FRAME_ROW_COL_INFO                                         \
	EVENT_ID(LME_INT1_BASE, LME_INT1_FRAME_ROW_COL_INFO)
#define LWIS_PLATFORM_EVENT_ID_LME_INT1_IRQ_CORRUPTED                                              \
	EVENT_ID(LME_INT1_BASE, LME_INT1_IRQ_CORRUPTED)
#define LWIS_PLATFORM_EVENT_ID_LME_INT1_COREX_ERROR EVENT_ID(LME_INT1_BASE, LME_INT1_COREX_ERROR)
#define LWIS_PLATFORM_EVENT_ID_LME_INT1_PRE_FRAME_END                                              \
	EVENT_ID(LME_INT1_BASE, LME_INT1_PRE_FRAME_END)
#define LWIS_PLATFORM_EVENT_ID_LME_INT1_MVCT_DONE EVENT_ID(LME_INT1_BASE, LME_INT1_MVCT_DONE)
#define LWIS_PLATFORM_EVENT_ID_LME_INT1_COREX_END0 EVENT_ID(LME_INT1_BASE, LME_INT1_COREX_END0)
#define LWIS_PLATFORM_EVENT_ID_LME_INT1_COREX_END1 EVENT_ID(LME_INT1_BASE, LME_INT1_COREX_END1)
#define LWIS_PLATFORM_EVENT_ID_LME_INT1_MVCT_TRS_CONN_LOST                                         \
	EVENT_ID(LME_INT1_BASE, LME_INT1_MVCT_TRS_CONN_LOST)
#define LWIS_PLATFORM_EVENT_ID_LME_INT1_CTRL_ERROR EVENT_ID(LME_INT1_BASE, LME_INT1_CTRL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_LME_INT1_DMA_CLIENTS_ERROR                                          \
	EVENT_ID(LME_INT1_BASE, LME_INT1_DMA_CLIENTS_ERROR)
#define LWIS_PLATFORM_EVENT_ID_LME_INT1_DMA_CLIENTS_INFO                                           \
	EVENT_ID(LME_INT1_BASE, LME_INT1_DMA_CLIENTS_INFO)
#define LWIS_PLATFORM_EVENT_ID_LME_INT1_C2COM_SLOW_RING                                            \
	EVENT_ID(LME_INT1_BASE, LME_INT1_C2COM_SLOW_RING)
#define LWIS_PLATFORM_EVENT_ID_LME_INT1_TRS0_LOST_FLUSH                                            \
	EVENT_ID(LME_INT1_BASE, LME_INT1_TRS0_LOST_FLUSH)
#define LWIS_PLATFORM_EVENT_ID_LME_INT1_TRS1_LOST_FLUSH                                            \
	EVENT_ID(LME_INT1_BASE, LME_INT1_TRS1_LOST_FLUSH)

#endif /* DT_BINDINGS_LWIS_PLATFORM_ZUMA_LME_H_ */
