## SPDX-License-Identifier: GPL-2.0-only

ccflags-y += -I$(srctree)/drivers/dma-buf
ccflags-y += -I$(KERNEL_SRC)/../private/google-modules/trusty/include

# vendor hook for mm
obj-$(CONFIG_PIXEL_STAT) += pixel_stat_mm.o
pixel_stat_mm-y += init.o page_alloc.o sysfs_node.o filemap.o cma.o meminfo.o vmscan.o compaction.o procfs_node.o
