dtb-$(CONFIG_SOC_GS201) += \
        gs201-a0.dtb \
        gs201-b0.dtb \
        gs201-b0_v2-ipop.dtb \

dtbo-y += \
        gs201-lynx-dev1_0.dtbo \
        gs201-lynx-proto1_0.dtbo \
        gs201-lynx-proto1_1.dtbo \
        gs201-lynx-evt1_0.dtbo \
        gs201-lynx-evt1_0-wingboard.dtbo \
        gs201-lynx-evt1_1.dtbo \
        gs201-lynx-dvt1_0.dtbo \
        gs201-lynx-dvt1_0-gain1.dtbo \
        gs201-lynx-pvt1_0.dtbo \
        gs201-lynx-mp1_0.dtbo

gs201-lynx-dev1_0.dtbo-base := google-base/gs201-a0.dtb
gs201-lynx-proto1_0.dtbo-base := google-base/gs201-a0.dtb
gs201-lynx-proto1_1.dtbo-base := google-base/gs201-b0_v2-ipop.dtb
gs201-lynx-evt1_0.dtbo-base := google-base/gs201-b0_v2-ipop.dtb
gs201-lynx-evt1_0-wingboard.dtbo-base := google-base/gs201-b0_v2-ipop.dtb
gs201-lynx-evt1_1.dtbo-base := google-base/gs201-b0_v2-ipop.dtb
gs201-lynx-dvt1_0.dtbo-base := google-base/gs201-b0_v2-ipop.dtb
gs201-lynx-dvt1_0-gain1.dtbo-base := google-base/gs201-b0_v2-ipop.dtb
gs201-lynx-pvt1_0.dtbo-base := google-base/gs201-b0_v2-ipop.dtb
gs201-lynx-mp1_0.dtbo-base := google-base/gs201-b0_v2-ipop.dtb

MKDTIMG_FLAGS += --page_size=4096  --id=/:board_id --rev=/:board_rev
