obj-$(CONFIG_GOOGLE_BCL)	+= google_bcl.o

ifneq ($(CONFIG_MFD_S2MPG13),)
obj-$(CONFIG_GSOC_PMIC_THERMAL)	+= s2mpg13_spmic_thermal.o
endif

ifneq ($(CONFIG_MFD_S2MPG11),)
obj-$(CONFIG_GSOC_PMIC_THERMAL)	+= gs101_spmic_thermal.o
endif
