/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Google LWIS GS201 IPP Interrupt And Event Defines
 *
 * Copyright (c) 2021 Google, LLC
 */

#ifndef DT_BINDINGS_LWIS_PLATFORM_GS201_IPP_H_
#define DT_BINDINGS_LWIS_PLATFORM_GS201_IPP_H_

#include <dt-bindings/lwis/platform/common.h>

/* clang-format off */


#define IPP_INT1_CTX0_BASE (HW_EVENT_MASK + 0)

#define IPP_INT1_CTX0_FRAME_START 0
#define IPP_INT1_CTX0_FRAME_END_INTERRUPT 1
#define IPP_INT1_CTX0_FRAME_INT_ON_ROW_COL_INFO 2
#define IPP_INT1_CTX0_IRQ_CORRUPTED 3
#define IPP_INT1_CTX0_COREX_ERROR_INT 4
#define IPP_INT1_CTX0_P_SLVERR 5
#define IPP_INT1_CTX0_PRE_FRAME_END_INTERRUPT 6
#define IPP_INT1_CTX0_COUTFIFO_DATA_OUT_END_INT 7
#define IPP_INT1_CTX0_COUTFIFO_FRAME_OUT_END_INT 8
#define IPP_INT1_CTX0_STRP_OUT_DMA_IN_LAST 9
#define IPP_INT1_CTX0_BDS_DATA_OUT_LAST 10
#define IPP_INT1_CTX0_ZSL_OUT_DMA_IN_LAST 11
#define IPP_INT1_CTX0_BCROP1_DATA_IN_LAST 12
#define IPP_INT1_CTX0_BCROP0_DATA_IN_LAST 13
#define IPP_INT1_CTX0_RGBY_HIST2_DMA_DONE 14
#define IPP_INT1_CTX0_RGBYHIST_DATA_OUT_LAST 15
#define IPP_INT1_CTX0_THSTAT_DATA_IN_LAST 16
#define IPP_INT1_CTX0_GP_DATA_IN_LAST 17
#define IPP_INT1_CTX0_CINFIFO_DATA_OUT_END_INT 18
#define IPP_INT1_CTX0_CINFIFO_FRAME_OUT_END_INT 19
#define IPP_INT1_CTX0_COREX_END_INT0 20
#define IPP_INT1_CTX0_COREX_END_INT1 21
#define IPP_INT1_CTX0_COUTFIFO_SIZE_ERROR 22
#define IPP_INT1_CTX0_COUTFIFO_LINE_ERROR 23
#define IPP_INT1_CTX0_COUTFIFO_COL_ERROR 24
#define IPP_INT1_CTX0_COUTFIFO_OVERFLOW_ERROR 25
#define IPP_INT1_CTX0_CINFIFO_TOTAL_SIZE_ERROR_INT 26
#define IPP_INT1_CTX0_CINFIFO_LINES_ERROR_INT 27
#define IPP_INT1_CTX0_CINFIFO_COLUMNS_ERROR_INT 28
#define IPP_INT1_CTX0_CINFIFO_STREAM_OVERFLOW_SIG 29
#define IPP_INT1_CTX0_FRAME_START_BEFORE_FRAME_END_CORRUPTED 30

#define IPP_INT1_CTX1_BASE (HW_EVENT_MASK + 32)

#define IPP_INT1_CTX1_FRAME_START 0
#define IPP_INT1_CTX1_FRAME_END_INTERRUPT 1
#define IPP_INT1_CTX1_FRAME_INT_ON_ROW_COL_INFO 2
#define IPP_INT1_CTX1_IRQ_CORRUPTED 3
#define IPP_INT1_CTX1_COREX_ERROR_INT 4
#define IPP_INT1_CTX1_P_SLVERR 5
#define IPP_INT1_CTX1_PRE_FRAME_END_INTERRUPT 6
#define IPP_INT1_CTX1_COUTFIFO_DATA_OUT_END_INT 7
#define IPP_INT1_CTX1_COUTFIFO_FRAME_OUT_END_INT 8
#define IPP_INT1_CTX1_STRP_OUT_DMA_IN_LAST 9
#define IPP_INT1_CTX1_BDS_DATA_OUT_LAST 10
#define IPP_INT1_CTX1_ZSL_OUT_DMA_IN_LAST 11
#define IPP_INT1_CTX1_BCROP1_DATA_IN_LAST 12
#define IPP_INT1_CTX1_BCROP0_DATA_IN_LAST 13
#define IPP_INT1_CTX1_RGBY_HIST2_DMA_DONE 14
#define IPP_INT1_CTX1_RGBYHIST_DATA_OUT_LAST 15
#define IPP_INT1_CTX1_THSTAT_DATA_IN_LAST 16
#define IPP_INT1_CTX1_GP_DATA_IN_LAST 17
#define IPP_INT1_CTX1_CINFIFO_DATA_OUT_END_INT 18
#define IPP_INT1_CTX1_CINFIFO_FRAME_OUT_END_INT 19
#define IPP_INT1_CTX1_COREX_END_INT0 20
#define IPP_INT1_CTX1_COREX_END_INT1 21
#define IPP_INT1_CTX1_COUTFIFO_SIZE_ERROR 22
#define IPP_INT1_CTX1_COUTFIFO_LINE_ERROR 23
#define IPP_INT1_CTX1_COUTFIFO_COL_ERROR 24
#define IPP_INT1_CTX1_COUTFIFO_OVERFLOW_ERROR 25
#define IPP_INT1_CTX1_CINFIFO_TOTAL_SIZE_ERROR_INT 26
#define IPP_INT1_CTX1_CINFIFO_LINES_ERROR_INT 27
#define IPP_INT1_CTX1_CINFIFO_COLUMNS_ERROR_INT 28
#define IPP_INT1_CTX1_CINFIFO_STREAM_OVERFLOW_SIG 29
#define IPP_INT1_CTX1_FRAME_START_BEFORE_FRAME_END_CORRUPTED 30

#define IPP_INT1_CTX2_BASE (HW_EVENT_MASK + 64)

#define IPP_INT1_CTX2_FRAME_START 0
#define IPP_INT1_CTX2_FRAME_END_INTERRUPT 1
#define IPP_INT1_CTX2_FRAME_INT_ON_ROW_COL_INFO 2
#define IPP_INT1_CTX2_IRQ_CORRUPTED 3
#define IPP_INT1_CTX2_COREX_ERROR_INT 4
#define IPP_INT1_CTX2_P_SLVERR 5
#define IPP_INT1_CTX2_PRE_FRAME_END_INTERRUPT 6
#define IPP_INT1_CTX2_COUTFIFO_DATA_OUT_END_INT 7
#define IPP_INT1_CTX2_COUTFIFO_FRAME_OUT_END_INT 8
#define IPP_INT1_CTX2_STRP_OUT_DMA_IN_LAST 9
#define IPP_INT1_CTX2_BDS_DATA_OUT_LAST 10
#define IPP_INT1_CTX2_ZSL_OUT_DMA_IN_LAST 11
#define IPP_INT1_CTX2_BCROP1_DATA_IN_LAST 12
#define IPP_INT1_CTX2_BCROP0_DATA_IN_LAST 13
#define IPP_INT1_CTX2_RGBY_HIST2_DMA_DONE 14
#define IPP_INT1_CTX2_RGBYHIST_DATA_OUT_LAST 15
#define IPP_INT1_CTX2_THSTAT_DATA_IN_LAST 16
#define IPP_INT1_CTX2_GP_DATA_IN_LAST 17
#define IPP_INT1_CTX2_CINFIFO_DATA_OUT_END_INT 18
#define IPP_INT1_CTX2_CINFIFO_FRAME_OUT_END_INT 19
#define IPP_INT1_CTX2_COREX_END_INT0 20
#define IPP_INT1_CTX2_COREX_END_INT1 21
#define IPP_INT1_CTX2_COUTFIFO_SIZE_ERROR 22
#define IPP_INT1_CTX2_COUTFIFO_LINE_ERROR 23
#define IPP_INT1_CTX2_COUTFIFO_COL_ERROR 24
#define IPP_INT1_CTX2_COUTFIFO_OVERFLOW_ERROR 25
#define IPP_INT1_CTX2_CINFIFO_TOTAL_SIZE_ERROR_INT 26
#define IPP_INT1_CTX2_CINFIFO_LINES_ERROR_INT 27
#define IPP_INT1_CTX2_CINFIFO_COLUMNS_ERROR_INT 28
#define IPP_INT1_CTX2_CINFIFO_STREAM_OVERFLOW_SIG 29
#define IPP_INT1_CTX2_FRAME_START_BEFORE_FRAME_END_CORRUPTED 30



#define IPP_INT2_CTX0_BASE (HW_EVENT_MASK + 96)

#define IPP_INT2_CTX0_CDAF_INT 0
#define IPP_INT2_CTX0_COUTFIFO_FRAME_OUT_START_INFO 1
#define IPP_INT2_CTX0_CINFIFO_FRAME_IN_END_INFO 2
#define IPP_INT2_CTX0_CINFIFO_FRAME_IN_START_INFO 3
#define IPP_INT2_CTX0_THSTAT_STATISTICS_DONE 4
#define IPP_INT2_CTX0_FRO_GROUP2 5
#define IPP_INT2_CTX0_FRO_GROUP4 6
#define IPP_INT2_CTX0_FRO_GROUP5 7

#define IPP_INT2_CTX1_BASE (HW_EVENT_MASK + 128)

#define IPP_INT2_CTX1_CDAF_INT 0
#define IPP_INT2_CTX1_COUTFIFO_FRAME_OUT_START_INFO 1
#define IPP_INT2_CTX1_CINFIFO_FRAME_IN_END_INFO 2
#define IPP_INT2_CTX1_CINFIFO_FRAME_IN_START_INFO 3
#define IPP_INT2_CTX1_THSTAT_STATISTICS_DONE 4
#define IPP_INT2_CTX1_FRO_GROUP2 5
#define IPP_INT2_CTX1_FRO_GROUP4 6
#define IPP_INT2_CTX1_FRO_GROUP5 7

#define IPP_INT2_CTX2_BASE (HW_EVENT_MASK + 160)

#define IPP_INT2_CTX2_CDAF_INT 0
#define IPP_INT2_CTX2_COUTFIFO_FRAME_OUT_START_INFO 1
#define IPP_INT2_CTX2_CINFIFO_FRAME_IN_END_INFO 2
#define IPP_INT2_CTX2_CINFIFO_FRAME_IN_START_INFO 3
#define IPP_INT2_CTX2_THSTAT_STATISTICS_DONE 4
#define IPP_INT2_CTX2_FRO_GROUP2 5
#define IPP_INT2_CTX2_FRO_GROUP4 6
#define IPP_INT2_CTX2_FRO_GROUP5 7




#define IPP_FRO_INT0_CTX0_BASE (HW_EVENT_MASK + 192)

#define IPP_FRO_INT0_CTX0_FRAME_START 0
#define IPP_FRO_INT0_CTX0_FRAME_END_INTERRUPT 1
#define IPP_FRO_INT0_CTX0_FRAME_INT_ON_ROW_COL_INFO 2
#define IPP_FRO_INT0_CTX0_IRQ_CORRUPTED 3
#define IPP_FRO_INT0_CTX0_COREX_ERROR_INT 4
#define IPP_FRO_INT0_CTX0_P_SLVERR 5
#define IPP_FRO_INT0_CTX0_PRE_FRAME_END_INTERRUPT 6
#define IPP_FRO_INT0_CTX0_COUTFIFO_DATA_OUT_END_INT 7
#define IPP_FRO_INT0_CTX0_COUTFIFO_FRAME_OUT_END_INT 8
#define IPP_FRO_INT0_CTX0_STRP_OUT_DMA_IN_LAST 9
#define IPP_FRO_INT0_CTX0_BDS_DATA_OUT_LAST 10
#define IPP_FRO_INT0_CTX0_ZSL_OUT_DMA_IN_LAST 11
#define IPP_FRO_INT0_CTX0_BCROP1_DATA_IN_LAST 12
#define IPP_FRO_INT0_CTX0_BCROP0_DATA_IN_LAST 13
#define IPP_FRO_INT0_CTX0_RGBYHIST2DMA_DONE 14
#define IPP_FRO_INT0_CTX0_RGBYHIST_DATA_OUT_LAST 15
#define IPP_FRO_INT0_CTX0_THSTAT_DATA_IN_LAST 16
#define IPP_FRO_INT0_CTX0_GP_DATA_IN_LAST 17
#define IPP_FRO_INT0_CTX0_CINFIFO_DATA_OUT_END_INT 18
#define IPP_FRO_INT0_CTX0_CINFIFO_FRAME_OUT_END_INT 19
#define IPP_FRO_INT0_CTX0_COREX_END_INT0 20
#define IPP_FRO_INT0_CTX0_COREX_END_INT1 21
#define IPP_FRO_INT0_CTX0_COUTFIFO_SIZE_ERROR 22
#define IPP_FRO_INT0_CTX0_COUTFIFO_LINE_ERROR 23
#define IPP_FRO_INT0_CTX0_COUTFIFO_COL_ERROR 24
#define IPP_FRO_INT0_CTX0_COUTFIFO_OVERFLOW_ERROR 25
#define IPP_FRO_INT0_CTX0_CINFIFO_TOTAL_SIZE_ERROR_INT 26
#define IPP_FRO_INT0_CTX0_CINFIFO_LINES_ERROR_INT 27
#define IPP_FRO_INT0_CTX0_CINFIFO_COLUMNS_ERROR_INT 28
#define IPP_FRO_INT0_CTX0_CINFIFO_STREAM_OVERFLOW_SIG 29
#define IPP_FRO_INT0_CTX0_FRAME_START_BEFORE_FRAME_END_CORRUPTED 30

#define IPP_FRO_INT0_CTX1_BASE (HW_EVENT_MASK + 224)

#define IPP_FRO_INT0_CTX1_FRAME_START 0
#define IPP_FRO_INT0_CTX1_FRAME_END_INTERRUPT 1
#define IPP_FRO_INT0_CTX1_FRAME_INT_ON_ROW_COL_INFO 2
#define IPP_FRO_INT0_CTX1_IRQ_CORRUPTED 3
#define IPP_FRO_INT0_CTX1_COREX_ERROR_INT 4
#define IPP_FRO_INT0_CTX1_P_SLVERR 5
#define IPP_FRO_INT0_CTX1_PRE_FRAME_END_INTERRUPT 6
#define IPP_FRO_INT0_CTX1_COUTFIFO_DATA_OUT_END_INT 7
#define IPP_FRO_INT0_CTX1_COUTFIFO_FRAME_OUT_END_INT 8
#define IPP_FRO_INT0_CTX1_STRP_OUT_DMA_IN_LAST 9
#define IPP_FRO_INT0_CTX1_BDS_DATA_OUT_LAST 10
#define IPP_FRO_INT0_CTX1_ZSL_OUT_DMA_IN_LAST 11
#define IPP_FRO_INT0_CTX1_BCROP1_DATA_IN_LAST 12
#define IPP_FRO_INT0_CTX1_BCROP0_DATA_IN_LAST 13
#define IPP_FRO_INT0_CTX1_RGBYHIST2DMA_DONE 14
#define IPP_FRO_INT0_CTX1_RGBYHIST_DATA_OUT_LAST 15
#define IPP_FRO_INT0_CTX1_THSTAT_DATA_IN_LAST 16
#define IPP_FRO_INT0_CTX1_GP_DATA_IN_LAST 17
#define IPP_FRO_INT0_CTX1_CINFIFO_DATA_OUT_END_INT 18
#define IPP_FRO_INT0_CTX1_CINFIFO_FRAME_OUT_END_INT 19
#define IPP_FRO_INT0_CTX1_COREX_END_INT0 20
#define IPP_FRO_INT0_CTX1_COREX_END_INT1 21
#define IPP_FRO_INT0_CTX1_COUTFIFO_SIZE_ERROR 22
#define IPP_FRO_INT0_CTX1_COUTFIFO_LINE_ERROR 23
#define IPP_FRO_INT0_CTX1_COUTFIFO_COL_ERROR 24
#define IPP_FRO_INT0_CTX1_COUTFIFO_OVERFLOW_ERROR 25
#define IPP_FRO_INT0_CTX1_CINFIFO_TOTAL_SIZE_ERROR_INT 26
#define IPP_FRO_INT0_CTX1_CINFIFO_LINES_ERROR_INT 27
#define IPP_FRO_INT0_CTX1_CINFIFO_COLUMNS_ERROR_INT 28
#define IPP_FRO_INT0_CTX1_CINFIFO_STREAM_OVERFLOW_SIG 29
#define IPP_FRO_INT0_CTX1_FRAME_START_BEFORE_FRAME_END_CORRUPTED 30

#define IPP_FRO_INT0_CTX2_BASE (HW_EVENT_MASK + 256)

#define IPP_FRO_INT0_CTX2_FRAME_START 0
#define IPP_FRO_INT0_CTX2_FRAME_END_INTERRUPT 1
#define IPP_FRO_INT0_CTX2_FRAME_INT_ON_ROW_COL_INFO 2
#define IPP_FRO_INT0_CTX2_IRQ_CORRUPTED 3
#define IPP_FRO_INT0_CTX2_COREX_ERROR_INT 4
#define IPP_FRO_INT0_CTX2_P_SLVERR 5
#define IPP_FRO_INT0_CTX2_PRE_FRAME_END_INTERRUPT 6
#define IPP_FRO_INT0_CTX2_COUTFIFO_DATA_OUT_END_INT 7
#define IPP_FRO_INT0_CTX2_COUTFIFO_FRAME_OUT_END_INT 8
#define IPP_FRO_INT0_CTX2_STRP_OUT_DMA_IN_LAST 9
#define IPP_FRO_INT0_CTX2_BDS_DATA_OUT_LAST 10
#define IPP_FRO_INT0_CTX2_ZSL_OUT_DMA_IN_LAST 11
#define IPP_FRO_INT0_CTX2_BCROP1_DATA_IN_LAST 12
#define IPP_FRO_INT0_CTX2_BCROP0_DATA_IN_LAST 13
#define IPP_FRO_INT0_CTX2_RGBYHIST2DMA_DONE 14
#define IPP_FRO_INT0_CTX2_RGBYHIST_DATA_OUT_LAST 15
#define IPP_FRO_INT0_CTX2_THSTAT_DATA_IN_LAST 16
#define IPP_FRO_INT0_CTX2_GP_DATA_IN_LAST 17
#define IPP_FRO_INT0_CTX2_CINFIFO_DATA_OUT_END_INT 18
#define IPP_FRO_INT0_CTX2_CINFIFO_FRAME_OUT_END_INT 19
#define IPP_FRO_INT0_CTX2_COREX_END_INT0 20
#define IPP_FRO_INT0_CTX2_COREX_END_INT1 21
#define IPP_FRO_INT0_CTX2_COUTFIFO_SIZE_ERROR 22
#define IPP_FRO_INT0_CTX2_COUTFIFO_LINE_ERROR 23
#define IPP_FRO_INT0_CTX2_COUTFIFO_COL_ERROR 24
#define IPP_FRO_INT0_CTX2_COUTFIFO_OVERFLOW_ERROR 25
#define IPP_FRO_INT0_CTX2_CINFIFO_TOTAL_SIZE_ERROR_INT 26
#define IPP_FRO_INT0_CTX2_CINFIFO_LINES_ERROR_INT 27
#define IPP_FRO_INT0_CTX2_CINFIFO_COLUMNS_ERROR_INT 28
#define IPP_FRO_INT0_CTX2_CINFIFO_STREAM_OVERFLOW_SIG 29
#define IPP_FRO_INT0_CTX2_FRAME_START_BEFORE_FRAME_END_CORRUPTED 30



#define IPP_FRO_INT1_CTX0_BASE (HW_EVENT_MASK + 288)

#define IPP_FRO_INT1_CTX0_CDAF_INT 0
#define IPP_FRO_INT1_CTX0_COUTFIFO_FRAME_OUT_START_INFO 1
#define IPP_FRO_INT1_CTX0_CINFIFO_FRAME_IN_END_INFO 2
#define IPP_FRO_INT1_CTX0_CINFIFO_FRAME_IN_START_INFO 3
#define IPP_FRO_INT1_CTX0_THSTAT_STATISTICS_DONE 4
#define IPP_FRO_INT1_CTX0_FRO_GROUP2_INT 5
#define IPP_FRO_INT1_CTX0_FRO_GROUP4_INT 6
#define IPP_FRO_INT1_CTX0_FRO_GROUP5_INT 7

#define IPP_FRO_INT1_CTX1_BASE (HW_EVENT_MASK + 320)

#define IPP_FRO_INT1_CTX1_CDAF_INT 0
#define IPP_FRO_INT1_CTX1_COUTFIFO_FRAME_OUT_START_INFO 1
#define IPP_FRO_INT1_CTX1_CINFIFO_FRAME_IN_END_INFO 2
#define IPP_FRO_INT1_CTX1_CINFIFO_FRAME_IN_START_INFO 3
#define IPP_FRO_INT1_CTX1_THSTAT_STATISTICS_DONE 4
#define IPP_FRO_INT1_CTX1_FRO_GROUP2_INT 5
#define IPP_FRO_INT1_CTX1_FRO_GROUP4_INT 6
#define IPP_FRO_INT1_CTX1_FRO_GROUP5_INT 7

#define IPP_FRO_INT1_CTX2_BASE (HW_EVENT_MASK + 352)

#define IPP_FRO_INT1_CTX2_CDAF_INT 0
#define IPP_FRO_INT1_CTX2_COUTFIFO_FRAME_OUT_START_INFO 1
#define IPP_FRO_INT1_CTX2_CINFIFO_FRAME_IN_END_INFO 2
#define IPP_FRO_INT1_CTX2_CINFIFO_FRAME_IN_START_INFO 3
#define IPP_FRO_INT1_CTX2_THSTAT_STATISTICS_DONE 4
#define IPP_FRO_INT1_CTX2_FRO_GROUP2_INT 5
#define IPP_FRO_INT1_CTX2_FRO_GROUP4_INT 6
#define IPP_FRO_INT1_CTX2_FRO_GROUP5_INT 7

/* clang-format on */

#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_FRAME_START                                                \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_FRAME_START)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_FRAME_END_INTERRUPT                                        \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_FRAME_END_INTERRUPT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_FRAME_INT_ON_ROW_COL_INFO                                  \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_FRAME_INT_ON_ROW_COL_INFO)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_IRQ_CORRUPTED                                              \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_IRQ_CORRUPTED)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_COREX_ERROR_INT                                            \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_COREX_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_P_SLVERR                                                   \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_P_SLVERR)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_PRE_FRAME_END_INTERRUPT                                    \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_PRE_FRAME_END_INTERRUPT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_COUTFIFO_DATA_OUT_END_INT                                  \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_COUTFIFO_DATA_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_COUTFIFO_FRAME_OUT_END_INT                                 \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_COUTFIFO_FRAME_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_STRP_OUT_DMA_IN_LAST                                       \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_STRP_OUT_DMA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_BDS_DATA_OUT_LAST                                          \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_BDS_DATA_OUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_ZSL_OUT_DMA_IN_LAST                                        \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_ZSL_OUT_DMA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_BCROP1_DATA_IN_LAST                                        \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_BCROP1_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_BCROP0_DATA_IN_LAST                                        \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_BCROP0_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_RGBY_HIST2_DMA_DONE                                        \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_RGBY_HIST2_DMA_DONE)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_RGBYHIST_DATA_OUT_LAST                                     \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_RGBYHIST_DATA_OUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_THSTAT_DATA_IN_LAST                                        \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_THSTAT_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_GP_DATA_IN_LAST                                            \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_GP_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_CINFIFO_DATA_OUT_END_INT                                   \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_CINFIFO_DATA_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_CINFIFO_FRAME_OUT_END_INT                                  \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_CINFIFO_FRAME_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_COREX_END_INT0                                             \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_COREX_END_INT0)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_COREX_END_INT1                                             \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_COREX_END_INT1)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_COUTFIFO_SIZE_ERROR                                        \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_COUTFIFO_SIZE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_COUTFIFO_LINE_ERROR                                        \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_COUTFIFO_LINE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_COUTFIFO_COL_ERROR                                         \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_COUTFIFO_COL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_COUTFIFO_OVERFLOW_ERROR                                    \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_COUTFIFO_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_CINFIFO_TOTAL_SIZE_ERROR_INT                               \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_CINFIFO_TOTAL_SIZE_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_CINFIFO_LINES_ERROR_INT                                    \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_CINFIFO_LINES_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_CINFIFO_COLUMNS_ERROR_INT                                  \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_CINFIFO_COLUMNS_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_CINFIFO_STREAM_OVERFLOW_SIG                                \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_CINFIFO_STREAM_OVERFLOW_SIG)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_FRAME_START_BEFORE_FRAME_END_CORRUPTED                     \
	EVENT_ID(IPP_INT1_CTX0_BASE, IPP_INT1_CTX0_FRAME_START_BEFORE_FRAME_END_CORRUPTED)

#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_FRAME_START                                                \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_FRAME_START)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_FRAME_END_INTERRUPT                                        \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_FRAME_END_INTERRUPT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_FRAME_INT_ON_ROW_COL_INFO                                  \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_FRAME_INT_ON_ROW_COL_INFO)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_IRQ_CORRUPTED                                              \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_IRQ_CORRUPTED)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_COREX_ERROR_INT                                            \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_COREX_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_P_SLVERR                                                   \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_P_SLVERR)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_PRE_FRAME_END_INTERRUPT                                    \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_PRE_FRAME_END_INTERRUPT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_COUTFIFO_DATA_OUT_END_INT                                  \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_COUTFIFO_DATA_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_COUTFIFO_FRAME_OUT_END_INT                                 \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_COUTFIFO_FRAME_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_STRP_OUT_DMA_IN_LAST                                       \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_STRP_OUT_DMA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_BDS_DATA_OUT_LAST                                          \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_BDS_DATA_OUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_ZSL_OUT_DMA_IN_LAST                                        \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_ZSL_OUT_DMA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_BCROP1_DATA_IN_LAST                                        \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_BCROP1_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_BCROP0_DATA_IN_LAST                                        \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_BCROP0_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_RGBY_HIST2_DMA_DONE                                        \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_RGBY_HIST2_DMA_DONE)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_RGBYHIST_DATA_OUT_LAST                                     \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_RGBYHIST_DATA_OUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_THSTAT_DATA_IN_LAST                                        \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_THSTAT_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_GP_DATA_IN_LAST                                            \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_GP_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_CINFIFO_DATA_OUT_END_INT                                   \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_CINFIFO_DATA_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_CINFIFO_FRAME_OUT_END_INT                                  \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_CINFIFO_FRAME_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_COREX_END_INT0                                             \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_COREX_END_INT0)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_COREX_END_INT1                                             \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_COREX_END_INT1)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_COUTFIFO_SIZE_ERROR                                        \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_COUTFIFO_SIZE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_COUTFIFO_LINE_ERROR                                        \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_COUTFIFO_LINE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_COUTFIFO_COL_ERROR                                         \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_COUTFIFO_COL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_COUTFIFO_OVERFLOW_ERROR                                    \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_COUTFIFO_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_CINFIFO_TOTAL_SIZE_ERROR_INT                               \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_CINFIFO_TOTAL_SIZE_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_CINFIFO_LINES_ERROR_INT                                    \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_CINFIFO_LINES_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_CINFIFO_COLUMNS_ERROR_INT                                  \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_CINFIFO_COLUMNS_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_CINFIFO_STREAM_OVERFLOW_SIG                                \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_CINFIFO_STREAM_OVERFLOW_SIG)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_FRAME_START_BEFORE_FRAME_END_CORRUPTED                     \
	EVENT_ID(IPP_INT1_CTX1_BASE, IPP_INT1_CTX1_FRAME_START_BEFORE_FRAME_END_CORRUPTED)

#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_FRAME_START                                                \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_FRAME_START)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_FRAME_END_INTERRUPT                                        \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_FRAME_END_INTERRUPT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_FRAME_INT_ON_ROW_COL_INFO                                  \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_FRAME_INT_ON_ROW_COL_INFO)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_IRQ_CORRUPTED                                              \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_IRQ_CORRUPTED)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_COREX_ERROR_INT                                            \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_COREX_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_P_SLVERR                                                   \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_P_SLVERR)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_PRE_FRAME_END_INTERRUPT                                    \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_PRE_FRAME_END_INTERRUPT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_COUTFIFO_DATA_OUT_END_INT                                  \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_COUTFIFO_DATA_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_COUTFIFO_FRAME_OUT_END_INT                                 \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_COUTFIFO_FRAME_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_STRP_OUT_DMA_IN_LAST                                       \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_STRP_OUT_DMA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_BDS_DATA_OUT_LAST                                          \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_BDS_DATA_OUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_ZSL_OUT_DMA_IN_LAST                                        \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_ZSL_OUT_DMA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_BCROP1_DATA_IN_LAST                                        \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_BCROP1_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_BCROP0_DATA_IN_LAST                                        \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_BCROP0_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_RGBY_HIST2_DMA_DONE                                        \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_RGBY_HIST2_DMA_DONE)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_RGBYHIST_DATA_OUT_LAST                                     \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_RGBYHIST_DATA_OUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_THSTAT_DATA_IN_LAST                                        \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_THSTAT_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_GP_DATA_IN_LAST                                            \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_GP_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_CINFIFO_DATA_OUT_END_INT                                   \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_CINFIFO_DATA_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_CINFIFO_FRAME_OUT_END_INT                                  \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_CINFIFO_FRAME_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_COREX_END_INT0                                             \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_COREX_END_INT0)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_COREX_END_INT1                                             \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_COREX_END_INT1)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_COUTFIFO_SIZE_ERROR                                        \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_COUTFIFO_SIZE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_COUTFIFO_LINE_ERROR                                        \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_COUTFIFO_LINE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_COUTFIFO_COL_ERROR                                         \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_COUTFIFO_COL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_COUTFIFO_OVERFLOW_ERROR                                    \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_COUTFIFO_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_CINFIFO_TOTAL_SIZE_ERROR_INT                               \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_CINFIFO_TOTAL_SIZE_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_CINFIFO_LINES_ERROR_INT                                    \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_CINFIFO_LINES_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_CINFIFO_COLUMNS_ERROR_INT                                  \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_CINFIFO_COLUMNS_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_CINFIFO_STREAM_OVERFLOW_SIG                                \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_CINFIFO_STREAM_OVERFLOW_SIG)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_FRAME_START_BEFORE_FRAME_END_CORRUPTED                     \
	EVENT_ID(IPP_INT1_CTX2_BASE, IPP_INT1_CTX2_FRAME_START_BEFORE_FRAME_END_CORRUPTED)

#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_CDAF_INT                                                   \
	EVENT_ID(IPP_INT2_CTX0_BASE, IPP_INT2_CTX0_CDAF_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_COUTFIFO_FRAME_OUT_START_INFO                              \
	EVENT_ID(IPP_INT2_CTX0_BASE, IPP_INT2_CTX0_COUTFIFO_FRAME_OUT_START_INFO)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_CINFIFO_FRAME_IN_END_INFO                                  \
	EVENT_ID(IPP_INT2_CTX0_BASE, IPP_INT2_CTX0_CINFIFO_FRAME_IN_END_INFO)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_CINFIFO_FRAME_IN_START_INFO                                \
	EVENT_ID(IPP_INT2_CTX0_BASE, IPP_INT2_CTX0_CINFIFO_FRAME_IN_START_INFO)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_THSTAT_STATISTICS_DONE                                     \
	EVENT_ID(IPP_INT2_CTX0_BASE, IPP_INT2_CTX0_THSTAT_STATISTICS_DONE)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_FRO_GROUP2                                                 \
	EVENT_ID(IPP_INT2_CTX0_BASE, IPP_INT2_CTX0_FRO_GROUP2)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_FRO_GROUP4                                                 \
	EVENT_ID(IPP_INT2_CTX0_BASE, IPP_INT2_CTX0_FRO_GROUP4)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX0_FRO_GROUP5                                                 \
	EVENT_ID(IPP_INT2_CTX0_BASE, IPP_INT2_CTX0_FRO_GROUP5)

#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_CDAF_INT                                                   \
	EVENT_ID(IPP_INT2_CTX1_BASE, IPP_INT2_CTX1_CDAF_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_COUTFIFO_FRAME_OUT_START_INFO                              \
	EVENT_ID(IPP_INT2_CTX1_BASE, IPP_INT2_CTX1_COUTFIFO_FRAME_OUT_START_INFO)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_CINFIFO_FRAME_IN_END_INFO                                  \
	EVENT_ID(IPP_INT2_CTX1_BASE, IPP_INT2_CTX1_CINFIFO_FRAME_IN_END_INFO)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_CINFIFO_FRAME_IN_START_INFO                                \
	EVENT_ID(IPP_INT2_CTX1_BASE, IPP_INT2_CTX1_CINFIFO_FRAME_IN_START_INFO)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_THSTAT_STATISTICS_DONE                                     \
	EVENT_ID(IPP_INT2_CTX1_BASE, IPP_INT2_CTX1_THSTAT_STATISTICS_DONE)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_FRO_GROUP2                                                 \
	EVENT_ID(IPP_INT2_CTX1_BASE, IPP_INT2_CTX1_FRO_GROUP2)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_FRO_GROUP4                                                 \
	EVENT_ID(IPP_INT2_CTX1_BASE, IPP_INT2_CTX1_FRO_GROUP4)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX1_FRO_GROUP5                                                 \
	EVENT_ID(IPP_INT2_CTX1_BASE, IPP_INT2_CTX1_FRO_GROUP5)

#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_CDAF_INT                                                   \
	EVENT_ID(IPP_INT2_CTX2_BASE, IPP_INT2_CTX2_CDAF_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_COUTFIFO_FRAME_OUT_START_INFO                              \
	EVENT_ID(IPP_INT2_CTX2_BASE, IPP_INT2_CTX2_COUTFIFO_FRAME_OUT_START_INFO)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_CINFIFO_FRAME_IN_END_INFO                                  \
	EVENT_ID(IPP_INT2_CTX2_BASE, IPP_INT2_CTX2_CINFIFO_FRAME_IN_END_INFO)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_CINFIFO_FRAME_IN_START_INFO                                \
	EVENT_ID(IPP_INT2_CTX2_BASE, IPP_INT2_CTX2_CINFIFO_FRAME_IN_START_INFO)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_THSTAT_STATISTICS_DONE                                     \
	EVENT_ID(IPP_INT2_CTX2_BASE, IPP_INT2_CTX2_THSTAT_STATISTICS_DONE)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_FRO_GROUP2                                                 \
	EVENT_ID(IPP_INT2_CTX2_BASE, IPP_INT2_CTX2_FRO_GROUP2)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_FRO_GROUP4                                                 \
	EVENT_ID(IPP_INT2_CTX2_BASE, IPP_INT2_CTX2_FRO_GROUP4)
#define LWIS_PLATFORM_EVENT_ID_IPP_CTX2_FRO_GROUP5                                                 \
	EVENT_ID(IPP_INT2_CTX2_BASE, IPP_INT2_CTX2_FRO_GROUP5)

#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_FRAME_START                                            \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_FRAME_START)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_FRAME_END_INTERRUPT                                    \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_FRAME_END_INTERRUPT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_FRAME_INT_ON_ROW_COL_INFO                              \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_FRAME_INT_ON_ROW_COL_INFO)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_IRQ_CORRUPTED                                          \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_IRQ_CORRUPTED)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_COREX_ERROR_INT                                        \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_COREX_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_P_SLVERR                                               \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_P_SLVERR)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_PRE_FRAME_END_INTERRUPT                                \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_PRE_FRAME_END_INTERRUPT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_COUTFIFO_DATA_OUT_END_INT                              \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_COUTFIFO_DATA_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_COUTFIFO_FRAME_OUT_END_INT                             \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_COUTFIFO_FRAME_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_STRP_OUT_DMA_IN_LAST                                   \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_STRP_OUT_DMA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_BDS_DATA_OUT_LAST                                      \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_BDS_DATA_OUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_ZSL_OUT_DMA_IN_LAST                                    \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_ZSL_OUT_DMA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_BCROP1_DATA_IN_LAST                                    \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_BCROP1_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_BCROP0_DATA_IN_LAST                                    \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_BCROP0_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_RGBYHIST2DMA_DONE                                      \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_RGBYHIST2DMA_DONE)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_RGBYHIST_DATA_OUT_LAST                                 \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_RGBYHIST_DATA_OUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_THSTAT_DATA_IN_LAST                                    \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_THSTAT_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_GP_DATA_IN_LAST                                        \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_GP_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_CINFIFO_DATA_OUT_END_INT                               \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_CINFIFO_DATA_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_CINFIFO_FRAME_OUT_END_INT                              \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_CINFIFO_FRAME_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_COREX_END_INT0                                         \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_COREX_END_INT0)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_COREX_END_INT1                                         \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_COREX_END_INT1)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_COUTFIFO_SIZE_ERROR                                    \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_COUTFIFO_SIZE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_COUTFIFO_LINE_ERROR                                    \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_COUTFIFO_LINE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_COUTFIFO_COL_ERROR                                     \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_COUTFIFO_COL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_COUTFIFO_OVERFLOW_ERROR                                \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_COUTFIFO_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_CINFIFO_TOTAL_SIZE_ERROR_INT                           \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_CINFIFO_TOTAL_SIZE_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_CINFIFO_LINES_ERROR_INT                                \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_CINFIFO_LINES_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_CINFIFO_COLUMNS_ERROR_INT                              \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_CINFIFO_COLUMNS_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_CINFIFO_STREAM_OVERFLOW_SIG                            \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_CINFIFO_STREAM_OVERFLOW_SIG)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_FRM_START_BEFORE_END_CORRUPTED                         \
	EVENT_ID(IPP_FRO_INT0_CTX0_BASE, IPP_FRO_INT0_CTX0_FRAME_START_BEFORE_FRAME_END_CORRUPTED)

#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_FRAME_START                                            \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_FRAME_START)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_FRAME_END_INTERRUPT                                    \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_FRAME_END_INTERRUPT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_FRAME_INT_ON_ROW_COL_INFO                              \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_FRAME_INT_ON_ROW_COL_INFO)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_IRQ_CORRUPTED                                          \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_IRQ_CORRUPTED)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_COREX_ERROR_INT                                        \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_COREX_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_P_SLVERR                                               \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_P_SLVERR)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_PRE_FRAME_END_INTERRUPT                                \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_PRE_FRAME_END_INTERRUPT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_COUTFIFO_DATA_OUT_END_INT                              \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_COUTFIFO_DATA_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_COUTFIFO_FRAME_OUT_END_INT                             \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_COUTFIFO_FRAME_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_STRP_OUT_DMA_IN_LAST                                   \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_STRP_OUT_DMA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_BDS_DATA_OUT_LAST                                      \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_BDS_DATA_OUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_ZSL_OUT_DMA_IN_LAST                                    \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_ZSL_OUT_DMA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_BCROP1_DATA_IN_LAST                                    \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_BCROP1_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_BCROP0_DATA_IN_LAST                                    \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_BCROP0_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_RGBYHIST2DMA_DONE                                      \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_RGBYHIST2DMA_DONE)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_RGBYHIST_DATA_OUT_LAST                                 \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_RGBYHIST_DATA_OUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_THSTAT_DATA_IN_LAST                                    \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_THSTAT_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_GP_DATA_IN_LAST                                        \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_GP_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_CINFIFO_DATA_OUT_END_INT                               \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_CINFIFO_DATA_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_CINFIFO_FRAME_OUT_END_INT                              \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_CINFIFO_FRAME_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_COREX_END_INT0                                         \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_COREX_END_INT0)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_COREX_END_INT1                                         \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_COREX_END_INT1)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_COUTFIFO_SIZE_ERROR                                    \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_COUTFIFO_SIZE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_COUTFIFO_LINE_ERROR                                    \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_COUTFIFO_LINE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_COUTFIFO_COL_ERROR                                     \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_COUTFIFO_COL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_COUTFIFO_OVERFLOW_ERROR                                \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_COUTFIFO_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_CINFIFO_TOTAL_SIZE_ERROR_INT                           \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_CINFIFO_TOTAL_SIZE_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_CINFIFO_LINES_ERROR_INT                                \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_CINFIFO_LINES_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_CINFIFO_COLUMNS_ERROR_INT                              \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_CINFIFO_COLUMNS_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_CINFIFO_STREAM_OVERFLOW_SIG                            \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_CINFIFO_STREAM_OVERFLOW_SIG)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_FRM_START_BEFORE_END_CORRUPTED                         \
	EVENT_ID(IPP_FRO_INT0_CTX1_BASE, IPP_FRO_INT0_CTX1_FRAME_START_BEFORE_FRAME_END_CORRUPTED)

#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_FRAME_START                                            \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_FRAME_START)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_FRAME_END_INTERRUPT                                    \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_FRAME_END_INTERRUPT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_FRAME_INT_ON_ROW_COL_INFO                              \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_FRAME_INT_ON_ROW_COL_INFO)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_IRQ_CORRUPTED                                          \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_IRQ_CORRUPTED)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_COREX_ERROR_INT                                        \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_COREX_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_P_SLVERR                                               \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_P_SLVERR)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_PRE_FRAME_END_INTERRUPT                                \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_PRE_FRAME_END_INTERRUPT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_COUTFIFO_DATA_OUT_END_INT                              \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_COUTFIFO_DATA_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_COUTFIFO_FRAME_OUT_END_INT                             \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_COUTFIFO_FRAME_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_STRP_OUT_DMA_IN_LAST                                   \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_STRP_OUT_DMA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_BDS_DATA_OUT_LAST                                      \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_BDS_DATA_OUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_ZSL_OUT_DMA_IN_LAST                                    \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_ZSL_OUT_DMA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_BCROP1_DATA_IN_LAST                                    \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_BCROP1_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_BCROP0_DATA_IN_LAST                                    \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_BCROP0_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_RGBYHIST2DMA_DONE                                      \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_RGBYHIST2DMA_DONE)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_RGBYHIST_DATA_OUT_LAST                                 \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_RGBYHIST_DATA_OUT_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_THSTAT_DATA_IN_LAST                                    \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_THSTAT_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_GP_DATA_IN_LAST                                        \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_GP_DATA_IN_LAST)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_CINFIFO_DATA_OUT_END_INT                               \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_CINFIFO_DATA_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_CINFIFO_FRAME_OUT_END_INT                              \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_CINFIFO_FRAME_OUT_END_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_COREX_END_INT0                                         \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_COREX_END_INT0)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_COREX_END_INT1                                         \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_COREX_END_INT1)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_COUTFIFO_SIZE_ERROR                                    \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_COUTFIFO_SIZE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_COUTFIFO_LINE_ERROR                                    \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_COUTFIFO_LINE_ERROR)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_COUTFIFO_COL_ERROR                                     \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_COUTFIFO_COL_ERROR)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_COUTFIFO_OVERFLOW_ERROR                                \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_COUTFIFO_OVERFLOW_ERROR)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_CINFIFO_TOTAL_SIZE_ERROR_INT                           \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_CINFIFO_TOTAL_SIZE_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_CINFIFO_LINES_ERROR_INT                                \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_CINFIFO_LINES_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_CINFIFO_COLUMNS_ERROR_INT                              \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_CINFIFO_COLUMNS_ERROR_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_CINFIFO_STREAM_OVERFLOW_SIG                            \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_CINFIFO_STREAM_OVERFLOW_SIG)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_FRM_START_BEFORE_END_CORRUPTED                         \
	EVENT_ID(IPP_FRO_INT0_CTX2_BASE, IPP_FRO_INT0_CTX2_FRAME_START_BEFORE_FRAME_END_CORRUPTED)

#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_CDAF_INT                                               \
	EVENT_ID(IPP_FRO_INT1_CTX0_BASE, IPP_FRO_INT1_CTX0_CDAF_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_COUTFIFO_FRAME_OUT_START_INFO                          \
	EVENT_ID(IPP_FRO_INT1_CTX0_BASE, IPP_FRO_INT1_CTX0_COUTFIFO_FRAME_OUT_START_INFO)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_CINFIFO_FRAME_IN_END_INFO                              \
	EVENT_ID(IPP_FRO_INT1_CTX0_BASE, IPP_FRO_INT1_CTX0_CINFIFO_FRAME_IN_END_INFO)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_CINFIFO_FRAME_IN_START_INFO                            \
	EVENT_ID(IPP_FRO_INT1_CTX0_BASE, IPP_FRO_INT1_CTX0_CINFIFO_FRAME_IN_START_INFO)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_THSTAT_STATISTICS_DONE                                 \
	EVENT_ID(IPP_FRO_INT1_CTX0_BASE, IPP_FRO_INT1_CTX0_THSTAT_STATISTICS_DONE)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_FRO_GROUP2_INT                                         \
	EVENT_ID(IPP_FRO_INT1_CTX0_BASE, IPP_FRO_INT1_CTX0_FRO_GROUP2_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_FRO_GROUP4_INT                                         \
	EVENT_ID(IPP_FRO_INT1_CTX0_BASE, IPP_FRO_INT1_CTX0_FRO_GROUP4_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX0_FRO_GROUP5_INT                                         \
	EVENT_ID(IPP_FRO_INT1_CTX0_BASE, IPP_FRO_INT1_CTX0_FRO_GROUP5_INT)

#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_CDAF_INT                                               \
	EVENT_ID(IPP_FRO_INT1_CTX1_BASE, IPP_FRO_INT1_CTX1_CDAF_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_COUTFIFO_FRAME_OUT_START_INFO                          \
	EVENT_ID(IPP_FRO_INT1_CTX1_BASE, IPP_FRO_INT1_CTX1_COUTFIFO_FRAME_OUT_START_INFO)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_CINFIFO_FRAME_IN_END_INFO                              \
	EVENT_ID(IPP_FRO_INT1_CTX1_BASE, IPP_FRO_INT1_CTX1_CINFIFO_FRAME_IN_END_INFO)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_CINFIFO_FRAME_IN_START_INFO                            \
	EVENT_ID(IPP_FRO_INT1_CTX1_BASE, IPP_FRO_INT1_CTX1_CINFIFO_FRAME_IN_START_INFO)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_THSTAT_STATISTICS_DONE                                 \
	EVENT_ID(IPP_FRO_INT1_CTX1_BASE, IPP_FRO_INT1_CTX1_THSTAT_STATISTICS_DONE)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_FRO_GROUP2_INT                                         \
	EVENT_ID(IPP_FRO_INT1_CTX1_BASE, IPP_FRO_INT1_CTX1_FRO_GROUP2_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_FRO_GROUP4_INT                                         \
	EVENT_ID(IPP_FRO_INT1_CTX1_BASE, IPP_FRO_INT1_CTX1_FRO_GROUP4_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX1_FRO_GROUP5_INT                                         \
	EVENT_ID(IPP_FRO_INT1_CTX1_BASE, IPP_FRO_INT1_CTX1_FRO_GROUP5_INT)

#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_CDAF_INT                                               \
	EVENT_ID(IPP_FRO_INT1_CTX2_BASE, IPP_FRO_INT1_CTX2_CDAF_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_COUTFIFO_FRAME_OUT_START_INFO                          \
	EVENT_ID(IPP_FRO_INT1_CTX2_BASE, IPP_FRO_INT1_CTX2_COUTFIFO_FRAME_OUT_START_INFO)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_CINFIFO_FRAME_IN_END_INFO                              \
	EVENT_ID(IPP_FRO_INT1_CTX2_BASE, IPP_FRO_INT1_CTX2_CINFIFO_FRAME_IN_END_INFO)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_CINFIFO_FRAME_IN_START_INFO                            \
	EVENT_ID(IPP_FRO_INT1_CTX2_BASE, IPP_FRO_INT1_CTX2_CINFIFO_FRAME_IN_START_INFO)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_THSTAT_STATISTICS_DONE                                 \
	EVENT_ID(IPP_FRO_INT1_CTX2_BASE, IPP_FRO_INT1_CTX2_THSTAT_STATISTICS_DONE)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_FRO_GROUP2_INT                                         \
	EVENT_ID(IPP_FRO_INT1_CTX2_BASE, IPP_FRO_INT1_CTX2_FRO_GROUP2_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_FRO_GROUP4_INT                                         \
	EVENT_ID(IPP_FRO_INT1_CTX2_BASE, IPP_FRO_INT1_CTX2_FRO_GROUP4_INT)
#define LWIS_PLATFORM_EVENT_ID_IPP_FRO_CTX2_FRO_GROUP5_INT                                         \
	EVENT_ID(IPP_FRO_INT1_CTX2_BASE, IPP_FRO_INT1_CTX2_FRO_GROUP5_INT)

#endif /* DT_BINDINGS_LWIS_PLATFORM_GS201_IPP_H_ */
