## SPDX-License-Identifier: GPL-2.0-only

# vh/kernel/sched
obj-$(CONFIG_VH_SCHED)	+= sched/

# systrace
obj-$(CONFIG_VH_SYSTRACE) += systrace.o

# vh/kernel/thermal
obj-$(CONFIG_VH_THERMAL)  += thermal/

# vh/kernel/fs
obj-$(CONFIG_VH_FS)	+= fs/

# vh/kernel/cgroup
obj-$(CONFIG_VH_CGROUP)	+= cgroup/

# vh/kernel/i2c
obj-$(CONFIG_VH_I2C)     += i2c/
