# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_GS_CHIPID)			+= gs-chipid.o
obj-$(CONFIG_CAL_IF)            	+= cal-if/
obj-$(CONFIG_EXYNOS_PMU_IF)		+= exynos-pmu-if.o
obj-$(CONFIG_EXYNOS_PD)			+= exynos-pd.o
obj-$(CONFIG_EXYNOS_PD_DBG)		+= exynos-pd-dbg.o
obj-$(CONFIG_EXYNOS_PD_EL3)		+= exynos-pd_el3.o
obj-$(CONFIG_ECT)			+= ect_parser.o
# ACPM
obj-$(CONFIG_GS_ACPM)			+= acpm/
