# SPDX-License-Identifier: GPL-2.0-only
#
# Samsung thermal specific Makefile
#

ccflags-y += -I$(srctree)/drivers/thermal

obj-$(CONFIG_GS_THERMAL_V3)			+= gs_thermal.o
gs_thermal-y					+= gs_tmu_v3.o
gs_thermal-y					+= exynos_acpm_tmu.o
gs_thermal-$(CONFIG_EXYNOS_CPU_THERMAL)  += exynos_cpu_cooling.o
gs_thermal-$(CONFIG_ISP_THERMAL)		+= isp_cooling.o

obj-$(CONFIG_GPU_THERMAL)			+= gpu_cooling.o
