# Makefile of gnssif

obj-$(CONFIG_EXYNOS_GNSS_IF_SPI) += gnss_spi.o

obj-$(CONFIG_EXYNOS_GNSS_IF_SPI) += gnssif.o
gnssif-y += gnss_main.o gnss_io_device.o gnss_keplerctl_device.o gnss_link_device.o
gnssif-y += gnss_utils.o
