# SPDX-License-Identifier: GPL-2.0
#
# (C) COPYRIGHT 2019-2020 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU license.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, you can access it online at
# http://www.gnu.org/licenses/gpl-2.0.html.
#
#

# make $(src) as absolute path if it isn't already, by prefixing $(srctree)
src:=$(if $(patsubst /%,,$(src)),$(srctree)/$(src),$(src))

CONFIG_MALI_MEMORY_GROUP_MANAGER ?= m
CONFIG_MALI_PRIORITY_CONTROL_MANAGER ?= m
CONFIG_MALI_PROTECTED_MEMORY_ALLOCATOR ?= m
CONFIG_MALI_PIXEL_STATS ?= m
CONFIG_MALI_PIXEL_GPU_SLC ?= y

mali_pixel-objs :=

ifeq ($(CONFIG_PIXEL_STAT),m)
	ifeq ($(CONFIG_MALI_PIXEL_STATS),m)
		DEFINES += -DCONFIG_MALI_PIXEL_STATS
		mali_pixel-objs += mali_pixel_stats.o
	endif
endif

ifeq ($(CONFIG_MALI_MEMORY_GROUP_MANAGER),m)
	DEFINES += -DCONFIG_MALI_MEMORY_GROUP_MANAGER
	mali_pixel-objs += memory_group_manager.o
	mali_pixel-objs += pixel_slc.o
endif
ifeq ($(CONFIG_MALI_PRIORITY_CONTROL_MANAGER),m)
	DEFINES += -DCONFIG_MALI_PRIORITY_CONTROL_MANAGER
	mali_pixel-objs += priority_control_manager.o
endif
ifeq ($(CONFIG_MALI_PROTECTED_MEMORY_ALLOCATOR),m)
	DEFINES += -DCONFIG_MALI_PROTECTED_MEMORY_ALLOCATOR
	mali_pixel-objs += protected_memory_allocator.o
endif
ifeq ($(CONFIG_MALI_PIXEL_GPU_SLC),y)
	DEFINES += -DCONFIG_MALI_PIXEL_GPU_SLC
	ifeq ($(CONFIG_SOC_ZUMA),y)
		DEFINES += -DPIXEL_GPU_SLC_ACPM_SIGNAL
	endif
endif

# Use our defines when compiling, and include mali platform module headers
ccflags-y += \
    $(DEFINES) \
    -I$(src)/../common/include

# Add kernel module target if any of our config options is enabled
ifneq ($(mali_pixel-objs),)
	obj-m += mali_pixel.o
	mali_pixel-objs += mali_pixel_mod.o
endif
