# SPDX-License-Identifier: GPL-2.0
#
# Makefile for multifunction miscellaneous devices
#

obj-$(CONFIG_MFD_S2MPG10) 		+= s2mpg10-mfd.o
s2mpg10-mfd-$(CONFIG_MFD_S2MPG10) 	+= s2mpg10-core.o s2mpg10-irq.o
obj-$(CONFIG_MFD_S2MPG11) 		+= s2mpg11-mfd.o
s2mpg11-mfd-$(CONFIG_MFD_S2MPG11) 	+= s2mpg11-core.o s2mpg11-irq.o
obj-$(CONFIG_MFD_S2MPG14) 		+= s2mpg14-mfd.o
s2mpg14-mfd-$(CONFIG_MFD_S2MPG14) 	+= s2mpg14-core.o s2mpg14-irq.o
obj-$(CONFIG_MFD_S2MPG15) 		+= s2mpg15-mfd.o
s2mpg15-mfd-$(CONFIG_MFD_S2MPG15) 	+= s2mpg15-core.o s2mpg15-notifier.o
obj-$(CONFIG_MFD_S2MPG1415_GPIO) 	+= s2mpg1415-gpio.o

obj-$(CONFIG_MFD_S2MPG1X_GPIO)		+= s2mpg1x-gpio.o
s2mpg1x-gpio-$(CONFIG_SOC_GS101)	+= s2mpg1x-gpio-gs101.o
s2mpg1x-gpio-$(CONFIG_SOC_GS201)	+= s2mpg1x-gpio-gs201.o

obj-$(CONFIG_MFD_S2MPG12) 		+= s2mpg12-mfd.o
s2mpg12-mfd-objs			+= s2mpg12-core.o s2mpg12-irq.o
obj-$(CONFIG_MFD_S2MPG13) 		+= s2mpg13-mfd.o
s2mpg13-mfd-objs			+= s2mpg13-core.o s2mpg13-notifier.o

obj-$(CONFIG_MFD_SLG51000)		+= slg51000-core.o
obj-$(CONFIG_MFD_SLG51002)		+= slg51002-core.o
