# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the input core drivers.
#

obj-$(CONFIG_INPUT_MISC)	+= misc/
obj-$(CONFIG_GOODIX_FINGERPRINT)+= fingerprint/
obj-$(CONFIG_INPUT_KEYBOARD)	+= keyboard/

obj-$(CONFIG_INPUT_KEYCOMBO)	+= keycombo.o
obj-$(CONFIG_INPUT_KEYDEBUG)    += keydebug.o
keydebug-y := keydebug-core.o

